-- Seed data for the `locations` table.
-- One row per channel. `category` groups channels under their in-game
-- venue (e.g. "BANK PLC"), matching the Discord category name minus the state prefix.
-- `role_gated` defaults to false for all rows -- flip individual rows to true
-- once specific access-gating roles are defined per location.

INSERT INTO locations (state, category, channel_name, is_voice) VALUES
('DELTA', 'BORDER & ENTRY', 'airport', FALSE),
('DELTA', 'BORDER & ENTRY', 'travel-agency', FALSE),
('DELTA', 'BORDER & ENTRY', 'arrival-terminal', FALSE),
('DELTA', 'BORDER & ENTRY', 'refugee-camp', FALSE),
('DELTA', 'BORDER & ENTRY', 'immigration-office', FALSE),
('DELTA', 'BORDER & ENTRY', 'front-desk', FALSE),
('DELTA', 'BORDER & ENTRY', 'parcel-pickup', FALSE),
('DELTA', 'BORDER & ENTRY', 'chief-marshal-office', FALSE),
('DELTA', 'HOTEL & SUITES', 'hotel-reception', FALSE),
('DELTA', 'HOTEL & SUITES', 'hotel-lobby', FALSE),
('DELTA', 'BROADCASTING STATION', 'broadcasting-station', FALSE),
('DELTA', 'BROADCASTING STATION', 'production-room', FALSE),
('DELTA', 'BROADCASTING STATION', 'media-manager', FALSE),
('DELTA', 'JUDICIARY', 'clerk-office', FALSE),
('DELTA', 'JUDICIARY', 'lawyer-chambers', FALSE),
('DELTA', 'JUDICIARY', 'judge-chambers', FALSE),
('DELTA', 'JUDICIARY', 'court-room', TRUE),
('DELTA', 'STATE GOVERNMENT', 'governor-office', FALSE),
('DELTA', 'STATE GOVERNMENT', 'deputy-governor-office', FALSE),
('DELTA', 'STATE GOVERNMENT', 'chief-of-staff', FALSE),
('DELTA', 'STATE GOVERNMENT', 'state-secretariat', FALSE),
('DELTA', 'STATE GOVERNMENT', 'council', FALSE),
('DELTA', 'STATE GOVERNMENT', 'ministry-of-finance', FALSE),
('DELTA', 'STATE GOVERNMENT', 'ministry-of-justice', FALSE),
('DELTA', 'STATE GOVERNMENT', 'ministry-of-agriculture', FALSE),
('DELTA', 'STATE GOVERNMENT', 'ministry-of-housing', FALSE),
('DELTA', 'STATE GOVERNMENT', 'ministry-of-education', FALSE),
('DELTA', 'STATE GOVERNMENT', 'ministry-of-commerce', FALSE),
('DELTA', 'STATE GOVERNMENT', 'ministry-of-power-and-water', FALSE),
('DELTA', 'STATE GOVERNMENT', 'ministry-of-petroleum', FALSE),
('DELTA', 'STATE GOVERNMENT', 'city-hall', TRUE),
('DELTA', 'GOVERNOR''S HOUSE', 'governor-penthouse', FALSE),
('DELTA', 'GOVERNOR''S HOUSE', 'deputy-governor-residence', FALSE),
('DELTA', 'GOVERNOR''S HOUSE', 'governor-guesthouse', FALSE),
('DELTA', 'BANK PLC', 'banking-hall', FALSE),
('DELTA', 'BANK PLC', 'atm', FALSE),
('DELTA', 'BANK PLC', 'customer-care', FALSE),
('DELTA', 'BANK PLC', 'accountant', FALSE),
('DELTA', 'BANK PLC', 'deposit', FALSE),
('DELTA', 'BANK PLC', 'bank-manager', FALSE),
('DELTA', 'BANK PLC', 'transaction-log', FALSE),
('DELTA', 'BANK PLC', 'treasury', FALSE),
('DELTA', 'POLICE DEPARTMENT', 'police-station', FALSE),
('DELTA', 'POLICE DEPARTMENT', 'officers-office', FALSE),
('DELTA', 'POLICE DEPARTMENT', 'investigation-room', FALSE),
('DELTA', 'POLICE DEPARTMENT', 'holding-cell', FALSE),
('DELTA', 'POLICE DEPARTMENT', 'patrol', FALSE),
('DELTA', 'POLICE DEPARTMENT', 'evidence-room', FALSE),
('DELTA', 'POLICE DEPARTMENT', 'dcp-office', FALSE),
('DELTA', 'POLICE DEPARTMENT', 'cp-office', FALSE),
('DELTA', 'POLICE DEPARTMENT', 'police-radio', FALSE),
('DELTA', 'GENERAL HOSPITAL', 'hospital-lobby', FALSE),
('DELTA', 'GENERAL HOSPITAL', 'hospital-reception', FALSE),
('DELTA', 'GENERAL HOSPITAL', 'nursing-station', FALSE),
('DELTA', 'GENERAL HOSPITAL', 'emergency', FALSE),
('DELTA', 'GENERAL HOSPITAL', 'pharmacy-and-laboratory', FALSE),
('DELTA', 'GENERAL HOSPITAL', 'consultation', FALSE),
('DELTA', 'GENERAL HOSPITAL', 'dentistry', FALSE),
('DELTA', 'GENERAL HOSPITAL', 'female-wards', FALSE),
('DELTA', 'GENERAL HOSPITAL', 'male-wards', FALSE),
('DELTA', 'GENERAL HOSPITAL', 'surgical-theatre', FALSE),
('DELTA', 'GENERAL HOSPITAL', 'dmd-office', FALSE),
('DELTA', 'GENERAL HOSPITAL', 'cmd-office', FALSE),
('DELTA', 'PROPERTY AND DEVELOPMENT DEPARTMENT', 'rental-desk', FALSE),
('DELTA', 'PROPERTY AND DEVELOPMENT DEPARTMENT', 'agents-office', FALSE),
('DELTA', 'ELECTRICITY DISTRIBUTION COMPANY', 'help-desk', FALSE),
('DELTA', 'ELECTRICITY DISTRIBUTION COMPANY', 'billing', FALSE),
('DELTA', 'ELECTRICITY DISTRIBUTION COMPANY', 'fault-report', FALSE),
('DELTA', 'ELECTRICITY DISTRIBUTION COMPANY', 'technician-office', FALSE),
('DELTA', 'ELECTRICITY DISTRIBUTION COMPANY', 'operations', FALSE),
('DELTA', 'LOW COST HOUSING', 'okpanam', FALSE),
('DELTA', 'LOW COST HOUSING', 'ozoro', FALSE),
('DELTA', 'MID CLASS HOUSING', 'ughelli', FALSE),
('DELTA', 'MID CLASS HOUSING', 'sapele', FALSE),
('DELTA', 'HIGH CLASS HOUSING', 'asaba', FALSE),
('DELTA', 'HIGH CLASS HOUSING', 'warri', FALSE),
('DELTA', 'CAREER HIGH SCHOOL', 'admin-block', FALSE),
('DELTA', 'CAREER HIGH SCHOOL', 'school-building', FALSE),
('DELTA', 'CAREER HIGH SCHOOL', 'school-hostel', FALSE),
('DELTA', 'STATE UNIVERSITY', 'administrative-block', FALSE),
('DELTA', 'STATE UNIVERSITY', 'school-of-nursing', FALSE),
('DELTA', 'STATE UNIVERSITY', 'school-of-administration', FALSE),
('DELTA', 'STATE UNIVERSITY', 'campus-residence', FALSE),
('DELTA', 'BUSINESS & COMMERCE', 'market', FALSE),
('DELTA', 'BUSINESS & COMMERCE', 'restaurant', FALSE),
('DELTA', 'BUSINESS & COMMERCE', 'abattoir', FALSE),
('DELTA', 'BUSINESS & COMMERCE', 'nnpc-fuel-station', FALSE),
('DELTA', 'BUSINESS & COMMERCE', 'auto-repair', FALSE),
('DELTA', 'BUSINESS & COMMERCE', 'dealership', FALSE),
('DELTA', 'BUSINESS & COMMERCE', 'depot', FALSE),
('DELTA', 'BUSINESS & COMMERCE', 'driving-school', FALSE),
('DELTA', 'BUSINESS & COMMERCE', 'club-house', FALSE),
('DELTA', 'BUSINESS & COMMERCE', 'bus-park', FALSE),
('DELTA', 'BUSINESS & COMMERCE', 'taxi-company', FALSE),
('DELTA', 'BUSINESS & COMMERCE', 'industrial-goods', FALSE),
('DELTA', 'BUSINESS & COMMERCE', 'food-beverages-industry', FALSE),
('DELTA', 'BUSINESS & COMMERCE', 'refinery', FALSE),
('DELTA', 'BUSINESS & COMMERCE', 'oil-well', FALSE),
('DELTA', 'FARMS', 'farmland', FALSE),
('DELTA', 'FARMS', 'Ranch', FALSE),
('DELTA', 'FARMS', 'River', FALSE),
('LAGOS', 'BORDER & ENTRY', 'airport', FALSE),
('LAGOS', 'BORDER & ENTRY', 'travel-agency', FALSE),
('LAGOS', 'BORDER & ENTRY', 'arrival-terminal', FALSE),
('LAGOS', 'BORDER & ENTRY', 'refugee-camp', FALSE),
('LAGOS', 'BORDER & ENTRY', 'immigration-office', FALSE),
('LAGOS', 'BORDER & ENTRY', 'front-desk', FALSE),
('LAGOS', 'BORDER & ENTRY', 'parcel-pickup', FALSE),
('LAGOS', 'BORDER & ENTRY', 'chief-marshal-office', FALSE),
('LAGOS', 'HOTEL & SUITES', 'hotel-reception', FALSE),
('LAGOS', 'HOTEL & SUITES', 'hotel-lobby', FALSE),
('LAGOS', 'BROADCASTING STATION', 'broadcasting-station', FALSE),
('LAGOS', 'BROADCASTING STATION', 'production-room', FALSE),
('LAGOS', 'BROADCASTING STATION', 'media-manager', FALSE),
('LAGOS', 'JUDICIARY', 'clerk-office', FALSE),
('LAGOS', 'JUDICIARY', 'lawyer-chambers', FALSE),
('LAGOS', 'JUDICIARY', 'judge-chambers', FALSE),
('LAGOS', 'JUDICIARY', 'court-room', TRUE),
('LAGOS', 'STATE GOVERNMENT', 'governor-office', FALSE),
('LAGOS', 'STATE GOVERNMENT', 'deputy-governor-office', FALSE),
('LAGOS', 'STATE GOVERNMENT', 'chief-of-staff', FALSE),
('LAGOS', 'STATE GOVERNMENT', 'state-secretariat', FALSE),
('LAGOS', 'STATE GOVERNMENT', 'council', FALSE),
('LAGOS', 'STATE GOVERNMENT', 'ministry-of-finance', FALSE),
('LAGOS', 'STATE GOVERNMENT', 'ministry-of-justice', FALSE),
('LAGOS', 'STATE GOVERNMENT', 'ministry-of-agriculture', FALSE),
('LAGOS', 'STATE GOVERNMENT', 'ministry-of-housing', FALSE),
('LAGOS', 'STATE GOVERNMENT', 'ministry-of-education', FALSE),
('LAGOS', 'STATE GOVERNMENT', 'ministry-of-commerce', FALSE),
('LAGOS', 'STATE GOVERNMENT', 'ministry-of-power-and-water', FALSE),
('LAGOS', 'STATE GOVERNMENT', 'ministry-of-petroleum', FALSE),
('LAGOS', 'STATE GOVERNMENT', 'city-hall', TRUE),
('LAGOS', 'GOVERNOR''S HOUSE', 'governor-penthouse', FALSE),
('LAGOS', 'GOVERNOR''S HOUSE', 'deputy-governor-residence', FALSE),
('LAGOS', 'GOVERNOR''S HOUSE', 'governor-guesthouse', FALSE),
('LAGOS', 'BANK PLC', 'banking-hall', FALSE),
('LAGOS', 'BANK PLC', 'atm', FALSE),
('LAGOS', 'BANK PLC', 'customer-care', FALSE),
('LAGOS', 'BANK PLC', 'accountant', FALSE),
('LAGOS', 'BANK PLC', 'deposit', FALSE),
('LAGOS', 'BANK PLC', 'bank-manager', FALSE),
('LAGOS', 'BANK PLC', 'transaction-log', FALSE),
('LAGOS', 'BANK PLC', 'treasury', FALSE),
('LAGOS', 'POLICE DEPARTMENT', 'police-station', FALSE),
('LAGOS', 'POLICE DEPARTMENT', 'officers-office', FALSE),
('LAGOS', 'POLICE DEPARTMENT', 'investigation-room', FALSE),
('LAGOS', 'POLICE DEPARTMENT', 'holding-cell', FALSE),
('LAGOS', 'POLICE DEPARTMENT', 'patrol', FALSE),
('LAGOS', 'POLICE DEPARTMENT', 'evidence-room', FALSE),
('LAGOS', 'POLICE DEPARTMENT', 'dcp-office', FALSE),
('LAGOS', 'POLICE DEPARTMENT', 'cp-office', FALSE),
('LAGOS', 'POLICE DEPARTMENT', 'police-radio', FALSE),
('LAGOS', 'GENERAL HOSPITAL', 'hospital-lobby', FALSE),
('LAGOS', 'GENERAL HOSPITAL', 'hospital-reception', FALSE),
('LAGOS', 'GENERAL HOSPITAL', 'nursing-station', FALSE),
('LAGOS', 'GENERAL HOSPITAL', 'emergency', FALSE),
('LAGOS', 'GENERAL HOSPITAL', 'pharmacy-and-laboratory', FALSE),
('LAGOS', 'GENERAL HOSPITAL', 'consultation', FALSE),
('LAGOS', 'GENERAL HOSPITAL', 'dentistry', FALSE),
('LAGOS', 'GENERAL HOSPITAL', 'female-wards', FALSE),
('LAGOS', 'GENERAL HOSPITAL', 'male-wards', FALSE),
('LAGOS', 'GENERAL HOSPITAL', 'surgical-theatre', FALSE),
('LAGOS', 'GENERAL HOSPITAL', 'dmd-office', FALSE),
('LAGOS', 'GENERAL HOSPITAL', 'cmd-office', FALSE),
('LAGOS', 'PROPERTY AND DEVELOPMENT DEPARTMENT', 'rental-desk', FALSE),
('LAGOS', 'PROPERTY AND DEVELOPMENT DEPARTMENT', 'agents-office', FALSE),
('LAGOS', 'ELECTRICITY DISTRIBUTION COMPANY', 'help-desk', FALSE),
('LAGOS', 'ELECTRICITY DISTRIBUTION COMPANY', 'billing', FALSE),
('LAGOS', 'ELECTRICITY DISTRIBUTION COMPANY', 'fault-report', FALSE),
('LAGOS', 'ELECTRICITY DISTRIBUTION COMPANY', 'technician-office', FALSE),
('LAGOS', 'ELECTRICITY DISTRIBUTION COMPANY', 'operations', FALSE),
('LAGOS', 'GHETTO', 'ajegunle', FALSE),
('LAGOS', 'GHETTO', 'makoko', FALSE),
('LAGOS', 'MAINLAND', 'ikeja', FALSE),
('LAGOS', 'MAINLAND', 'gbagada', FALSE),
('LAGOS', 'MAINLAND', 'yaba', FALSE),
('LAGOS', 'ISLAND', 'lekki-phase-1', FALSE),
('LAGOS', 'ISLAND', 'lekki-phase-2', FALSE),
('LAGOS', 'ISLAND', 'ikoyi', FALSE),
('LAGOS', 'CAREER HIGH SCHOOL', 'admin-block', FALSE),
('LAGOS', 'CAREER HIGH SCHOOL', 'school-building', FALSE),
('LAGOS', 'CAREER HIGH SCHOOL', 'school-hostel', FALSE),
('LAGOS', 'DEFENCE ACADEMY', 'administrative-block', FALSE),
('LAGOS', 'DEFENCE ACADEMY', 'training-ground', FALSE),
('LAGOS', 'DEFENCE ACADEMY', 'lecture-area', FALSE),
('LAGOS', 'DEFENCE ACADEMY', 'campus-residence', FALSE),
('LAGOS', 'BUSINESS & COMMERCE', 'market', FALSE),
('LAGOS', 'BUSINESS & COMMERCE', 'restaurant', FALSE),
('LAGOS', 'BUSINESS & COMMERCE', 'abattoir', FALSE),
('LAGOS', 'BUSINESS & COMMERCE', 'nnpc-fuel-station', FALSE),
('LAGOS', 'BUSINESS & COMMERCE', 'auto-repair', FALSE),
('LAGOS', 'BUSINESS & COMMERCE', 'dealership', FALSE),
('LAGOS', 'BUSINESS & COMMERCE', 'depot', FALSE),
('LAGOS', 'BUSINESS & COMMERCE', 'driving-school', FALSE),
('LAGOS', 'BUSINESS & COMMERCE', 'club-house', FALSE),
('LAGOS', 'BUSINESS & COMMERCE', 'bus-park', FALSE),
('LAGOS', 'BUSINESS & COMMERCE', 'taxi-company', FALSE),
('LAGOS', 'BUSINESS & COMMERCE', 'industrial-goods', FALSE),
('LAGOS', 'BUSINESS & COMMERCE', 'food-beverages-industry', FALSE),
('LAGOS', 'BUSINESS & COMMERCE', 'refinery', FALSE),
('LAGOS', 'BUSINESS & COMMERCE', 'sea-port', FALSE),
('LAGOS', 'FARMS', 'river', FALSE),
('ABUJA', 'BORDER & ENTRY', 'airport', FALSE),
('ABUJA', 'BORDER & ENTRY', 'travel-agency', FALSE),
('ABUJA', 'BORDER & ENTRY', 'arrival-terminal', FALSE),
('ABUJA', 'BORDER & ENTRY', 'refugee-camp', FALSE),
('ABUJA', 'BORDER & ENTRY', 'immigration-office', FALSE),
('ABUJA', 'BORDER & ENTRY', 'front-desk', FALSE),
('ABUJA', 'BORDER & ENTRY', 'parcel-pickup', FALSE),
('ABUJA', 'BORDER & ENTRY', 'chief-marshal-office', FALSE),
('ABUJA', 'HOTEL & SUITES', 'hotel-reception', FALSE),
('ABUJA', 'HOTEL & SUITES', 'hotel-lobby', FALSE),
('ABUJA', 'TELEVISION AUTHORITY', 'broadcasting-station', FALSE),
('ABUJA', 'TELEVISION AUTHORITY', 'production-room', FALSE),
('ABUJA', 'TELEVISION AUTHORITY', 'media-manager', FALSE),
('ABUJA', 'JUDICIARY', 'clerk-office', FALSE),
('ABUJA', 'JUDICIARY', 'lawyer-chambers', FALSE),
('ABUJA', 'JUDICIARY', 'judge-chambers', FALSE),
('ABUJA', 'JUDICIARY', 'court-room', TRUE),
('ABUJA', 'JUDICIARY', 'high-court', TRUE),
('ABUJA', 'FEDERAL GOVERNMENT', 'fct-minister', FALSE),
('ABUJA', 'FEDERAL GOVERNMENT', 'state-secretariat', FALSE),
('ABUJA', 'FEDERAL GOVERNMENT', 'council', FALSE),
('ABUJA', 'FEDERAL GOVERNMENT', 'ministry-of-finance', FALSE),
('ABUJA', 'FEDERAL GOVERNMENT', 'ministry-of-justice', FALSE),
('ABUJA', 'FEDERAL GOVERNMENT', 'ministry-of-agriculture', FALSE),
('ABUJA', 'FEDERAL GOVERNMENT', 'ministry-of-housing', FALSE),
('ABUJA', 'FEDERAL GOVERNMENT', 'ministry-of-education', FALSE),
('ABUJA', 'FEDERAL GOVERNMENT', 'ministry-of-commerce', FALSE),
('ABUJA', 'FEDERAL GOVERNMENT', 'ministry-of-power-and-water', FALSE),
('ABUJA', 'FEDERAL GOVERNMENT', 'ministry-of-petroleum', FALSE),
('ABUJA', 'FEDERAL GOVERNMENT', 'ministry-of-information-and-culture', FALSE),
('ABUJA', 'FEDERAL GOVERNMENT', 'ministry-of-health', FALSE),
('ABUJA', 'FEDERAL GOVERNMENT', 'city-hall', TRUE),
('ABUJA', 'ASO ROCK', 'president-office', FALSE),
('ABUJA', 'ASO ROCK', 'vice-president-office', FALSE),
('ABUJA', 'ASO ROCK', 'chief-of-staff', FALSE),
('ABUJA', 'ASO ROCK', 'presidential-villa', FALSE),
('ABUJA', 'ASO ROCK', 'presidential-guesthouse', FALSE),
('ABUJA', 'ASO ROCK', 'villa-staff-residence', FALSE),
('ABUJA', 'ASO ROCK', 'presidential-banquet-hall', TRUE),
('ABUJA', 'BANK PLC', 'banking-hall', FALSE),
('ABUJA', 'BANK PLC', 'atm', FALSE),
('ABUJA', 'BANK PLC', 'customer-care', FALSE),
('ABUJA', 'BANK PLC', 'accountant', FALSE),
('ABUJA', 'BANK PLC', 'deposit', FALSE),
('ABUJA', 'BANK PLC', 'bank-manager', FALSE),
('ABUJA', 'BANK PLC', 'transaction-log', FALSE),
('ABUJA', 'BANK PLC', 'treasury', FALSE),
('ABUJA', 'CENTRAL BANK OF NIGERIA', 'cbn-lobby', FALSE),
('ABUJA', 'CENTRAL BANK OF NIGERIA', 'vault', FALSE),
('ABUJA', 'CENTRAL BANK OF NIGERIA', 'cbn-deputy', FALSE),
('ABUJA', 'CENTRAL BANK OF NIGERIA', 'cbn-governor', FALSE),
('ABUJA', 'CENTRAL BANK OF NIGERIA', 'cbn-log', FALSE),
('ABUJA', 'POLICE DEPARTMENT', 'police-station', FALSE),
('ABUJA', 'POLICE DEPARTMENT', 'officers-office', FALSE),
('ABUJA', 'POLICE DEPARTMENT', 'investigation-room', FALSE),
('ABUJA', 'POLICE DEPARTMENT', 'holding-cell', FALSE),
('ABUJA', 'POLICE DEPARTMENT', 'patrol', FALSE),
('ABUJA', 'POLICE DEPARTMENT', 'evidence-room', FALSE),
('ABUJA', 'POLICE DEPARTMENT', 'dcp-office', FALSE),
('ABUJA', 'POLICE DEPARTMENT', 'cp-office', FALSE),
('ABUJA', 'POLICE DEPARTMENT', 'police-radio', FALSE),
('ABUJA', 'POLICE DEPARTMENT', 'armoury', FALSE),
('ABUJA', 'POLICE DEPARTMENT', 'igp-office', FALSE),
('ABUJA', 'POLICE DEPARTMENT', 'maximum-prison', FALSE),
('ABUJA', 'GENERAL HOSPITAL', 'hospital-lobby', FALSE),
('ABUJA', 'GENERAL HOSPITAL', 'hospital-reception', FALSE),
('ABUJA', 'GENERAL HOSPITAL', 'nursing-station', FALSE),
('ABUJA', 'GENERAL HOSPITAL', 'emergency', FALSE),
('ABUJA', 'GENERAL HOSPITAL', 'pharmacy-and-laboratory', FALSE),
('ABUJA', 'GENERAL HOSPITAL', 'consultation', FALSE),
('ABUJA', 'GENERAL HOSPITAL', 'dentistry', FALSE),
('ABUJA', 'GENERAL HOSPITAL', 'female-wards', FALSE),
('ABUJA', 'GENERAL HOSPITAL', 'male-wards', FALSE),
('ABUJA', 'GENERAL HOSPITAL', 'surgical-theatre', FALSE),
('ABUJA', 'GENERAL HOSPITAL', 'dmd-office', FALSE),
('ABUJA', 'GENERAL HOSPITAL', 'cmd-office', FALSE),
('ABUJA', 'PROPERTY AND DEVELOPMENT DEPARTMENT', 'rental-desk', FALSE),
('ABUJA', 'PROPERTY AND DEVELOPMENT DEPARTMENT', 'agents-office', FALSE),
('ABUJA', 'ELECTRICITY DISTRIBUTION COMPANY', 'help-desk', FALSE),
('ABUJA', 'ELECTRICITY DISTRIBUTION COMPANY', 'billing', FALSE),
('ABUJA', 'ELECTRICITY DISTRIBUTION COMPANY', 'fault-report', FALSE),
('ABUJA', 'ELECTRICITY DISTRIBUTION COMPANY', 'technician-office', FALSE),
('ABUJA', 'ELECTRICITY DISTRIBUTION COMPANY', 'operations', FALSE),
('ABUJA', 'LOW COST HOUSING', 'karu', FALSE),
('ABUJA', 'MID CLASS HOUSING', 'gwarinpa', FALSE),
('ABUJA', 'MID CLASS HOUSING', 'kubwa', FALSE),
('ABUJA', 'HIGH CLASS HOUSING', 'maitama', FALSE),
('ABUJA', 'HIGH CLASS HOUSING', 'asokoro', FALSE),
('ABUJA', 'CAREER HIGH SCHOOL', 'admin-block', FALSE),
('ABUJA', 'CAREER HIGH SCHOOL', 'school-building', FALSE),
('ABUJA', 'CAREER HIGH SCHOOL', 'school-hostel', FALSE),
('ABUJA', 'UNIVERSITY OF BANKING AND MEDICINE', 'administrative-block', FALSE),
('ABUJA', 'UNIVERSITY OF BANKING AND MEDICINE', 'school-of-medicine-and-surgery', FALSE),
('ABUJA', 'UNIVERSITY OF BANKING AND MEDICINE', 'school-of-banking', FALSE),
('ABUJA', 'UNIVERSITY OF BANKING AND MEDICINE', 'campus-residence', FALSE),
('ABUJA', 'BUSINESS & COMMERCE', 'market', FALSE),
('ABUJA', 'BUSINESS & COMMERCE', 'restaurant', FALSE),
('ABUJA', 'BUSINESS & COMMERCE', 'abattoir', FALSE),
('ABUJA', 'BUSINESS & COMMERCE', 'nnpc-fuel-station', FALSE),
('ABUJA', 'BUSINESS & COMMERCE', 'auto-repair', FALSE),
('ABUJA', 'BUSINESS & COMMERCE', 'dealership', FALSE),
('ABUJA', 'BUSINESS & COMMERCE', 'depot', FALSE),
('ABUJA', 'BUSINESS & COMMERCE', 'driving-school', FALSE),
('ABUJA', 'BUSINESS & COMMERCE', 'club-house', FALSE),
('ABUJA', 'BUSINESS & COMMERCE', 'bus-park', FALSE),
('ABUJA', 'BUSINESS & COMMERCE', 'taxi-company', FALSE),
('ABUJA', 'BUSINESS & COMMERCE', 'industrial-goods', FALSE),
('ABUJA', 'BUSINESS & COMMERCE', 'food-beverages-industry', FALSE),
('ABUJA', 'BUSINESS & COMMERCE', 'refinery', FALSE),
('ABUJA', 'BUSINESS & COMMERCE', 'mining-ground', FALSE),
('ABUJA', 'FARMS', 'farmland', FALSE),
('ABUJA', 'FARMS', 'ranch', FALSE)
ON CONFLICT (state, category, channel_name) DO NOTHING;