-- Seed data for the `locations` table.
-- One row per channel. `category` groups channels under their in-game
-- venue (e.g. "BANK PLC"), matching the Discord category name minus the state prefix.
-- `role_gated` is TRUE for DELTA channels restricted to a specific role/staff
-- position in the design doc (e.g. Bank Staff, Police Officer, a ministry).
-- It's FALSE for channels open to anyone in that state/category, and still
-- FALSE by default for LAGOS/ABUJA rows until their own role docs land --
-- which *role* enforces each TRUE flag is still TBD (see config.py).

INSERT INTO locations (state, category, channel_name, is_voice, role_gated) VALUES
('DELTA', 'BORDER & ENTRY', 'airport', FALSE, FALSE),
('DELTA', 'BORDER & ENTRY', 'travel-agency', FALSE, FALSE),
('DELTA', 'BORDER & ENTRY', 'arrival-terminal', FALSE, FALSE),
('DELTA', 'BORDER & ENTRY', 'refugee-camp', FALSE, FALSE),
('DELTA', 'BORDER & ENTRY', 'immigration-office', FALSE, FALSE),
('DELTA', 'BORDER & ENTRY', 'front-desk', FALSE, TRUE),
('DELTA', 'BORDER & ENTRY', 'parcel-pickup', FALSE, TRUE),
('DELTA', 'BORDER & ENTRY', 'chief-marshal-office', FALSE, TRUE),
('DELTA', 'HOTEL & SUITES', 'hotel-reception', FALSE, FALSE),
('DELTA', 'HOTEL & SUITES', 'hotel-lobby', FALSE, TRUE),
('DELTA', 'BROADCASTING STATION', 'broadcasting-station', FALSE, FALSE),
('DELTA', 'BROADCASTING STATION', 'production-room', FALSE, TRUE),
('DELTA', 'BROADCASTING STATION', 'media-manager', FALSE, TRUE),
('DELTA', 'JUDICIARY', 'clerk-office', FALSE, FALSE),
('DELTA', 'JUDICIARY', 'lawyer-chambers', FALSE, TRUE),
('DELTA', 'JUDICIARY', 'judge-chambers', FALSE, TRUE),
('DELTA', 'JUDICIARY', 'court-room', TRUE, FALSE),
('DELTA', 'STATE GOVERNMENT', 'governor-office', FALSE, TRUE),
('DELTA', 'STATE GOVERNMENT', 'deputy-governor-office', FALSE, TRUE),
('DELTA', 'STATE GOVERNMENT', 'chief-of-staff', FALSE, TRUE),
('DELTA', 'STATE GOVERNMENT', 'state-secretariat', FALSE, TRUE),
('DELTA', 'STATE GOVERNMENT', 'council', FALSE, TRUE),
('DELTA', 'STATE GOVERNMENT', 'ministry-of-finance', FALSE, TRUE),
('DELTA', 'STATE GOVERNMENT', 'ministry-of-justice', FALSE, TRUE),
('DELTA', 'STATE GOVERNMENT', 'ministry-of-agriculture', FALSE, TRUE),
('DELTA', 'STATE GOVERNMENT', 'ministry-of-housing', FALSE, TRUE),
('DELTA', 'STATE GOVERNMENT', 'ministry-of-education', FALSE, TRUE),
('DELTA', 'STATE GOVERNMENT', 'ministry-of-commerce', FALSE, TRUE),
('DELTA', 'STATE GOVERNMENT', 'ministry-of-power-and-water', FALSE, TRUE),
('DELTA', 'STATE GOVERNMENT', 'ministry-of-petroleum', FALSE, TRUE),
('DELTA', 'STATE GOVERNMENT', 'city-hall', TRUE, FALSE),
('DELTA', 'GOVERNOR''S HOUSE', 'governor-penthouse', FALSE, TRUE),
('DELTA', 'GOVERNOR''S HOUSE', 'deputy-governor-residence', FALSE, TRUE),
('DELTA', 'GOVERNOR''S HOUSE', 'governor-guesthouse', FALSE, TRUE),
('DELTA', 'BANK PLC', 'banking-hall', FALSE, FALSE),
('DELTA', 'BANK PLC', 'atm', FALSE, FALSE),
('DELTA', 'BANK PLC', 'customer-care', FALSE, TRUE),
('DELTA', 'BANK PLC', 'accountant', FALSE, TRUE),
('DELTA', 'BANK PLC', 'deposit', FALSE, TRUE),
('DELTA', 'BANK PLC', 'bank-manager', FALSE, TRUE),
('DELTA', 'BANK PLC', 'transaction-log', FALSE, TRUE),
('DELTA', 'BANK PLC', 'treasury', FALSE, TRUE),
('DELTA', 'POLICE DEPARTMENT', 'police-station', FALSE, FALSE),
('DELTA', 'POLICE DEPARTMENT', 'officers-office', FALSE, TRUE),
('DELTA', 'POLICE DEPARTMENT', 'investigation-room', FALSE, TRUE),
('DELTA', 'POLICE DEPARTMENT', 'holding-cell', FALSE, TRUE),
('DELTA', 'POLICE DEPARTMENT', 'patrol', FALSE, TRUE),
('DELTA', 'POLICE DEPARTMENT', 'evidence-room', FALSE, TRUE),
('DELTA', 'POLICE DEPARTMENT', 'dcp-office', FALSE, TRUE),
('DELTA', 'POLICE DEPARTMENT', 'cp-office', FALSE, TRUE),
('DELTA', 'POLICE DEPARTMENT', 'police-radio', FALSE, TRUE),
('DELTA', 'GENERAL HOSPITAL', 'hospital-lobby', FALSE, FALSE),
('DELTA', 'GENERAL HOSPITAL', 'hospital-reception', FALSE, TRUE),
('DELTA', 'GENERAL HOSPITAL', 'nursing-station', FALSE, TRUE),
('DELTA', 'GENERAL HOSPITAL', 'emergency', FALSE, TRUE),
('DELTA', 'GENERAL HOSPITAL', 'pharmacy-and-laboratory', FALSE, TRUE),
('DELTA', 'GENERAL HOSPITAL', 'consultation', FALSE, TRUE),
('DELTA', 'GENERAL HOSPITAL', 'dentistry', FALSE, TRUE),
('DELTA', 'GENERAL HOSPITAL', 'female-wards', FALSE, TRUE),
('DELTA', 'GENERAL HOSPITAL', 'male-wards', FALSE, TRUE),
('DELTA', 'GENERAL HOSPITAL', 'surgical-theatre', FALSE, TRUE),
('DELTA', 'GENERAL HOSPITAL', 'dmd-office', FALSE, TRUE),
('DELTA', 'GENERAL HOSPITAL', 'cmd-office', FALSE, TRUE),
('DELTA', 'PROPERTY AND DEVELOPMENT DEPARTMENT', 'rental-desk', FALSE, FALSE),
('DELTA', 'PROPERTY AND DEVELOPMENT DEPARTMENT', 'agents-office', FALSE, TRUE),
('DELTA', 'ELECTRICITY DISTRIBUTION COMPANY', 'help-desk', FALSE, FALSE),
('DELTA', 'ELECTRICITY DISTRIBUTION COMPANY', 'billing', FALSE, FALSE),
('DELTA', 'ELECTRICITY DISTRIBUTION COMPANY', 'fault-report', FALSE, TRUE),
('DELTA', 'ELECTRICITY DISTRIBUTION COMPANY', 'technician-office', FALSE, TRUE),
('DELTA', 'ELECTRICITY DISTRIBUTION COMPANY', 'operations', FALSE, TRUE),
('DELTA', 'LOW COST HOUSING', 'okpanam', FALSE, FALSE),
('DELTA', 'LOW COST HOUSING', 'ozoro', FALSE, FALSE),
('DELTA', 'MID CLASS HOUSING', 'ughelli', FALSE, TRUE),
('DELTA', 'MID CLASS HOUSING', 'sapele', FALSE, TRUE),
('DELTA', 'HIGH CLASS HOUSING', 'asaba', FALSE, TRUE),
('DELTA', 'HIGH CLASS HOUSING', 'warri', FALSE, TRUE),
('DELTA', 'CAREER HIGH SCHOOL', 'admin-block', FALSE, FALSE),
('DELTA', 'CAREER HIGH SCHOOL', 'school-building', FALSE, TRUE),
('DELTA', 'CAREER HIGH SCHOOL', 'school-hostel', FALSE, TRUE),
('DELTA', 'STATE UNIVERSITY', 'administrative-block', FALSE, FALSE),
('DELTA', 'STATE UNIVERSITY', 'school-of-nursing', FALSE, TRUE),
('DELTA', 'STATE UNIVERSITY', 'school-of-administration', FALSE, TRUE),
('DELTA', 'STATE UNIVERSITY', 'campus-residence', FALSE, TRUE),
('DELTA', 'BUSINESS & COMMERCE', 'market', FALSE, FALSE),
('DELTA', 'BUSINESS & COMMERCE', 'restaurant', FALSE, FALSE),
('DELTA', 'BUSINESS & COMMERCE', 'abattoir', FALSE, FALSE),
('DELTA', 'BUSINESS & COMMERCE', 'nnpc-fuel-station', FALSE, FALSE),
('DELTA', 'BUSINESS & COMMERCE', 'auto-repair', FALSE, FALSE),
('DELTA', 'BUSINESS & COMMERCE', 'dealership', FALSE, FALSE),
('DELTA', 'BUSINESS & COMMERCE', 'depot', FALSE, TRUE),
('DELTA', 'BUSINESS & COMMERCE', 'driving-school', FALSE, FALSE),
('DELTA', 'BUSINESS & COMMERCE', 'club-house', FALSE, FALSE),
('DELTA', 'BUSINESS & COMMERCE', 'bus-park', FALSE, FALSE),
('DELTA', 'BUSINESS & COMMERCE', 'taxi-company', FALSE, FALSE),
('DELTA', 'BUSINESS & COMMERCE', 'industrial-goods', FALSE, TRUE),
('DELTA', 'BUSINESS & COMMERCE', 'food-beverages-industry', FALSE, TRUE),
('DELTA', 'BUSINESS & COMMERCE', 'refinery', FALSE, TRUE),
('DELTA', 'BUSINESS & COMMERCE', 'oil-well', FALSE, TRUE),
('DELTA', 'FARMS', 'farmland', FALSE, TRUE),
('DELTA', 'FARMS', 'Ranch', FALSE, TRUE),
('DELTA', 'FARMS', 'River', FALSE, TRUE),
('LAGOS', 'BORDER & ENTRY', 'airport', FALSE, FALSE),
('LAGOS', 'BORDER & ENTRY', 'travel-agency', FALSE, FALSE),
('LAGOS', 'BORDER & ENTRY', 'arrival-terminal', FALSE, FALSE),
('LAGOS', 'BORDER & ENTRY', 'refugee-camp', FALSE, FALSE),
('LAGOS', 'BORDER & ENTRY', 'immigration-office', FALSE, FALSE),
('LAGOS', 'BORDER & ENTRY', 'front-desk', FALSE, TRUE),
('LAGOS', 'BORDER & ENTRY', 'parcel-pickup', FALSE, TRUE),
('LAGOS', 'BORDER & ENTRY', 'chief-marshal-office', FALSE, TRUE),
('LAGOS', 'HOTEL & SUITES', 'hotel-reception', FALSE, FALSE),
('LAGOS', 'HOTEL & SUITES', 'hotel-lobby', FALSE, TRUE),
('LAGOS', 'BROADCASTING STATION', 'broadcasting-station', FALSE, FALSE),
('LAGOS', 'BROADCASTING STATION', 'production-room', FALSE, TRUE),
('LAGOS', 'BROADCASTING STATION', 'media-manager', FALSE, TRUE),
('LAGOS', 'JUDICIARY', 'clerk-office', FALSE, FALSE),
('LAGOS', 'JUDICIARY', 'lawyer-chambers', FALSE, TRUE),
('LAGOS', 'JUDICIARY', 'judge-chambers', FALSE, TRUE),
('LAGOS', 'JUDICIARY', 'court-room', TRUE, FALSE),
('LAGOS', 'STATE GOVERNMENT', 'governor-office', FALSE, TRUE),
('LAGOS', 'STATE GOVERNMENT', 'deputy-governor-office', FALSE, TRUE),
('LAGOS', 'STATE GOVERNMENT', 'chief-of-staff', FALSE, TRUE),
('LAGOS', 'STATE GOVERNMENT', 'state-secretariat', FALSE, TRUE),
('LAGOS', 'STATE GOVERNMENT', 'council', FALSE, TRUE),
('LAGOS', 'STATE GOVERNMENT', 'ministry-of-finance', FALSE, TRUE),
('LAGOS', 'STATE GOVERNMENT', 'ministry-of-justice', FALSE, TRUE),
('LAGOS', 'STATE GOVERNMENT', 'ministry-of-agriculture', FALSE, TRUE),
('LAGOS', 'STATE GOVERNMENT', 'ministry-of-housing', FALSE, TRUE),
('LAGOS', 'STATE GOVERNMENT', 'ministry-of-education', FALSE, TRUE),
('LAGOS', 'STATE GOVERNMENT', 'ministry-of-commerce', FALSE, TRUE),
('LAGOS', 'STATE GOVERNMENT', 'ministry-of-power-and-water', FALSE, TRUE),
('LAGOS', 'STATE GOVERNMENT', 'ministry-of-petroleum', FALSE, TRUE),
('LAGOS', 'STATE GOVERNMENT', 'city-hall', TRUE, FALSE),
('LAGOS', 'GOVERNOR''S HOUSE', 'governor-penthouse', FALSE, TRUE),
('LAGOS', 'GOVERNOR''S HOUSE', 'deputy-governor-residence', FALSE, TRUE),
('LAGOS', 'GOVERNOR''S HOUSE', 'governor-guesthouse', FALSE, TRUE),
('LAGOS', 'BANK PLC', 'banking-hall', FALSE, FALSE),
('LAGOS', 'BANK PLC', 'atm', FALSE, FALSE),
('LAGOS', 'BANK PLC', 'customer-care', FALSE, TRUE),
('LAGOS', 'BANK PLC', 'accountant', FALSE, TRUE),
('LAGOS', 'BANK PLC', 'deposit', FALSE, TRUE),
('LAGOS', 'BANK PLC', 'bank-manager', FALSE, TRUE),
('LAGOS', 'BANK PLC', 'transaction-log', FALSE, TRUE),
('LAGOS', 'BANK PLC', 'treasury', FALSE, TRUE),
('LAGOS', 'POLICE DEPARTMENT', 'police-station', FALSE, FALSE),
('LAGOS', 'POLICE DEPARTMENT', 'officers-office', FALSE, TRUE),
('LAGOS', 'POLICE DEPARTMENT', 'investigation-room', FALSE, TRUE),
('LAGOS', 'POLICE DEPARTMENT', 'holding-cell', FALSE, TRUE),
('LAGOS', 'POLICE DEPARTMENT', 'patrol', FALSE, TRUE),
('LAGOS', 'POLICE DEPARTMENT', 'evidence-room', FALSE, TRUE),
('LAGOS', 'POLICE DEPARTMENT', 'dcp-office', FALSE, TRUE),
('LAGOS', 'POLICE DEPARTMENT', 'cp-office', FALSE, TRUE),
('LAGOS', 'POLICE DEPARTMENT', 'police-radio', FALSE, TRUE),
('LAGOS', 'GENERAL HOSPITAL', 'hospital-lobby', FALSE, FALSE),
('LAGOS', 'GENERAL HOSPITAL', 'hospital-reception', FALSE, TRUE),
('LAGOS', 'GENERAL HOSPITAL', 'nursing-station', FALSE, TRUE),
('LAGOS', 'GENERAL HOSPITAL', 'emergency', FALSE, TRUE),
('LAGOS', 'GENERAL HOSPITAL', 'pharmacy-and-laboratory', FALSE, TRUE),
('LAGOS', 'GENERAL HOSPITAL', 'consultation', FALSE, TRUE),
('LAGOS', 'GENERAL HOSPITAL', 'dentistry', FALSE, TRUE),
('LAGOS', 'GENERAL HOSPITAL', 'female-wards', FALSE, TRUE),
('LAGOS', 'GENERAL HOSPITAL', 'male-wards', FALSE, TRUE),
('LAGOS', 'GENERAL HOSPITAL', 'surgical-theatre', FALSE, TRUE),
('LAGOS', 'GENERAL HOSPITAL', 'dmd-office', FALSE, TRUE),
('LAGOS', 'GENERAL HOSPITAL', 'cmd-office', FALSE, TRUE),
('LAGOS', 'PROPERTY AND DEVELOPMENT DEPARTMENT', 'rental-desk', FALSE, FALSE),
('LAGOS', 'PROPERTY AND DEVELOPMENT DEPARTMENT', 'agents-office', FALSE, TRUE),
('LAGOS', 'ELECTRICITY DISTRIBUTION COMPANY', 'help-desk', FALSE, FALSE),
('LAGOS', 'ELECTRICITY DISTRIBUTION COMPANY', 'billing', FALSE, FALSE),
('LAGOS', 'ELECTRICITY DISTRIBUTION COMPANY', 'fault-report', FALSE, TRUE),
('LAGOS', 'ELECTRICITY DISTRIBUTION COMPANY', 'technician-office', FALSE, TRUE),
('LAGOS', 'ELECTRICITY DISTRIBUTION COMPANY', 'operations', FALSE, TRUE),
('LAGOS', 'GHETTO', 'ajegunle', FALSE, FALSE),
('LAGOS', 'GHETTO', 'makoko', FALSE, FALSE),
('LAGOS', 'MAINLAND', 'ikeja', FALSE, TRUE),
('LAGOS', 'MAINLAND', 'gbagada', FALSE, TRUE),
('LAGOS', 'MAINLAND', 'yaba', FALSE, TRUE),
('LAGOS', 'ISLAND', 'lekki-phase-1', FALSE, TRUE),
('LAGOS', 'ISLAND', 'lekki-phase-2', FALSE, TRUE),
('LAGOS', 'ISLAND', 'ikoyi', FALSE, TRUE),
('LAGOS', 'CAREER HIGH SCHOOL', 'admin-block', FALSE, FALSE),
('LAGOS', 'CAREER HIGH SCHOOL', 'school-building', FALSE, TRUE),
('LAGOS', 'CAREER HIGH SCHOOL', 'school-hostel', FALSE, TRUE),
('LAGOS', 'DEFENCE ACADEMY', 'administrative-block', FALSE, FALSE),
('LAGOS', 'DEFENCE ACADEMY', 'training-ground', FALSE, TRUE),
('LAGOS', 'DEFENCE ACADEMY', 'lecture-area', FALSE, TRUE),
('LAGOS', 'DEFENCE ACADEMY', 'campus-residence', FALSE, TRUE),
('LAGOS', 'BUSINESS & COMMERCE', 'market', FALSE, FALSE),
('LAGOS', 'BUSINESS & COMMERCE', 'restaurant', FALSE, FALSE),
('LAGOS', 'BUSINESS & COMMERCE', 'abattoir', FALSE, FALSE),
('LAGOS', 'BUSINESS & COMMERCE', 'nnpc-fuel-station', FALSE, FALSE),
('LAGOS', 'BUSINESS & COMMERCE', 'auto-repair', FALSE, FALSE),
('LAGOS', 'BUSINESS & COMMERCE', 'dealership', FALSE, FALSE),
('LAGOS', 'BUSINESS & COMMERCE', 'depot', FALSE, TRUE),
('LAGOS', 'BUSINESS & COMMERCE', 'driving-school', FALSE, FALSE),
('LAGOS', 'BUSINESS & COMMERCE', 'club-house', FALSE, FALSE),
('LAGOS', 'BUSINESS & COMMERCE', 'bus-park', FALSE, FALSE),
('LAGOS', 'BUSINESS & COMMERCE', 'taxi-company', FALSE, FALSE),
('LAGOS', 'BUSINESS & COMMERCE', 'industrial-goods', FALSE, TRUE),
('LAGOS', 'BUSINESS & COMMERCE', 'food-beverages-industry', FALSE, TRUE),
('LAGOS', 'BUSINESS & COMMERCE', 'refinery', FALSE, TRUE),
('LAGOS', 'BUSINESS & COMMERCE', 'sea-port', FALSE, TRUE),
('LAGOS', 'FARMS', 'river', FALSE, TRUE),
('ABUJA', 'BORDER & ENTRY', 'airport', FALSE, FALSE),
('ABUJA', 'BORDER & ENTRY', 'travel-agency', FALSE, FALSE),
('ABUJA', 'BORDER & ENTRY', 'arrival-terminal', FALSE, FALSE),
('ABUJA', 'BORDER & ENTRY', 'refugee-camp', FALSE, FALSE),
('ABUJA', 'BORDER & ENTRY', 'immigration-office', FALSE, FALSE),
('ABUJA', 'BORDER & ENTRY', 'front-desk', FALSE, FALSE),
('ABUJA', 'BORDER & ENTRY', 'parcel-pickup', FALSE, FALSE),
('ABUJA', 'BORDER & ENTRY', 'chief-marshal-office', FALSE, FALSE),
('ABUJA', 'HOTEL & SUITES', 'hotel-reception', FALSE, FALSE),
('ABUJA', 'HOTEL & SUITES', 'hotel-lobby', FALSE, FALSE),
('ABUJA', 'TELEVISION AUTHORITY', 'broadcasting-station', FALSE, FALSE),
('ABUJA', 'TELEVISION AUTHORITY', 'production-room', FALSE, TRUE),
('ABUJA', 'TELEVISION AUTHORITY', 'media-manager', FALSE, TRUE),
('ABUJA', 'JUDICIARY', 'clerk-office', FALSE, FALSE),
('ABUJA', 'JUDICIARY', 'lawyer-chambers', FALSE, FALSE),
('ABUJA', 'JUDICIARY', 'judge-chambers', FALSE, FALSE),
('ABUJA', 'JUDICIARY', 'court-room', TRUE, FALSE),
('ABUJA', 'JUDICIARY', 'high-court', TRUE, FALSE),
('ABUJA', 'FEDERAL GOVERNMENT', 'fct-minister', FALSE, TRUE),
('ABUJA', 'FEDERAL GOVERNMENT', 'state-secretariat', FALSE, TRUE),
('ABUJA', 'FEDERAL GOVERNMENT', 'council', FALSE, TRUE),
('ABUJA', 'FEDERAL GOVERNMENT', 'ministry-of-finance', FALSE, TRUE),
('ABUJA', 'FEDERAL GOVERNMENT', 'ministry-of-justice', FALSE, TRUE),
('ABUJA', 'FEDERAL GOVERNMENT', 'ministry-of-agriculture', FALSE, TRUE),
('ABUJA', 'FEDERAL GOVERNMENT', 'ministry-of-housing', FALSE, TRUE),
('ABUJA', 'FEDERAL GOVERNMENT', 'ministry-of-education', FALSE, TRUE),
('ABUJA', 'FEDERAL GOVERNMENT', 'ministry-of-commerce', FALSE, TRUE),
('ABUJA', 'FEDERAL GOVERNMENT', 'ministry-of-power-and-water', FALSE, TRUE),
('ABUJA', 'FEDERAL GOVERNMENT', 'ministry-of-petroleum', FALSE, TRUE),
('ABUJA', 'FEDERAL GOVERNMENT', 'ministry-of-information-and-culture', FALSE, TRUE),
('ABUJA', 'FEDERAL GOVERNMENT', 'ministry-of-health', FALSE, TRUE),
('ABUJA', 'FEDERAL GOVERNMENT', 'city-hall', TRUE, FALSE),
('ABUJA', 'ASO ROCK', 'president-office', FALSE, TRUE),
('ABUJA', 'ASO ROCK', 'vice-president-office', FALSE, TRUE),
('ABUJA', 'ASO ROCK', 'chief-of-staff', FALSE, TRUE),
('ABUJA', 'ASO ROCK', 'presidential-villa', FALSE, TRUE),
('ABUJA', 'ASO ROCK', 'presidential-guesthouse', FALSE, TRUE),
('ABUJA', 'ASO ROCK', 'villa-staff-residence', FALSE, TRUE),
('ABUJA', 'ASO ROCK', 'presidential-banquet-hall', TRUE, TRUE),
('ABUJA', 'BANK PLC', 'banking-hall', FALSE, FALSE),
('ABUJA', 'BANK PLC', 'atm', FALSE, FALSE),
('ABUJA', 'BANK PLC', 'customer-care', FALSE, TRUE),
('ABUJA', 'BANK PLC', 'accountant', FALSE, TRUE),
('ABUJA', 'BANK PLC', 'deposit', FALSE, TRUE),
('ABUJA', 'BANK PLC', 'bank-manager', FALSE, TRUE),
('ABUJA', 'BANK PLC', 'transaction-log', FALSE, TRUE),
('ABUJA', 'BANK PLC', 'treasury', FALSE, TRUE),
('ABUJA', 'CENTRAL BANK OF NIGERIA', 'cbn-lobby', FALSE, FALSE),
('ABUJA', 'CENTRAL BANK OF NIGERIA', 'vault', FALSE, TRUE),
('ABUJA', 'CENTRAL BANK OF NIGERIA', 'cbn-deputy', FALSE, TRUE),
('ABUJA', 'CENTRAL BANK OF NIGERIA', 'cbn-governor', FALSE, TRUE),
('ABUJA', 'CENTRAL BANK OF NIGERIA', 'cbn-log', FALSE, TRUE),
('ABUJA', 'POLICE DEPARTMENT', 'police-station', FALSE, FALSE),
('ABUJA', 'POLICE DEPARTMENT', 'officers-office', FALSE, TRUE),
('ABUJA', 'POLICE DEPARTMENT', 'investigation-room', FALSE, TRUE),
('ABUJA', 'POLICE DEPARTMENT', 'holding-cell', FALSE, TRUE),
('ABUJA', 'POLICE DEPARTMENT', 'patrol', FALSE, TRUE),
('ABUJA', 'POLICE DEPARTMENT', 'evidence-room', FALSE, TRUE),
('ABUJA', 'POLICE DEPARTMENT', 'dcp-office', FALSE, TRUE),
('ABUJA', 'POLICE DEPARTMENT', 'cp-office', FALSE, TRUE),
('ABUJA', 'POLICE DEPARTMENT', 'police-radio', FALSE, TRUE),
('ABUJA', 'POLICE DEPARTMENT', 'armoury', FALSE, TRUE),
('ABUJA', 'POLICE DEPARTMENT', 'igp-office', FALSE, TRUE),
('ABUJA', 'POLICE DEPARTMENT', 'maximum-prison', FALSE, TRUE),
('ABUJA', 'GENERAL HOSPITAL', 'hospital-lobby', FALSE, FALSE),
('ABUJA', 'GENERAL HOSPITAL', 'hospital-reception', FALSE, TRUE),
('ABUJA', 'GENERAL HOSPITAL', 'nursing-station', FALSE, TRUE),
('ABUJA', 'GENERAL HOSPITAL', 'emergency', FALSE, TRUE),
('ABUJA', 'GENERAL HOSPITAL', 'pharmacy-and-laboratory', FALSE, TRUE),
('ABUJA', 'GENERAL HOSPITAL', 'consultation', FALSE, TRUE),
('ABUJA', 'GENERAL HOSPITAL', 'dentistry', FALSE, TRUE),
('ABUJA', 'GENERAL HOSPITAL', 'female-wards', FALSE, TRUE),
('ABUJA', 'GENERAL HOSPITAL', 'male-wards', FALSE, TRUE),
('ABUJA', 'GENERAL HOSPITAL', 'surgical-theatre', FALSE, TRUE),
('ABUJA', 'GENERAL HOSPITAL', 'dmd-office', FALSE, TRUE),
('ABUJA', 'GENERAL HOSPITAL', 'cmd-office', FALSE, TRUE),
('ABUJA', 'PROPERTY AND DEVELOPMENT DEPARTMENT', 'rental-desk', FALSE, FALSE),
('ABUJA', 'PROPERTY AND DEVELOPMENT DEPARTMENT', 'agents-office', FALSE, TRUE),
('ABUJA', 'ELECTRICITY DISTRIBUTION COMPANY', 'help-desk', FALSE, FALSE),
('ABUJA', 'ELECTRICITY DISTRIBUTION COMPANY', 'billing', FALSE, FALSE),
('ABUJA', 'ELECTRICITY DISTRIBUTION COMPANY', 'fault-report', FALSE, TRUE),
('ABUJA', 'ELECTRICITY DISTRIBUTION COMPANY', 'technician-office', FALSE, TRUE),
('ABUJA', 'ELECTRICITY DISTRIBUTION COMPANY', 'operations', FALSE, TRUE),
('ABUJA', 'LOW COST HOUSING', 'karu', FALSE, FALSE),
('ABUJA', 'MID CLASS HOUSING', 'gwarinpa', FALSE, TRUE),
('ABUJA', 'MID CLASS HOUSING', 'kubwa', FALSE, TRUE),
('ABUJA', 'HIGH CLASS HOUSING', 'maitama', FALSE, TRUE),
('ABUJA', 'HIGH CLASS HOUSING', 'asokoro', FALSE, TRUE),
('ABUJA', 'CAREER HIGH SCHOOL', 'admin-block', FALSE, FALSE),
('ABUJA', 'CAREER HIGH SCHOOL', 'school-building', FALSE, TRUE),
('ABUJA', 'CAREER HIGH SCHOOL', 'school-hostel', FALSE, TRUE),
('ABUJA', 'UNIVERSITY OF BANKING AND MEDICINE', 'administrative-block', FALSE, FALSE),
('ABUJA', 'UNIVERSITY OF BANKING AND MEDICINE', 'school-of-medicine-and-surgery', FALSE, TRUE),
('ABUJA', 'UNIVERSITY OF BANKING AND MEDICINE', 'school-of-banking', FALSE, TRUE),
('ABUJA', 'UNIVERSITY OF BANKING AND MEDICINE', 'campus-residence', FALSE, TRUE),
('ABUJA', 'BUSINESS & COMMERCE', 'market', FALSE, FALSE),
('ABUJA', 'BUSINESS & COMMERCE', 'restaurant', FALSE, FALSE),
('ABUJA', 'BUSINESS & COMMERCE', 'abattoir', FALSE, FALSE),
('ABUJA', 'BUSINESS & COMMERCE', 'nnpc-fuel-station', FALSE, FALSE),
('ABUJA', 'BUSINESS & COMMERCE', 'auto-repair', FALSE, FALSE),
('ABUJA', 'BUSINESS & COMMERCE', 'dealership', FALSE, FALSE),
('ABUJA', 'BUSINESS & COMMERCE', 'depot', FALSE, TRUE),
('ABUJA', 'BUSINESS & COMMERCE', 'driving-school', FALSE, FALSE),
('ABUJA', 'BUSINESS & COMMERCE', 'club-house', FALSE, FALSE),
('ABUJA', 'BUSINESS & COMMERCE', 'bus-park', FALSE, FALSE),
('ABUJA', 'BUSINESS & COMMERCE', 'taxi-company', FALSE, FALSE),
('ABUJA', 'BUSINESS & COMMERCE', 'industrial-goods', FALSE, TRUE),
('ABUJA', 'BUSINESS & COMMERCE', 'food-beverages-industry', FALSE, TRUE),
('ABUJA', 'BUSINESS & COMMERCE', 'refinery', FALSE, TRUE),
('ABUJA', 'BUSINESS & COMMERCE', 'mining-ground', FALSE, TRUE),
('ABUJA', 'FARMS', 'farmland', FALSE, TRUE),
('ABUJA', 'FARMS', 'ranch', FALSE, TRUE)
ON CONFLICT (state, category, channel_name) DO NOTHING;