-- Links each location to the role(s) that may access it. Run after
-- locations_seed.sql and roles_seed.sql.
--
-- Every location is role_gated = TRUE (see locations_seed.sql) -- nothing
-- is ungated. Locations with no specific job-role requirement are gated by
-- the general state location role instead ("Delta" / "Lagos" / "Abuja"),
-- granted to anyone settled in that state -- that's what stops e.g. a
-- Lagos resident from seeing Delta's or Abuja's open areas.
--
-- EVERY group, CENTRAL BANK OF NIGERIA included, also requires that same
-- general state role as an extra AND condition, even when a specific role
-- already applies -- e.g. Warri's channel needs "Warri Resident" AND
-- "Delta" together. The one exception is the arrival-flow trio
-- (arrival-terminal / refugee-camp / immigration-office): those are gated
-- by the state's "Arrival" role alone (the limited-access role Discord's
-- onboarding question grants directly), since a brand-new arrival doesn't
-- hold the general state role yet. arrival-terminal additionally accepts
-- the general state role on its own as a second, separate option, since
-- settled residents can also pass through it.

INSERT INTO location_roles (location_id, group_id, role_id)
SELECT l.id, v.group_id, r.id
FROM (VALUES
  ('DELTA', 'BORDER & ENTRY', 'front-desk', 1, 'Immigration Officer'),
  ('DELTA', 'BORDER & ENTRY', 'front-desk', 1, 'Delta'),
  ('DELTA', 'BORDER & ENTRY', 'parcel-pickup', 2, 'Dispatch Rider'),
  ('DELTA', 'BORDER & ENTRY', 'parcel-pickup', 2, 'Delta'),
  ('DELTA', 'BORDER & ENTRY', 'parcel-pickup', 3, 'Immigration Officer'),
  ('DELTA', 'BORDER & ENTRY', 'parcel-pickup', 3, 'Delta'),
  ('DELTA', 'BORDER & ENTRY', 'chief-marshal-office', 4, 'Chief Immigration Marshal'),
  ('DELTA', 'BORDER & ENTRY', 'chief-marshal-office', 4, 'Delta'),
  ('DELTA', 'HOTEL & SUITES', 'hotel-lobby', 5, 'Hotel Guest'),
  ('DELTA', 'HOTEL & SUITES', 'hotel-lobby', 5, 'Delta'),
  ('DELTA', 'BROADCASTING STATION', 'production-room', 6, 'Media Staff'),
  ('DELTA', 'BROADCASTING STATION', 'production-room', 6, 'Delta Employee'),
  ('DELTA', 'BROADCASTING STATION', 'production-room', 6, 'Delta'),
  ('DELTA', 'BROADCASTING STATION', 'production-room', 7, 'Journalist'),
  ('DELTA', 'BROADCASTING STATION', 'production-room', 7, 'Delta Employee'),
  ('DELTA', 'BROADCASTING STATION', 'production-room', 7, 'Delta'),
  ('DELTA', 'BROADCASTING STATION', 'production-room', 8, 'Reporter'),
  ('DELTA', 'BROADCASTING STATION', 'production-room', 8, 'Delta Employee'),
  ('DELTA', 'BROADCASTING STATION', 'production-room', 8, 'Delta'),
  ('DELTA', 'BROADCASTING STATION', 'media-manager', 9, 'Media Manager'),
  ('DELTA', 'BROADCASTING STATION', 'media-manager', 9, 'Delta Employee'),
  ('DELTA', 'BROADCASTING STATION', 'media-manager', 9, 'Delta'),
  ('DELTA', 'JUDICIARY', 'lawyer-chambers', 10, 'Lawyers'),
  ('DELTA', 'JUDICIARY', 'lawyer-chambers', 10, 'Delta Employee'),
  ('DELTA', 'JUDICIARY', 'lawyer-chambers', 10, 'Delta'),
  ('DELTA', 'JUDICIARY', 'judge-chambers', 11, 'Supreme Judge'),
  ('DELTA', 'JUDICIARY', 'judge-chambers', 11, 'Delta Employee'),
  ('DELTA', 'JUDICIARY', 'judge-chambers', 11, 'Delta'),
  ('DELTA', 'STATE GOVERNMENT', 'governor-office', 12, 'Delta Governor'),
  ('DELTA', 'STATE GOVERNMENT', 'governor-office', 12, 'Delta'),
  ('DELTA', 'STATE GOVERNMENT', 'governor-office', 13, 'Appointment with Governor'),
  ('DELTA', 'STATE GOVERNMENT', 'governor-office', 13, 'Delta'),
  ('DELTA', 'STATE GOVERNMENT', 'deputy-governor-office', 14, 'Governor'),
  ('DELTA', 'STATE GOVERNMENT', 'deputy-governor-office', 14, 'Delta'),
  ('DELTA', 'STATE GOVERNMENT', 'deputy-governor-office', 15, 'Deputy Governor'),
  ('DELTA', 'STATE GOVERNMENT', 'deputy-governor-office', 15, 'Delta'),
  ('DELTA', 'STATE GOVERNMENT', 'deputy-governor-office', 16, 'Appointment with Deputy'),
  ('DELTA', 'STATE GOVERNMENT', 'deputy-governor-office', 16, 'Delta'),
  ('DELTA', 'STATE GOVERNMENT', 'chief-of-staff', 17, 'Delta Commissioner'),
  ('DELTA', 'STATE GOVERNMENT', 'chief-of-staff', 17, 'Delta'),
  ('DELTA', 'STATE GOVERNMENT', 'chief-of-staff', 18, 'Lagos Commissioner'),
  ('DELTA', 'STATE GOVERNMENT', 'chief-of-staff', 18, 'Delta'),
  ('DELTA', 'STATE GOVERNMENT', 'chief-of-staff', 19, 'FCT Commissioner'),
  ('DELTA', 'STATE GOVERNMENT', 'chief-of-staff', 19, 'Delta'),
  ('DELTA', 'STATE GOVERNMENT', 'chief-of-staff', 20, 'President'),
  ('DELTA', 'STATE GOVERNMENT', 'chief-of-staff', 20, 'Delta'),
  ('DELTA', 'STATE GOVERNMENT', 'chief-of-staff', 21, 'Vice President'),
  ('DELTA', 'STATE GOVERNMENT', 'chief-of-staff', 21, 'Delta'),
  ('DELTA', 'STATE GOVERNMENT', 'chief-of-staff', 22, 'FCT Minister'),
  ('DELTA', 'STATE GOVERNMENT', 'chief-of-staff', 22, 'Delta'),
  ('DELTA', 'STATE GOVERNMENT', 'state-secretariat', 23, 'Delta Commissioner'),
  ('DELTA', 'STATE GOVERNMENT', 'state-secretariat', 23, 'Delta'),
  ('DELTA', 'STATE GOVERNMENT', 'state-secretariat', 24, 'Lagos Commissioner'),
  ('DELTA', 'STATE GOVERNMENT', 'state-secretariat', 24, 'Delta'),
  ('DELTA', 'STATE GOVERNMENT', 'state-secretariat', 25, 'FCT Commissioner'),
  ('DELTA', 'STATE GOVERNMENT', 'state-secretariat', 25, 'Delta'),
  ('DELTA', 'STATE GOVERNMENT', 'council', 26, 'Delta Commissioner'),
  ('DELTA', 'STATE GOVERNMENT', 'council', 26, 'Delta'),
  ('DELTA', 'STATE GOVERNMENT', 'ministry-of-finance', 27, 'Delta Commissioner'),
  ('DELTA', 'STATE GOVERNMENT', 'ministry-of-finance', 27, 'Delta'),
  ('DELTA', 'STATE GOVERNMENT', 'ministry-of-finance', 28, 'Bank Manager'),
  ('DELTA', 'STATE GOVERNMENT', 'ministry-of-finance', 28, 'Delta Employee'),
  ('DELTA', 'STATE GOVERNMENT', 'ministry-of-finance', 28, 'Delta'),
  ('DELTA', 'STATE GOVERNMENT', 'ministry-of-finance', 29, 'Minister of Finance'),
  ('DELTA', 'STATE GOVERNMENT', 'ministry-of-finance', 29, 'Delta'),
  ('DELTA', 'STATE GOVERNMENT', 'ministry-of-finance', 30, 'Delta Commissioner of Finance'),
  ('DELTA', 'STATE GOVERNMENT', 'ministry-of-finance', 30, 'Delta'),
  ('DELTA', 'STATE GOVERNMENT', 'ministry-of-justice', 31, 'Delta Commissioner'),
  ('DELTA', 'STATE GOVERNMENT', 'ministry-of-justice', 31, 'Delta'),
  ('DELTA', 'STATE GOVERNMENT', 'ministry-of-justice', 32, 'High Court Judge'),
  ('DELTA', 'STATE GOVERNMENT', 'ministry-of-justice', 32, 'Delta'),
  ('DELTA', 'STATE GOVERNMENT', 'ministry-of-justice', 33, 'Supreme Judge'),
  ('DELTA', 'STATE GOVERNMENT', 'ministry-of-justice', 33, 'Delta'),
  ('DELTA', 'STATE GOVERNMENT', 'ministry-of-agriculture', 34, 'Delta Commissioner'),
  ('DELTA', 'STATE GOVERNMENT', 'ministry-of-agriculture', 34, 'Delta'),
  ('DELTA', 'STATE GOVERNMENT', 'ministry-of-agriculture', 35, 'Minister of Agriculture'),
  ('DELTA', 'STATE GOVERNMENT', 'ministry-of-agriculture', 35, 'Delta'),
  ('DELTA', 'STATE GOVERNMENT', 'ministry-of-housing', 36, 'Delta Commissioner'),
  ('DELTA', 'STATE GOVERNMENT', 'ministry-of-housing', 36, 'Delta'),
  ('DELTA', 'STATE GOVERNMENT', 'ministry-of-housing', 37, 'Minister of Housing'),
  ('DELTA', 'STATE GOVERNMENT', 'ministry-of-housing', 37, 'Delta'),
  ('DELTA', 'STATE GOVERNMENT', 'ministry-of-education', 38, 'Delta Commissioner'),
  ('DELTA', 'STATE GOVERNMENT', 'ministry-of-education', 38, 'Delta'),
  ('DELTA', 'STATE GOVERNMENT', 'ministry-of-education', 39, 'Minister of Education'),
  ('DELTA', 'STATE GOVERNMENT', 'ministry-of-education', 39, 'Delta'),
  ('DELTA', 'STATE GOVERNMENT', 'ministry-of-commerce', 40, 'Delta Commissioner'),
  ('DELTA', 'STATE GOVERNMENT', 'ministry-of-commerce', 40, 'Delta'),
  ('DELTA', 'STATE GOVERNMENT', 'ministry-of-commerce', 41, 'Minister of Trade and Commerce'),
  ('DELTA', 'STATE GOVERNMENT', 'ministry-of-commerce', 41, 'Delta'),
  ('DELTA', 'STATE GOVERNMENT', 'ministry-of-commerce', 42, 'Delta Commissioner of Commerce'),
  ('DELTA', 'STATE GOVERNMENT', 'ministry-of-commerce', 42, 'Delta'),
  ('DELTA', 'STATE GOVERNMENT', 'ministry-of-power-and-water', 43, 'Delta Commissioner'),
  ('DELTA', 'STATE GOVERNMENT', 'ministry-of-power-and-water', 43, 'Delta'),
  ('DELTA', 'STATE GOVERNMENT', 'ministry-of-power-and-water', 44, 'Minister of Power and Water'),
  ('DELTA', 'STATE GOVERNMENT', 'ministry-of-power-and-water', 44, 'Delta'),
  ('DELTA', 'STATE GOVERNMENT', 'ministry-of-petroleum', 45, 'Delta Commissioner'),
  ('DELTA', 'STATE GOVERNMENT', 'ministry-of-petroleum', 45, 'Delta'),
  ('DELTA', 'STATE GOVERNMENT', 'ministry-of-petroleum', 46, 'Minister of Petroleum'),
  ('DELTA', 'STATE GOVERNMENT', 'ministry-of-petroleum', 46, 'Delta'),
  ('DELTA', 'GOVERNOR''S HOUSE', 'governor-penthouse', 49, 'Delta Governor'),
  ('DELTA', 'GOVERNOR''S HOUSE', 'governor-penthouse', 49, 'Delta'),
  ('DELTA', 'GOVERNOR''S HOUSE', 'governor-penthouse', 50, 'Deputy Governor'),
  ('DELTA', 'GOVERNOR''S HOUSE', 'governor-penthouse', 50, 'Delta'),
  ('DELTA', 'GOVERNOR''S HOUSE', 'governor-penthouse', 51, 'Governor Visitor'),
  ('DELTA', 'GOVERNOR''S HOUSE', 'governor-penthouse', 51, 'Delta'),
  ('DELTA', 'GOVERNOR''S HOUSE', 'deputy-governor-residence', 52, 'Delta Governor'),
  ('DELTA', 'GOVERNOR''S HOUSE', 'deputy-governor-residence', 52, 'Delta'),
  ('DELTA', 'GOVERNOR''S HOUSE', 'deputy-governor-residence', 53, 'Deputy Governor'),
  ('DELTA', 'GOVERNOR''S HOUSE', 'deputy-governor-residence', 53, 'Delta'),
  ('DELTA', 'GOVERNOR''S HOUSE', 'deputy-governor-residence', 54, 'Governor Visitor'),
  ('DELTA', 'GOVERNOR''S HOUSE', 'deputy-governor-residence', 54, 'Delta'),
  ('DELTA', 'GOVERNOR''S HOUSE', 'governor-guesthouse', 55, 'Delta Governor'),
  ('DELTA', 'GOVERNOR''S HOUSE', 'governor-guesthouse', 55, 'Delta'),
  ('DELTA', 'GOVERNOR''S HOUSE', 'governor-guesthouse', 56, 'Deputy Governor'),
  ('DELTA', 'GOVERNOR''S HOUSE', 'governor-guesthouse', 56, 'Delta'),
  ('DELTA', 'GOVERNOR''S HOUSE', 'governor-guesthouse', 57, 'Governor Guest'),
  ('DELTA', 'GOVERNOR''S HOUSE', 'governor-guesthouse', 57, 'Delta'),
  ('DELTA', 'BANK PLC', 'customer-care', 58, 'Bank Staff'),
  ('DELTA', 'BANK PLC', 'customer-care', 58, 'Delta Employee'),
  ('DELTA', 'BANK PLC', 'customer-care', 58, 'Delta'),
  ('DELTA', 'BANK PLC', 'accountant', 59, 'Bank Staff'),
  ('DELTA', 'BANK PLC', 'accountant', 59, 'Delta Employee'),
  ('DELTA', 'BANK PLC', 'accountant', 59, 'Delta'),
  ('DELTA', 'BANK PLC', 'deposit', 60, 'Bank Staff'),
  ('DELTA', 'BANK PLC', 'deposit', 60, 'Delta Employee'),
  ('DELTA', 'BANK PLC', 'deposit', 60, 'Delta'),
  ('DELTA', 'BANK PLC', 'bank-manager', 61, 'Bank Staff'),
  ('DELTA', 'BANK PLC', 'bank-manager', 61, 'Delta Employee'),
  ('DELTA', 'BANK PLC', 'bank-manager', 61, 'Delta'),
  ('DELTA', 'BANK PLC', 'transaction-log', 62, 'Bank Manager'),
  ('DELTA', 'BANK PLC', 'transaction-log', 62, 'Delta Employee'),
  ('DELTA', 'BANK PLC', 'transaction-log', 62, 'Delta'),
  ('DELTA', 'BANK PLC', 'treasury', 63, 'Bank Manager'),
  ('DELTA', 'BANK PLC', 'treasury', 63, 'Delta Employee'),
  ('DELTA', 'BANK PLC', 'treasury', 63, 'Delta'),
  ('DELTA', 'POLICE DEPARTMENT', 'officers-office', 64, 'Police Officer'),
  ('DELTA', 'POLICE DEPARTMENT', 'officers-office', 64, 'Delta Employee'),
  ('DELTA', 'POLICE DEPARTMENT', 'officers-office', 64, 'Delta'),
  ('DELTA', 'POLICE DEPARTMENT', 'investigation-room', 65, 'Police Officer'),
  ('DELTA', 'POLICE DEPARTMENT', 'investigation-room', 65, 'Delta Employee'),
  ('DELTA', 'POLICE DEPARTMENT', 'investigation-room', 65, 'Delta'),
  ('DELTA', 'POLICE DEPARTMENT', 'investigation-room', 66, 'Suspect'),
  ('DELTA', 'POLICE DEPARTMENT', 'investigation-room', 66, 'Delta'),
  ('DELTA', 'POLICE DEPARTMENT', 'investigation-room', 67, 'Arrested'),
  ('DELTA', 'POLICE DEPARTMENT', 'investigation-room', 67, 'Delta'),
  ('DELTA', 'POLICE DEPARTMENT', 'holding-cell', 68, 'Police Officer'),
  ('DELTA', 'POLICE DEPARTMENT', 'holding-cell', 68, 'Delta Employee'),
  ('DELTA', 'POLICE DEPARTMENT', 'holding-cell', 68, 'Delta'),
  ('DELTA', 'POLICE DEPARTMENT', 'holding-cell', 69, 'Jailed'),
  ('DELTA', 'POLICE DEPARTMENT', 'holding-cell', 69, 'Delta'),
  ('DELTA', 'POLICE DEPARTMENT', 'holding-cell', 70, 'Arrested'),
  ('DELTA', 'POLICE DEPARTMENT', 'holding-cell', 70, 'Delta'),
  ('DELTA', 'POLICE DEPARTMENT', 'patrol', 71, 'Police Officer'),
  ('DELTA', 'POLICE DEPARTMENT', 'patrol', 71, 'Delta Employee'),
  ('DELTA', 'POLICE DEPARTMENT', 'patrol', 71, 'Delta'),
  ('DELTA', 'POLICE DEPARTMENT', 'evidence-room', 72, 'Police Officer'),
  ('DELTA', 'POLICE DEPARTMENT', 'evidence-room', 72, 'Delta Employee'),
  ('DELTA', 'POLICE DEPARTMENT', 'evidence-room', 72, 'Delta'),
  ('DELTA', 'POLICE DEPARTMENT', 'dcp-office', 73, 'Police Officer'),
  ('DELTA', 'POLICE DEPARTMENT', 'dcp-office', 73, 'Delta Employee'),
  ('DELTA', 'POLICE DEPARTMENT', 'dcp-office', 73, 'Delta'),
  ('DELTA', 'POLICE DEPARTMENT', 'dcp-office', 74, 'Police Station Visitor'),
  ('DELTA', 'POLICE DEPARTMENT', 'dcp-office', 74, 'Delta'),
  ('DELTA', 'POLICE DEPARTMENT', 'cp-office', 75, 'Delta Deputy Chief of Police'),
  ('DELTA', 'POLICE DEPARTMENT', 'cp-office', 75, 'Delta'),
  ('DELTA', 'POLICE DEPARTMENT', 'cp-office', 76, 'Police Station Visitor'),
  ('DELTA', 'POLICE DEPARTMENT', 'cp-office', 76, 'Delta'),
  ('DELTA', 'POLICE DEPARTMENT', 'police-radio', 77, 'Delta Chief of Police'),
  ('DELTA', 'POLICE DEPARTMENT', 'police-radio', 77, 'Delta'),
  ('DELTA', 'POLICE DEPARTMENT', 'police-radio', 78, 'Delta Deputy Chief of Police'),
  ('DELTA', 'POLICE DEPARTMENT', 'police-radio', 78, 'Delta'),
  ('DELTA', 'GENERAL HOSPITAL', 'hospital-reception', 79, 'Hospitalized'),
  ('DELTA', 'GENERAL HOSPITAL', 'hospital-reception', 79, 'Delta'),
  ('DELTA', 'GENERAL HOSPITAL', 'hospital-reception', 80, 'Medic Staff'),
  ('DELTA', 'GENERAL HOSPITAL', 'hospital-reception', 80, 'Delta'),
  ('DELTA', 'GENERAL HOSPITAL', 'hospital-reception', 81, 'Hospital Visitor'),
  ('DELTA', 'GENERAL HOSPITAL', 'hospital-reception', 81, 'Delta'),
  ('DELTA', 'GENERAL HOSPITAL', 'hospital-reception', 82, 'Out Patient'),
  ('DELTA', 'GENERAL HOSPITAL', 'hospital-reception', 82, 'Delta'),
  ('DELTA', 'GENERAL HOSPITAL', 'nursing-station', 83, 'Hospitalized'),
  ('DELTA', 'GENERAL HOSPITAL', 'nursing-station', 83, 'Delta'),
  ('DELTA', 'GENERAL HOSPITAL', 'nursing-station', 84, 'Medic Staff'),
  ('DELTA', 'GENERAL HOSPITAL', 'nursing-station', 84, 'Delta Employee'),
  ('DELTA', 'GENERAL HOSPITAL', 'nursing-station', 84, 'Delta'),
  ('DELTA', 'GENERAL HOSPITAL', 'nursing-station', 85, 'Hospital Visitor'),
  ('DELTA', 'GENERAL HOSPITAL', 'nursing-station', 85, 'Delta'),
  ('DELTA', 'GENERAL HOSPITAL', 'nursing-station', 86, 'Out Patient'),
  ('DELTA', 'GENERAL HOSPITAL', 'nursing-station', 86, 'Delta'),
  ('DELTA', 'GENERAL HOSPITAL', 'emergency', 87, 'Hospitalized'),
  ('DELTA', 'GENERAL HOSPITAL', 'emergency', 87, 'Delta'),
  ('DELTA', 'GENERAL HOSPITAL', 'emergency', 88, 'Medic Staff'),
  ('DELTA', 'GENERAL HOSPITAL', 'emergency', 88, 'Delta Employee'),
  ('DELTA', 'GENERAL HOSPITAL', 'emergency', 88, 'Delta'),
  ('DELTA', 'GENERAL HOSPITAL', 'pharmacy-and-laboratory', 89, 'Medic Staff'),
  ('DELTA', 'GENERAL HOSPITAL', 'pharmacy-and-laboratory', 89, 'Delta Employee'),
  ('DELTA', 'GENERAL HOSPITAL', 'pharmacy-and-laboratory', 89, 'Delta'),
  ('DELTA', 'GENERAL HOSPITAL', 'consultation', 90, 'Hospitalized'),
  ('DELTA', 'GENERAL HOSPITAL', 'consultation', 90, 'Delta'),
  ('DELTA', 'GENERAL HOSPITAL', 'consultation', 91, 'Medic Staff'),
  ('DELTA', 'GENERAL HOSPITAL', 'consultation', 91, 'Delta Employee'),
  ('DELTA', 'GENERAL HOSPITAL', 'consultation', 91, 'Delta'),
  ('DELTA', 'GENERAL HOSPITAL', 'dentistry', 92, 'Dental Patient'),
  ('DELTA', 'GENERAL HOSPITAL', 'dentistry', 92, 'Delta'),
  ('DELTA', 'GENERAL HOSPITAL', 'dentistry', 93, 'Dentist'),
  ('DELTA', 'GENERAL HOSPITAL', 'dentistry', 93, 'Delta Employee'),
  ('DELTA', 'GENERAL HOSPITAL', 'dentistry', 93, 'Delta'),
  ('DELTA', 'GENERAL HOSPITAL', 'female-wards', 94, 'Hospitalized (Female)'),
  ('DELTA', 'GENERAL HOSPITAL', 'female-wards', 94, 'Delta'),
  ('DELTA', 'GENERAL HOSPITAL', 'female-wards', 95, 'Medic Staff'),
  ('DELTA', 'GENERAL HOSPITAL', 'female-wards', 95, 'Delta Employee'),
  ('DELTA', 'GENERAL HOSPITAL', 'female-wards', 95, 'Delta'),
  ('DELTA', 'GENERAL HOSPITAL', 'male-wards', 96, 'Hospitalized (Male)'),
  ('DELTA', 'GENERAL HOSPITAL', 'male-wards', 96, 'Delta'),
  ('DELTA', 'GENERAL HOSPITAL', 'male-wards', 97, 'Medic Staff'),
  ('DELTA', 'GENERAL HOSPITAL', 'male-wards', 97, 'Delta Employee'),
  ('DELTA', 'GENERAL HOSPITAL', 'male-wards', 97, 'Delta'),
  ('DELTA', 'GENERAL HOSPITAL', 'surgical-theatre', 98, 'Surgery Patient'),
  ('DELTA', 'GENERAL HOSPITAL', 'surgical-theatre', 98, 'Delta'),
  ('DELTA', 'GENERAL HOSPITAL', 'surgical-theatre', 99, 'Medic Staff'),
  ('DELTA', 'GENERAL HOSPITAL', 'surgical-theatre', 99, 'Delta Employee'),
  ('DELTA', 'GENERAL HOSPITAL', 'surgical-theatre', 99, 'Delta'),
  ('DELTA', 'GENERAL HOSPITAL', 'dmd-office', 100, 'Medic Staff'),
  ('DELTA', 'GENERAL HOSPITAL', 'dmd-office', 100, 'Delta'),
  ('DELTA', 'GENERAL HOSPITAL', 'dmd-office', 101, 'Deputy Medical Director'),
  ('DELTA', 'GENERAL HOSPITAL', 'dmd-office', 101, 'Delta Employee'),
  ('DELTA', 'GENERAL HOSPITAL', 'dmd-office', 101, 'Delta'),
  ('DELTA', 'GENERAL HOSPITAL', 'dmd-office', 102, 'Director Visitor'),
  ('DELTA', 'GENERAL HOSPITAL', 'dmd-office', 102, 'Delta'),
  ('DELTA', 'GENERAL HOSPITAL', 'cmd-office', 103, 'Chief Medical Director'),
  ('DELTA', 'GENERAL HOSPITAL', 'cmd-office', 103, 'Delta'),
  ('DELTA', 'GENERAL HOSPITAL', 'cmd-office', 104, 'Deputy Medical Director'),
  ('DELTA', 'GENERAL HOSPITAL', 'cmd-office', 104, 'Delta Employee'),
  ('DELTA', 'GENERAL HOSPITAL', 'cmd-office', 104, 'Delta'),
  ('DELTA', 'PROPERTY AND DEVELOPMENT DEPARTMENT', 'agents-office', 105, 'Housing Officer'),
  ('DELTA', 'PROPERTY AND DEVELOPMENT DEPARTMENT', 'agents-office', 105, 'Delta Employee'),
  ('DELTA', 'PROPERTY AND DEVELOPMENT DEPARTMENT', 'agents-office', 105, 'Delta'),
  ('DELTA', 'ELECTRICITY DISTRIBUTION COMPANY', 'billing', 106, 'Delta Resident'),
  ('DELTA', 'ELECTRICITY DISTRIBUTION COMPANY', 'billing', 106, 'Delta'),
  ('DELTA', 'ELECTRICITY DISTRIBUTION COMPANY', 'billing', 107, 'Technician'),
  ('DELTA', 'ELECTRICITY DISTRIBUTION COMPANY', 'billing', 107, 'Delta Employee'),
  ('DELTA', 'ELECTRICITY DISTRIBUTION COMPANY', 'billing', 107, 'Delta'),
  ('DELTA', 'ELECTRICITY DISTRIBUTION COMPANY', 'fault-report', 108, 'Technician'),
  ('DELTA', 'ELECTRICITY DISTRIBUTION COMPANY', 'fault-report', 108, 'Delta Employee'),
  ('DELTA', 'ELECTRICITY DISTRIBUTION COMPANY', 'fault-report', 108, 'Delta'),
  ('DELTA', 'ELECTRICITY DISTRIBUTION COMPANY', 'fault-report', 109, 'Delta Commissioner of Power and Water'),
  ('DELTA', 'ELECTRICITY DISTRIBUTION COMPANY', 'fault-report', 109, 'Delta'),
  ('DELTA', 'ELECTRICITY DISTRIBUTION COMPANY', 'technician-office', 110, 'Technician'),
  ('DELTA', 'ELECTRICITY DISTRIBUTION COMPANY', 'technician-office', 110, 'Delta Employee'),
  ('DELTA', 'ELECTRICITY DISTRIBUTION COMPANY', 'technician-office', 110, 'Delta'),
  ('DELTA', 'ELECTRICITY DISTRIBUTION COMPANY', 'technician-office', 111, 'Delta Commissioner of Power and Water'),
  ('DELTA', 'ELECTRICITY DISTRIBUTION COMPANY', 'technician-office', 111, 'Delta'),
  ('DELTA', 'ELECTRICITY DISTRIBUTION COMPANY', 'operations', 112, 'Delta Commissioner of Power and Water'),
  ('DELTA', 'ELECTRICITY DISTRIBUTION COMPANY', 'operations', 112, 'Delta'),
  ('DELTA', 'MID CLASS HOUSING', 'ughelli', 113, 'Ughelli Resident'),
  ('DELTA', 'MID CLASS HOUSING', 'ughelli', 113, 'Delta'),
  ('DELTA', 'MID CLASS HOUSING', 'sapele', 114, 'Sapele Resident'),
  ('DELTA', 'MID CLASS HOUSING', 'sapele', 114, 'Delta'),
  ('DELTA', 'HIGH CLASS HOUSING', 'asaba', 115, 'Asaba Resident'),
  ('DELTA', 'HIGH CLASS HOUSING', 'asaba', 115, 'Delta'),
  ('DELTA', 'HIGH CLASS HOUSING', 'warri', 116, 'Warri Resident'),
  ('DELTA', 'HIGH CLASS HOUSING', 'warri', 116, 'Delta'),
  ('DELTA', 'CAREER HIGH SCHOOL', 'school-building', 117, 'Student'),
  ('DELTA', 'CAREER HIGH SCHOOL', 'school-building', 117, 'Delta'),
  ('DELTA', 'CAREER HIGH SCHOOL', 'school-hostel', 118, 'Hostel Resident'),
  ('DELTA', 'CAREER HIGH SCHOOL', 'school-hostel', 118, 'Delta'),
  ('DELTA', 'STATE UNIVERSITY', 'school-of-nursing', 119, 'Nursing Student'),
  ('DELTA', 'STATE UNIVERSITY', 'school-of-nursing', 119, 'Delta'),
  ('DELTA', 'STATE UNIVERSITY', 'school-of-nursing', 120, 'Doctor'),
  ('DELTA', 'STATE UNIVERSITY', 'school-of-nursing', 120, 'Delta'),
  ('DELTA', 'STATE UNIVERSITY', 'school-of-administration', 121, 'Admin Student'),
  ('DELTA', 'STATE UNIVERSITY', 'school-of-administration', 121, 'Delta'),
  ('DELTA', 'STATE UNIVERSITY', 'school-of-administration', 122, 'Lecturer'),
  ('DELTA', 'STATE UNIVERSITY', 'school-of-administration', 122, 'Delta'),
  ('DELTA', 'STATE UNIVERSITY', 'campus-residence', 123, 'Campus Resident'),
  ('DELTA', 'STATE UNIVERSITY', 'campus-residence', 123, 'Delta'),
  ('DELTA', 'BUSINESS & COMMERCE', 'depot', 124, 'Business Owner'),
  ('DELTA', 'BUSINESS & COMMERCE', 'depot', 124, 'Delta'),
  ('DELTA', 'BUSINESS & COMMERCE', 'depot', 125, 'Supplier'),
  ('DELTA', 'BUSINESS & COMMERCE', 'depot', 125, 'Delta'),
  ('DELTA', 'BUSINESS & COMMERCE', 'industrial-goods', 126, 'Delta Commissioner of Commerce'),
  ('DELTA', 'BUSINESS & COMMERCE', 'industrial-goods', 126, 'Delta'),
  ('DELTA', 'BUSINESS & COMMERCE', 'industrial-goods', 127, 'Supplier'),
  ('DELTA', 'BUSINESS & COMMERCE', 'industrial-goods', 127, 'Delta'),
  ('DELTA', 'BUSINESS & COMMERCE', 'food-beverages-industry', 128, 'Delta Commissioner of Commerce'),
  ('DELTA', 'BUSINESS & COMMERCE', 'food-beverages-industry', 128, 'Delta'),
  ('DELTA', 'BUSINESS & COMMERCE', 'food-beverages-industry', 129, 'Supplier'),
  ('DELTA', 'BUSINESS & COMMERCE', 'food-beverages-industry', 129, 'Delta'),
  ('DELTA', 'BUSINESS & COMMERCE', 'refinery', 130, 'Delta Commissioner of Petroleum'),
  ('DELTA', 'BUSINESS & COMMERCE', 'refinery', 130, 'Delta'),
  ('DELTA', 'BUSINESS & COMMERCE', 'refinery', 131, 'Gas Station Owner'),
  ('DELTA', 'BUSINESS & COMMERCE', 'refinery', 131, 'Delta'),
  ('DELTA', 'BUSINESS & COMMERCE', 'refinery', 132, 'Chief of Staff'),
  ('DELTA', 'BUSINESS & COMMERCE', 'refinery', 132, 'Delta'),
  ('DELTA', 'BUSINESS & COMMERCE', 'oil-well', 133, 'Delta Commissioner of Petroleum'),
  ('DELTA', 'BUSINESS & COMMERCE', 'oil-well', 133, 'Delta'),
  ('DELTA', 'BUSINESS & COMMERCE', 'oil-well', 134, 'President'),
  ('DELTA', 'BUSINESS & COMMERCE', 'oil-well', 134, 'Delta'),
  ('DELTA', 'BUSINESS & COMMERCE', 'oil-well', 135, 'Vice President'),
  ('DELTA', 'BUSINESS & COMMERCE', 'oil-well', 135, 'Delta'),
  ('DELTA', 'BUSINESS & COMMERCE', 'oil-well', 136, 'Minister of Petroleum'),
  ('DELTA', 'BUSINESS & COMMERCE', 'oil-well', 136, 'Delta'),
  ('DELTA', 'FARMS', 'farmland', 137, 'Farmer'),
  ('DELTA', 'FARMS', 'farmland', 137, 'Delta'),
  ('DELTA', 'FARMS', 'farmland', 138, 'Trader'),
  ('DELTA', 'FARMS', 'farmland', 138, 'Delta'),
  ('DELTA', 'FARMS', 'farmland', 139, 'Delta Commissioner of Agriculture'),
  ('DELTA', 'FARMS', 'farmland', 139, 'Delta'),
  ('DELTA', 'FARMS', 'Ranch', 140, 'Rancher'),
  ('DELTA', 'FARMS', 'Ranch', 140, 'Delta'),
  ('DELTA', 'FARMS', 'Ranch', 141, 'Butcher'),
  ('DELTA', 'FARMS', 'Ranch', 141, 'Delta'),
  ('DELTA', 'FARMS', 'Ranch', 142, 'Delta Commissioner of Agriculture'),
  ('DELTA', 'FARMS', 'Ranch', 142, 'Delta'),
  ('DELTA', 'FARMS', 'River', 143, 'Fisherman'),
  ('DELTA', 'FARMS', 'River', 143, 'Delta'),
  ('DELTA', 'FARMS', 'River', 144, 'Trader'),
  ('DELTA', 'FARMS', 'River', 144, 'Delta'),
  ('DELTA', 'FARMS', 'River', 145, 'Delta Commissioner of Agriculture'),
  ('DELTA', 'FARMS', 'River', 145, 'Delta'),
  ('LAGOS', 'BORDER & ENTRY', 'front-desk', 146, 'Immigration Officer'),
  ('LAGOS', 'BORDER & ENTRY', 'front-desk', 146, 'Lagos'),
  ('LAGOS', 'BORDER & ENTRY', 'parcel-pickup', 147, 'Dispatch Rider'),
  ('LAGOS', 'BORDER & ENTRY', 'parcel-pickup', 147, 'Lagos'),
  ('LAGOS', 'BORDER & ENTRY', 'parcel-pickup', 148, 'Immigration Officer'),
  ('LAGOS', 'BORDER & ENTRY', 'parcel-pickup', 148, 'Lagos'),
  ('LAGOS', 'BORDER & ENTRY', 'chief-marshal-office', 149, 'Chief Immigration Marshal'),
  ('LAGOS', 'BORDER & ENTRY', 'chief-marshal-office', 149, 'Lagos'),
  ('LAGOS', 'HOTEL & SUITES', 'hotel-lobby', 150, 'Hotel Guest'),
  ('LAGOS', 'HOTEL & SUITES', 'hotel-lobby', 150, 'Lagos'),
  ('LAGOS', 'BROADCASTING STATION', 'production-room', 151, 'Media Staff'),
  ('LAGOS', 'BROADCASTING STATION', 'production-room', 151, 'Lagos Employee'),
  ('LAGOS', 'BROADCASTING STATION', 'production-room', 151, 'Lagos'),
  ('LAGOS', 'BROADCASTING STATION', 'production-room', 152, 'Journalist'),
  ('LAGOS', 'BROADCASTING STATION', 'production-room', 152, 'Lagos Employee'),
  ('LAGOS', 'BROADCASTING STATION', 'production-room', 152, 'Lagos'),
  ('LAGOS', 'BROADCASTING STATION', 'production-room', 153, 'Reporter'),
  ('LAGOS', 'BROADCASTING STATION', 'production-room', 153, 'Lagos Employee'),
  ('LAGOS', 'BROADCASTING STATION', 'production-room', 153, 'Lagos'),
  ('LAGOS', 'BROADCASTING STATION', 'media-manager', 154, 'Media Manager'),
  ('LAGOS', 'BROADCASTING STATION', 'media-manager', 154, 'Lagos Employee'),
  ('LAGOS', 'BROADCASTING STATION', 'media-manager', 154, 'Lagos'),
  ('LAGOS', 'JUDICIARY', 'lawyer-chambers', 155, 'Lawyers'),
  ('LAGOS', 'JUDICIARY', 'lawyer-chambers', 155, 'Lagos Employee'),
  ('LAGOS', 'JUDICIARY', 'lawyer-chambers', 155, 'Lagos'),
  ('LAGOS', 'JUDICIARY', 'judge-chambers', 156, 'Supreme Judge'),
  ('LAGOS', 'JUDICIARY', 'judge-chambers', 156, 'Lagos Employee'),
  ('LAGOS', 'JUDICIARY', 'judge-chambers', 156, 'Lagos'),
  ('LAGOS', 'STATE GOVERNMENT', 'governor-office', 157, 'Lagos Governor'),
  ('LAGOS', 'STATE GOVERNMENT', 'governor-office', 157, 'Lagos'),
  ('LAGOS', 'STATE GOVERNMENT', 'governor-office', 158, 'Appointment with Governor'),
  ('LAGOS', 'STATE GOVERNMENT', 'governor-office', 158, 'Lagos'),
  ('LAGOS', 'STATE GOVERNMENT', 'deputy-governor-office', 159, 'Governor'),
  ('LAGOS', 'STATE GOVERNMENT', 'deputy-governor-office', 159, 'Lagos'),
  ('LAGOS', 'STATE GOVERNMENT', 'deputy-governor-office', 160, 'Deputy Governor'),
  ('LAGOS', 'STATE GOVERNMENT', 'deputy-governor-office', 160, 'Lagos'),
  ('LAGOS', 'STATE GOVERNMENT', 'deputy-governor-office', 161, 'Appointment with Deputy'),
  ('LAGOS', 'STATE GOVERNMENT', 'deputy-governor-office', 161, 'Lagos'),
  ('LAGOS', 'STATE GOVERNMENT', 'chief-of-staff', 162, 'Lagos Commissioner'),
  ('LAGOS', 'STATE GOVERNMENT', 'chief-of-staff', 162, 'Lagos'),
  ('LAGOS', 'STATE GOVERNMENT', 'chief-of-staff', 163, 'FCT Commissioner'),
  ('LAGOS', 'STATE GOVERNMENT', 'chief-of-staff', 163, 'Lagos'),
  ('LAGOS', 'STATE GOVERNMENT', 'chief-of-staff', 164, 'President'),
  ('LAGOS', 'STATE GOVERNMENT', 'chief-of-staff', 164, 'Lagos'),
  ('LAGOS', 'STATE GOVERNMENT', 'chief-of-staff', 165, 'Vice President'),
  ('LAGOS', 'STATE GOVERNMENT', 'chief-of-staff', 165, 'Lagos'),
  ('LAGOS', 'STATE GOVERNMENT', 'chief-of-staff', 166, 'FCT Minister'),
  ('LAGOS', 'STATE GOVERNMENT', 'chief-of-staff', 166, 'Lagos'),
  ('LAGOS', 'STATE GOVERNMENT', 'state-secretariat', 167, 'Lagos Commissioner'),
  ('LAGOS', 'STATE GOVERNMENT', 'state-secretariat', 167, 'Lagos'),
  ('LAGOS', 'STATE GOVERNMENT', 'state-secretariat', 168, 'FCT Commissioner'),
  ('LAGOS', 'STATE GOVERNMENT', 'state-secretariat', 168, 'Lagos'),
  ('LAGOS', 'STATE GOVERNMENT', 'council', 169, 'Lagos Commissioner'),
  ('LAGOS', 'STATE GOVERNMENT', 'council', 169, 'Lagos'),
  ('LAGOS', 'STATE GOVERNMENT', 'ministry-of-finance', 170, 'Lagos Commissioner'),
  ('LAGOS', 'STATE GOVERNMENT', 'ministry-of-finance', 170, 'Lagos'),
  ('LAGOS', 'STATE GOVERNMENT', 'ministry-of-finance', 171, 'Bank Manager'),
  ('LAGOS', 'STATE GOVERNMENT', 'ministry-of-finance', 171, 'Lagos Employee'),
  ('LAGOS', 'STATE GOVERNMENT', 'ministry-of-finance', 171, 'Lagos'),
  ('LAGOS', 'STATE GOVERNMENT', 'ministry-of-finance', 172, 'Minister of Finance'),
  ('LAGOS', 'STATE GOVERNMENT', 'ministry-of-finance', 172, 'Lagos'),
  ('LAGOS', 'STATE GOVERNMENT', 'ministry-of-finance', 173, 'Lagos Commissioner of Finance'),
  ('LAGOS', 'STATE GOVERNMENT', 'ministry-of-finance', 173, 'Lagos'),
  ('LAGOS', 'STATE GOVERNMENT', 'ministry-of-justice', 174, 'Lagos Commissioner'),
  ('LAGOS', 'STATE GOVERNMENT', 'ministry-of-justice', 174, 'Lagos'),
  ('LAGOS', 'STATE GOVERNMENT', 'ministry-of-justice', 175, 'High Court Judge'),
  ('LAGOS', 'STATE GOVERNMENT', 'ministry-of-justice', 175, 'Lagos'),
  ('LAGOS', 'STATE GOVERNMENT', 'ministry-of-justice', 176, 'Supreme Judge'),
  ('LAGOS', 'STATE GOVERNMENT', 'ministry-of-justice', 176, 'Lagos'),
  ('LAGOS', 'STATE GOVERNMENT', 'ministry-of-agriculture', 177, 'Lagos Commissioner'),
  ('LAGOS', 'STATE GOVERNMENT', 'ministry-of-agriculture', 177, 'Lagos'),
  ('LAGOS', 'STATE GOVERNMENT', 'ministry-of-agriculture', 178, 'Minister of Agriculture'),
  ('LAGOS', 'STATE GOVERNMENT', 'ministry-of-agriculture', 178, 'Lagos'),
  ('LAGOS', 'STATE GOVERNMENT', 'ministry-of-housing', 179, 'Lagos Commissioner'),
  ('LAGOS', 'STATE GOVERNMENT', 'ministry-of-housing', 179, 'Lagos'),
  ('LAGOS', 'STATE GOVERNMENT', 'ministry-of-housing', 180, 'Minister of Housing'),
  ('LAGOS', 'STATE GOVERNMENT', 'ministry-of-housing', 180, 'Lagos'),
  ('LAGOS', 'STATE GOVERNMENT', 'ministry-of-education', 181, 'Lagos Commissioner'),
  ('LAGOS', 'STATE GOVERNMENT', 'ministry-of-education', 181, 'Lagos'),
  ('LAGOS', 'STATE GOVERNMENT', 'ministry-of-education', 182, 'Minister of Education'),
  ('LAGOS', 'STATE GOVERNMENT', 'ministry-of-education', 182, 'Lagos'),
  ('LAGOS', 'STATE GOVERNMENT', 'ministry-of-commerce', 183, 'Lagos Commissioner'),
  ('LAGOS', 'STATE GOVERNMENT', 'ministry-of-commerce', 183, 'Lagos'),
  ('LAGOS', 'STATE GOVERNMENT', 'ministry-of-commerce', 184, 'Minister of Trade and Commerce'),
  ('LAGOS', 'STATE GOVERNMENT', 'ministry-of-commerce', 184, 'Lagos'),
  ('LAGOS', 'STATE GOVERNMENT', 'ministry-of-commerce', 185, 'Lagos Commissioner of Commerce'),
  ('LAGOS', 'STATE GOVERNMENT', 'ministry-of-commerce', 185, 'Lagos'),
  ('LAGOS', 'STATE GOVERNMENT', 'ministry-of-power-and-water', 186, 'Lagos Commissioner'),
  ('LAGOS', 'STATE GOVERNMENT', 'ministry-of-power-and-water', 186, 'Lagos'),
  ('LAGOS', 'STATE GOVERNMENT', 'ministry-of-power-and-water', 187, 'Minister of Power and Water'),
  ('LAGOS', 'STATE GOVERNMENT', 'ministry-of-power-and-water', 187, 'Lagos'),
  ('LAGOS', 'STATE GOVERNMENT', 'ministry-of-petroleum', 188, 'Lagos Commissioner'),
  ('LAGOS', 'STATE GOVERNMENT', 'ministry-of-petroleum', 188, 'Lagos'),
  ('LAGOS', 'STATE GOVERNMENT', 'ministry-of-petroleum', 189, 'Minister of Petroleum'),
  ('LAGOS', 'STATE GOVERNMENT', 'ministry-of-petroleum', 189, 'Lagos'),
  ('LAGOS', 'GOVERNOR''S HOUSE', 'governor-penthouse', 192, 'Lagos Governor'),
  ('LAGOS', 'GOVERNOR''S HOUSE', 'governor-penthouse', 192, 'Lagos'),
  ('LAGOS', 'GOVERNOR''S HOUSE', 'governor-penthouse', 193, 'Deputy Governor'),
  ('LAGOS', 'GOVERNOR''S HOUSE', 'governor-penthouse', 193, 'Lagos'),
  ('LAGOS', 'GOVERNOR''S HOUSE', 'governor-penthouse', 194, 'Governor Visitor'),
  ('LAGOS', 'GOVERNOR''S HOUSE', 'governor-penthouse', 194, 'Lagos'),
  ('LAGOS', 'GOVERNOR''S HOUSE', 'deputy-governor-residence', 195, 'Lagos Governor'),
  ('LAGOS', 'GOVERNOR''S HOUSE', 'deputy-governor-residence', 195, 'Lagos'),
  ('LAGOS', 'GOVERNOR''S HOUSE', 'deputy-governor-residence', 196, 'Deputy Governor'),
  ('LAGOS', 'GOVERNOR''S HOUSE', 'deputy-governor-residence', 196, 'Lagos'),
  ('LAGOS', 'GOVERNOR''S HOUSE', 'deputy-governor-residence', 197, 'Governor Visitor'),
  ('LAGOS', 'GOVERNOR''S HOUSE', 'deputy-governor-residence', 197, 'Lagos'),
  ('LAGOS', 'GOVERNOR''S HOUSE', 'governor-guesthouse', 198, 'Lagos Governor'),
  ('LAGOS', 'GOVERNOR''S HOUSE', 'governor-guesthouse', 198, 'Lagos'),
  ('LAGOS', 'GOVERNOR''S HOUSE', 'governor-guesthouse', 199, 'Deputy Governor'),
  ('LAGOS', 'GOVERNOR''S HOUSE', 'governor-guesthouse', 199, 'Lagos'),
  ('LAGOS', 'GOVERNOR''S HOUSE', 'governor-guesthouse', 200, 'Governor Guest'),
  ('LAGOS', 'GOVERNOR''S HOUSE', 'governor-guesthouse', 200, 'Lagos'),
  ('LAGOS', 'BANK PLC', 'customer-care', 201, 'Bank Staff'),
  ('LAGOS', 'BANK PLC', 'customer-care', 201, 'Lagos Employee'),
  ('LAGOS', 'BANK PLC', 'customer-care', 201, 'Lagos'),
  ('LAGOS', 'BANK PLC', 'accountant', 202, 'Bank Staff'),
  ('LAGOS', 'BANK PLC', 'accountant', 202, 'Lagos Employee'),
  ('LAGOS', 'BANK PLC', 'accountant', 202, 'Lagos'),
  ('LAGOS', 'BANK PLC', 'deposit', 203, 'Bank Staff'),
  ('LAGOS', 'BANK PLC', 'deposit', 203, 'Lagos Employee'),
  ('LAGOS', 'BANK PLC', 'deposit', 203, 'Lagos'),
  ('LAGOS', 'BANK PLC', 'bank-manager', 204, 'Bank Staff'),
  ('LAGOS', 'BANK PLC', 'bank-manager', 204, 'Lagos Employee'),
  ('LAGOS', 'BANK PLC', 'bank-manager', 204, 'Lagos'),
  ('LAGOS', 'BANK PLC', 'transaction-log', 205, 'Bank Manager'),
  ('LAGOS', 'BANK PLC', 'transaction-log', 205, 'Lagos Employee'),
  ('LAGOS', 'BANK PLC', 'transaction-log', 205, 'Lagos'),
  ('LAGOS', 'BANK PLC', 'treasury', 206, 'Bank Manager'),
  ('LAGOS', 'BANK PLC', 'treasury', 206, 'Lagos Employee'),
  ('LAGOS', 'BANK PLC', 'treasury', 206, 'Lagos'),
  ('LAGOS', 'POLICE DEPARTMENT', 'officers-office', 207, 'Police Officer'),
  ('LAGOS', 'POLICE DEPARTMENT', 'officers-office', 207, 'Lagos Employee'),
  ('LAGOS', 'POLICE DEPARTMENT', 'officers-office', 207, 'Lagos'),
  ('LAGOS', 'POLICE DEPARTMENT', 'investigation-room', 208, 'Police Officer'),
  ('LAGOS', 'POLICE DEPARTMENT', 'investigation-room', 208, 'Lagos Employee'),
  ('LAGOS', 'POLICE DEPARTMENT', 'investigation-room', 208, 'Lagos'),
  ('LAGOS', 'POLICE DEPARTMENT', 'investigation-room', 209, 'Suspect'),
  ('LAGOS', 'POLICE DEPARTMENT', 'investigation-room', 209, 'Lagos'),
  ('LAGOS', 'POLICE DEPARTMENT', 'investigation-room', 210, 'Arrested'),
  ('LAGOS', 'POLICE DEPARTMENT', 'investigation-room', 210, 'Lagos'),
  ('LAGOS', 'POLICE DEPARTMENT', 'holding-cell', 211, 'Police Officer'),
  ('LAGOS', 'POLICE DEPARTMENT', 'holding-cell', 211, 'Lagos Employee'),
  ('LAGOS', 'POLICE DEPARTMENT', 'holding-cell', 211, 'Lagos'),
  ('LAGOS', 'POLICE DEPARTMENT', 'holding-cell', 212, 'Jailed'),
  ('LAGOS', 'POLICE DEPARTMENT', 'holding-cell', 212, 'Lagos'),
  ('LAGOS', 'POLICE DEPARTMENT', 'holding-cell', 213, 'Arrested'),
  ('LAGOS', 'POLICE DEPARTMENT', 'holding-cell', 213, 'Lagos'),
  ('LAGOS', 'POLICE DEPARTMENT', 'patrol', 214, 'Police Officer'),
  ('LAGOS', 'POLICE DEPARTMENT', 'patrol', 214, 'Lagos Employee'),
  ('LAGOS', 'POLICE DEPARTMENT', 'patrol', 214, 'Lagos'),
  ('LAGOS', 'POLICE DEPARTMENT', 'evidence-room', 215, 'Police Officer'),
  ('LAGOS', 'POLICE DEPARTMENT', 'evidence-room', 215, 'Lagos Employee'),
  ('LAGOS', 'POLICE DEPARTMENT', 'evidence-room', 215, 'Lagos'),
  ('LAGOS', 'POLICE DEPARTMENT', 'dcp-office', 216, 'Police Officer'),
  ('LAGOS', 'POLICE DEPARTMENT', 'dcp-office', 216, 'Lagos Employee'),
  ('LAGOS', 'POLICE DEPARTMENT', 'dcp-office', 216, 'Lagos'),
  ('LAGOS', 'POLICE DEPARTMENT', 'dcp-office', 217, 'Police Station Visitor'),
  ('LAGOS', 'POLICE DEPARTMENT', 'dcp-office', 217, 'Lagos'),
  ('LAGOS', 'POLICE DEPARTMENT', 'cp-office', 218, 'Lagos Deputy Chief of Police'),
  ('LAGOS', 'POLICE DEPARTMENT', 'cp-office', 218, 'Lagos'),
  ('LAGOS', 'POLICE DEPARTMENT', 'cp-office', 219, 'Police Station Visitor'),
  ('LAGOS', 'POLICE DEPARTMENT', 'cp-office', 219, 'Lagos'),
  ('LAGOS', 'POLICE DEPARTMENT', 'police-radio', 220, 'Lagos Chief of Police'),
  ('LAGOS', 'POLICE DEPARTMENT', 'police-radio', 220, 'Lagos'),
  ('LAGOS', 'POLICE DEPARTMENT', 'police-radio', 221, 'Lagos Deputy Chief of Police'),
  ('LAGOS', 'POLICE DEPARTMENT', 'police-radio', 221, 'Lagos'),
  ('LAGOS', 'GENERAL HOSPITAL', 'hospital-reception', 222, 'Hospitalized'),
  ('LAGOS', 'GENERAL HOSPITAL', 'hospital-reception', 222, 'Lagos'),
  ('LAGOS', 'GENERAL HOSPITAL', 'hospital-reception', 223, 'Medic Staff'),
  ('LAGOS', 'GENERAL HOSPITAL', 'hospital-reception', 223, 'Lagos'),
  ('LAGOS', 'GENERAL HOSPITAL', 'hospital-reception', 224, 'Hospital Visitor'),
  ('LAGOS', 'GENERAL HOSPITAL', 'hospital-reception', 224, 'Lagos'),
  ('LAGOS', 'GENERAL HOSPITAL', 'hospital-reception', 225, 'Out Patient'),
  ('LAGOS', 'GENERAL HOSPITAL', 'hospital-reception', 225, 'Lagos'),
  ('LAGOS', 'GENERAL HOSPITAL', 'nursing-station', 226, 'Hospitalized'),
  ('LAGOS', 'GENERAL HOSPITAL', 'nursing-station', 226, 'Lagos'),
  ('LAGOS', 'GENERAL HOSPITAL', 'nursing-station', 227, 'Medic Staff'),
  ('LAGOS', 'GENERAL HOSPITAL', 'nursing-station', 227, 'Lagos Employee'),
  ('LAGOS', 'GENERAL HOSPITAL', 'nursing-station', 227, 'Lagos'),
  ('LAGOS', 'GENERAL HOSPITAL', 'nursing-station', 228, 'Hospital Visitor'),
  ('LAGOS', 'GENERAL HOSPITAL', 'nursing-station', 228, 'Lagos'),
  ('LAGOS', 'GENERAL HOSPITAL', 'nursing-station', 229, 'Out Patient'),
  ('LAGOS', 'GENERAL HOSPITAL', 'nursing-station', 229, 'Lagos'),
  ('LAGOS', 'GENERAL HOSPITAL', 'emergency', 230, 'Hospitalized'),
  ('LAGOS', 'GENERAL HOSPITAL', 'emergency', 230, 'Lagos'),
  ('LAGOS', 'GENERAL HOSPITAL', 'emergency', 231, 'Medic Staff'),
  ('LAGOS', 'GENERAL HOSPITAL', 'emergency', 231, 'Lagos Employee'),
  ('LAGOS', 'GENERAL HOSPITAL', 'emergency', 231, 'Lagos'),
  ('LAGOS', 'GENERAL HOSPITAL', 'pharmacy-and-laboratory', 232, 'Medic Staff'),
  ('LAGOS', 'GENERAL HOSPITAL', 'pharmacy-and-laboratory', 232, 'Lagos Employee'),
  ('LAGOS', 'GENERAL HOSPITAL', 'pharmacy-and-laboratory', 232, 'Lagos'),
  ('LAGOS', 'GENERAL HOSPITAL', 'consultation', 233, 'Hospitalized'),
  ('LAGOS', 'GENERAL HOSPITAL', 'consultation', 233, 'Lagos'),
  ('LAGOS', 'GENERAL HOSPITAL', 'consultation', 234, 'Medic Staff'),
  ('LAGOS', 'GENERAL HOSPITAL', 'consultation', 234, 'Lagos Employee'),
  ('LAGOS', 'GENERAL HOSPITAL', 'consultation', 234, 'Lagos'),
  ('LAGOS', 'GENERAL HOSPITAL', 'dentistry', 235, 'Dental Patient'),
  ('LAGOS', 'GENERAL HOSPITAL', 'dentistry', 235, 'Lagos'),
  ('LAGOS', 'GENERAL HOSPITAL', 'dentistry', 236, 'Dentist'),
  ('LAGOS', 'GENERAL HOSPITAL', 'dentistry', 236, 'Lagos Employee'),
  ('LAGOS', 'GENERAL HOSPITAL', 'dentistry', 236, 'Lagos'),
  ('LAGOS', 'GENERAL HOSPITAL', 'female-wards', 237, 'Hospitalized (Female)'),
  ('LAGOS', 'GENERAL HOSPITAL', 'female-wards', 237, 'Lagos'),
  ('LAGOS', 'GENERAL HOSPITAL', 'female-wards', 238, 'Medic Staff'),
  ('LAGOS', 'GENERAL HOSPITAL', 'female-wards', 238, 'Lagos Employee'),
  ('LAGOS', 'GENERAL HOSPITAL', 'female-wards', 238, 'Lagos'),
  ('LAGOS', 'GENERAL HOSPITAL', 'male-wards', 239, 'Hospitalized (Male)'),
  ('LAGOS', 'GENERAL HOSPITAL', 'male-wards', 239, 'Lagos'),
  ('LAGOS', 'GENERAL HOSPITAL', 'male-wards', 240, 'Medic Staff'),
  ('LAGOS', 'GENERAL HOSPITAL', 'male-wards', 240, 'Lagos Employee'),
  ('LAGOS', 'GENERAL HOSPITAL', 'male-wards', 240, 'Lagos'),
  ('LAGOS', 'GENERAL HOSPITAL', 'surgical-theatre', 241, 'Surgery Patient'),
  ('LAGOS', 'GENERAL HOSPITAL', 'surgical-theatre', 241, 'Lagos'),
  ('LAGOS', 'GENERAL HOSPITAL', 'surgical-theatre', 242, 'Medic Staff'),
  ('LAGOS', 'GENERAL HOSPITAL', 'surgical-theatre', 242, 'Lagos Employee'),
  ('LAGOS', 'GENERAL HOSPITAL', 'surgical-theatre', 242, 'Lagos'),
  ('LAGOS', 'GENERAL HOSPITAL', 'dmd-office', 243, 'Medic Staff'),
  ('LAGOS', 'GENERAL HOSPITAL', 'dmd-office', 243, 'Lagos'),
  ('LAGOS', 'GENERAL HOSPITAL', 'dmd-office', 244, 'Deputy Medical Director'),
  ('LAGOS', 'GENERAL HOSPITAL', 'dmd-office', 244, 'Lagos Employee'),
  ('LAGOS', 'GENERAL HOSPITAL', 'dmd-office', 244, 'Lagos'),
  ('LAGOS', 'GENERAL HOSPITAL', 'dmd-office', 245, 'Director Visitor'),
  ('LAGOS', 'GENERAL HOSPITAL', 'dmd-office', 245, 'Lagos'),
  ('LAGOS', 'GENERAL HOSPITAL', 'cmd-office', 246, 'Chief Medical Director'),
  ('LAGOS', 'GENERAL HOSPITAL', 'cmd-office', 246, 'Lagos'),
  ('LAGOS', 'GENERAL HOSPITAL', 'cmd-office', 247, 'Deputy Medical Director'),
  ('LAGOS', 'GENERAL HOSPITAL', 'cmd-office', 247, 'Lagos Employee'),
  ('LAGOS', 'GENERAL HOSPITAL', 'cmd-office', 247, 'Lagos'),
  ('LAGOS', 'PROPERTY AND DEVELOPMENT DEPARTMENT', 'agents-office', 248, 'Housing Officer'),
  ('LAGOS', 'PROPERTY AND DEVELOPMENT DEPARTMENT', 'agents-office', 248, 'Lagos Employee'),
  ('LAGOS', 'PROPERTY AND DEVELOPMENT DEPARTMENT', 'agents-office', 248, 'Lagos'),
  ('LAGOS', 'ELECTRICITY DISTRIBUTION COMPANY', 'fault-report', 249, 'Technician'),
  ('LAGOS', 'ELECTRICITY DISTRIBUTION COMPANY', 'fault-report', 249, 'Lagos Employee'),
  ('LAGOS', 'ELECTRICITY DISTRIBUTION COMPANY', 'fault-report', 249, 'Lagos'),
  ('LAGOS', 'ELECTRICITY DISTRIBUTION COMPANY', 'fault-report', 250, 'Lagos Commissioner of Power and Water'),
  ('LAGOS', 'ELECTRICITY DISTRIBUTION COMPANY', 'fault-report', 250, 'Lagos'),
  ('LAGOS', 'ELECTRICITY DISTRIBUTION COMPANY', 'technician-office', 251, 'Technician'),
  ('LAGOS', 'ELECTRICITY DISTRIBUTION COMPANY', 'technician-office', 251, 'Lagos Employee'),
  ('LAGOS', 'ELECTRICITY DISTRIBUTION COMPANY', 'technician-office', 251, 'Lagos'),
  ('LAGOS', 'ELECTRICITY DISTRIBUTION COMPANY', 'technician-office', 252, 'Lagos Commissioner of Power and Water'),
  ('LAGOS', 'ELECTRICITY DISTRIBUTION COMPANY', 'technician-office', 252, 'Lagos'),
  ('LAGOS', 'ELECTRICITY DISTRIBUTION COMPANY', 'operations', 253, 'Lagos Commissioner of Power and Water'),
  ('LAGOS', 'ELECTRICITY DISTRIBUTION COMPANY', 'operations', 253, 'Lagos'),
  ('LAGOS', 'MAINLAND', 'ikeja', 254, 'Ikeja Resident'),
  ('LAGOS', 'MAINLAND', 'ikeja', 254, 'Lagos'),
  ('LAGOS', 'MAINLAND', 'gbagada', 255, 'Gbagada Resident'),
  ('LAGOS', 'MAINLAND', 'gbagada', 255, 'Lagos'),
  ('LAGOS', 'MAINLAND', 'yaba', 256, 'Yaba Resident'),
  ('LAGOS', 'MAINLAND', 'yaba', 256, 'Lagos'),
  ('LAGOS', 'ISLAND', 'lekki-phase-1', 257, 'Lekki Phase 1 Resident'),
  ('LAGOS', 'ISLAND', 'lekki-phase-1', 257, 'Lagos'),
  ('LAGOS', 'ISLAND', 'lekki-phase-2', 258, 'Lekki Phase 2 Resident'),
  ('LAGOS', 'ISLAND', 'lekki-phase-2', 258, 'Lagos'),
  ('LAGOS', 'ISLAND', 'ikoyi', 259, 'Ikoyi Resident'),
  ('LAGOS', 'ISLAND', 'ikoyi', 259, 'Lagos'),
  ('LAGOS', 'CAREER HIGH SCHOOL', 'school-building', 260, 'Student'),
  ('LAGOS', 'CAREER HIGH SCHOOL', 'school-building', 260, 'Lagos'),
  ('LAGOS', 'CAREER HIGH SCHOOL', 'school-hostel', 261, 'Hostel Resident'),
  ('LAGOS', 'CAREER HIGH SCHOOL', 'school-hostel', 261, 'Lagos'),
  ('LAGOS', 'DEFENCE ACADEMY', 'training-ground', 262, 'Rookie'),
  ('LAGOS', 'DEFENCE ACADEMY', 'training-ground', 262, 'Lagos'),
  ('LAGOS', 'DEFENCE ACADEMY', 'training-ground', 263, 'Detective'),
  ('LAGOS', 'DEFENCE ACADEMY', 'training-ground', 263, 'Lagos'),
  ('LAGOS', 'DEFENCE ACADEMY', 'lecture-area', 264, 'Rookie'),
  ('LAGOS', 'DEFENCE ACADEMY', 'lecture-area', 264, 'Lagos'),
  ('LAGOS', 'DEFENCE ACADEMY', 'lecture-area', 265, 'Detective'),
  ('LAGOS', 'DEFENCE ACADEMY', 'lecture-area', 265, 'Lagos'),
  ('LAGOS', 'DEFENCE ACADEMY', 'campus-residence', 266, 'Campus Resident'),
  ('LAGOS', 'DEFENCE ACADEMY', 'campus-residence', 266, 'Lagos'),
  ('LAGOS', 'BUSINESS & COMMERCE', 'depot', 267, 'Business Owner'),
  ('LAGOS', 'BUSINESS & COMMERCE', 'depot', 267, 'Lagos'),
  ('LAGOS', 'BUSINESS & COMMERCE', 'depot', 268, 'Supplier'),
  ('LAGOS', 'BUSINESS & COMMERCE', 'depot', 268, 'Lagos'),
  ('LAGOS', 'BUSINESS & COMMERCE', 'industrial-goods', 269, 'Lagos Commissioner of Commerce'),
  ('LAGOS', 'BUSINESS & COMMERCE', 'industrial-goods', 269, 'Lagos'),
  ('LAGOS', 'BUSINESS & COMMERCE', 'industrial-goods', 270, 'Supplier'),
  ('LAGOS', 'BUSINESS & COMMERCE', 'industrial-goods', 270, 'Lagos'),
  ('LAGOS', 'BUSINESS & COMMERCE', 'food-beverages-industry', 271, 'Lagos Commissioner of Commerce'),
  ('LAGOS', 'BUSINESS & COMMERCE', 'food-beverages-industry', 271, 'Lagos'),
  ('LAGOS', 'BUSINESS & COMMERCE', 'food-beverages-industry', 272, 'Supplier'),
  ('LAGOS', 'BUSINESS & COMMERCE', 'food-beverages-industry', 272, 'Lagos'),
  ('LAGOS', 'BUSINESS & COMMERCE', 'refinery', 273, 'Lagos Commissioner of Petroleum'),
  ('LAGOS', 'BUSINESS & COMMERCE', 'refinery', 273, 'Lagos'),
  ('LAGOS', 'BUSINESS & COMMERCE', 'refinery', 274, 'Gas Station Owner'),
  ('LAGOS', 'BUSINESS & COMMERCE', 'refinery', 274, 'Lagos'),
  ('LAGOS', 'BUSINESS & COMMERCE', 'refinery', 275, 'Chief of Staff'),
  ('LAGOS', 'BUSINESS & COMMERCE', 'refinery', 275, 'Lagos'),
  ('LAGOS', 'BUSINESS & COMMERCE', 'sea-port', 276, 'Minister of Trade and Commerce'),
  ('LAGOS', 'BUSINESS & COMMERCE', 'sea-port', 276, 'Lagos'),
  ('LAGOS', 'BUSINESS & COMMERCE', 'sea-port', 277, 'Lagos Commissioner of Commerce'),
  ('LAGOS', 'BUSINESS & COMMERCE', 'sea-port', 277, 'Lagos'),
  ('LAGOS', 'FARMS', 'river', 278, 'Fisherman'),
  ('LAGOS', 'FARMS', 'river', 278, 'Lagos'),
  ('LAGOS', 'FARMS', 'river', 279, 'Trader'),
  ('LAGOS', 'FARMS', 'river', 279, 'Lagos'),
  ('LAGOS', 'FARMS', 'river', 280, 'Lagos Commissioner of Agriculture'),
  ('LAGOS', 'FARMS', 'river', 280, 'Lagos'),
  ('ABUJA', 'TELEVISION AUTHORITY', 'production-room', 281, 'Media Staff'),
  ('ABUJA', 'TELEVISION AUTHORITY', 'production-room', 281, 'FCT Employee'),
  ('ABUJA', 'TELEVISION AUTHORITY', 'production-room', 281, 'Abuja'),
  ('ABUJA', 'TELEVISION AUTHORITY', 'production-room', 282, 'Journalist'),
  ('ABUJA', 'TELEVISION AUTHORITY', 'production-room', 282, 'FCT Employee'),
  ('ABUJA', 'TELEVISION AUTHORITY', 'production-room', 282, 'Abuja'),
  ('ABUJA', 'TELEVISION AUTHORITY', 'production-room', 283, 'Reporter'),
  ('ABUJA', 'TELEVISION AUTHORITY', 'production-room', 283, 'FCT Employee'),
  ('ABUJA', 'TELEVISION AUTHORITY', 'production-room', 283, 'Abuja'),
  ('ABUJA', 'TELEVISION AUTHORITY', 'media-manager', 284, 'Media Manager'),
  ('ABUJA', 'TELEVISION AUTHORITY', 'media-manager', 284, 'FCT Employee'),
  ('ABUJA', 'TELEVISION AUTHORITY', 'media-manager', 284, 'Abuja'),
  ('ABUJA', 'FEDERAL GOVERNMENT', 'state-secretariat', 285, 'FCT Commissioner'),
  ('ABUJA', 'FEDERAL GOVERNMENT', 'state-secretariat', 285, 'Abuja'),
  ('ABUJA', 'FEDERAL GOVERNMENT', 'state-secretariat', 286, 'Lagos Commissioner'),
  ('ABUJA', 'FEDERAL GOVERNMENT', 'state-secretariat', 286, 'Abuja'),
  ('ABUJA', 'FEDERAL GOVERNMENT', 'council', 287, 'FCT Commissioner'),
  ('ABUJA', 'FEDERAL GOVERNMENT', 'council', 287, 'Abuja'),
  ('ABUJA', 'FEDERAL GOVERNMENT', 'ministry-of-finance', 288, 'FCT Commissioner'),
  ('ABUJA', 'FEDERAL GOVERNMENT', 'ministry-of-finance', 288, 'Abuja'),
  ('ABUJA', 'FEDERAL GOVERNMENT', 'ministry-of-finance', 289, 'Bank Manager'),
  ('ABUJA', 'FEDERAL GOVERNMENT', 'ministry-of-finance', 289, 'FCT Employee'),
  ('ABUJA', 'FEDERAL GOVERNMENT', 'ministry-of-finance', 289, 'Abuja'),
  ('ABUJA', 'FEDERAL GOVERNMENT', 'ministry-of-finance', 290, 'Minister of Finance'),
  ('ABUJA', 'FEDERAL GOVERNMENT', 'ministry-of-finance', 290, 'Abuja'),
  ('ABUJA', 'FEDERAL GOVERNMENT', 'ministry-of-finance', 291, 'FCT Commissioner of Finance'),
  ('ABUJA', 'FEDERAL GOVERNMENT', 'ministry-of-finance', 291, 'Abuja'),
  ('ABUJA', 'FEDERAL GOVERNMENT', 'ministry-of-justice', 292, 'FCT Commissioner'),
  ('ABUJA', 'FEDERAL GOVERNMENT', 'ministry-of-justice', 292, 'Abuja'),
  ('ABUJA', 'FEDERAL GOVERNMENT', 'ministry-of-justice', 293, 'High Court Judge'),
  ('ABUJA', 'FEDERAL GOVERNMENT', 'ministry-of-justice', 293, 'Abuja'),
  ('ABUJA', 'FEDERAL GOVERNMENT', 'ministry-of-justice', 294, 'Supreme Judge'),
  ('ABUJA', 'FEDERAL GOVERNMENT', 'ministry-of-justice', 294, 'Abuja'),
  ('ABUJA', 'FEDERAL GOVERNMENT', 'ministry-of-agriculture', 295, 'FCT Commissioner'),
  ('ABUJA', 'FEDERAL GOVERNMENT', 'ministry-of-agriculture', 295, 'Abuja'),
  ('ABUJA', 'FEDERAL GOVERNMENT', 'ministry-of-agriculture', 296, 'Minister of Agriculture'),
  ('ABUJA', 'FEDERAL GOVERNMENT', 'ministry-of-agriculture', 296, 'Abuja'),
  ('ABUJA', 'FEDERAL GOVERNMENT', 'ministry-of-housing', 297, 'FCT Commissioner'),
  ('ABUJA', 'FEDERAL GOVERNMENT', 'ministry-of-housing', 297, 'Abuja'),
  ('ABUJA', 'FEDERAL GOVERNMENT', 'ministry-of-housing', 298, 'Minister of Housing'),
  ('ABUJA', 'FEDERAL GOVERNMENT', 'ministry-of-housing', 298, 'Abuja'),
  ('ABUJA', 'FEDERAL GOVERNMENT', 'ministry-of-education', 299, 'FCT Commissioner'),
  ('ABUJA', 'FEDERAL GOVERNMENT', 'ministry-of-education', 299, 'Abuja'),
  ('ABUJA', 'FEDERAL GOVERNMENT', 'ministry-of-education', 300, 'Minister of Education'),
  ('ABUJA', 'FEDERAL GOVERNMENT', 'ministry-of-education', 300, 'Abuja'),
  ('ABUJA', 'FEDERAL GOVERNMENT', 'ministry-of-commerce', 301, 'FCT Commissioner'),
  ('ABUJA', 'FEDERAL GOVERNMENT', 'ministry-of-commerce', 301, 'Abuja'),
  ('ABUJA', 'FEDERAL GOVERNMENT', 'ministry-of-commerce', 302, 'Minister of Trade and Commerce'),
  ('ABUJA', 'FEDERAL GOVERNMENT', 'ministry-of-commerce', 302, 'Abuja'),
  ('ABUJA', 'FEDERAL GOVERNMENT', 'ministry-of-commerce', 303, 'FCT Commissioner of Commerce'),
  ('ABUJA', 'FEDERAL GOVERNMENT', 'ministry-of-commerce', 303, 'Abuja'),
  ('ABUJA', 'FEDERAL GOVERNMENT', 'ministry-of-power-and-water', 304, 'FCT Commissioner'),
  ('ABUJA', 'FEDERAL GOVERNMENT', 'ministry-of-power-and-water', 304, 'Abuja'),
  ('ABUJA', 'FEDERAL GOVERNMENT', 'ministry-of-power-and-water', 305, 'Minister of Power and Water'),
  ('ABUJA', 'FEDERAL GOVERNMENT', 'ministry-of-power-and-water', 305, 'Abuja'),
  ('ABUJA', 'FEDERAL GOVERNMENT', 'ministry-of-petroleum', 306, 'FCT Commissioner'),
  ('ABUJA', 'FEDERAL GOVERNMENT', 'ministry-of-petroleum', 306, 'Abuja'),
  ('ABUJA', 'FEDERAL GOVERNMENT', 'ministry-of-petroleum', 307, 'Minister of Petroleum'),
  ('ABUJA', 'FEDERAL GOVERNMENT', 'ministry-of-petroleum', 307, 'Abuja'),
  ('ABUJA', 'FEDERAL GOVERNMENT', 'ministry-of-information-and-culture', 308, 'FCT Commissioner'),
  ('ABUJA', 'FEDERAL GOVERNMENT', 'ministry-of-information-and-culture', 308, 'Abuja'),
  ('ABUJA', 'FEDERAL GOVERNMENT', 'ministry-of-information-and-culture', 309, 'Minister of Information and Culture'),
  ('ABUJA', 'FEDERAL GOVERNMENT', 'ministry-of-information-and-culture', 309, 'Abuja'),
  ('ABUJA', 'FEDERAL GOVERNMENT', 'ministry-of-health', 310, 'FCT Commissioner'),
  ('ABUJA', 'FEDERAL GOVERNMENT', 'ministry-of-health', 310, 'Abuja'),
  ('ABUJA', 'FEDERAL GOVERNMENT', 'ministry-of-health', 311, 'Minister of Health'),
  ('ABUJA', 'FEDERAL GOVERNMENT', 'ministry-of-health', 311, 'Abuja'),
  ('ABUJA', 'FEDERAL GOVERNMENT', 'city-hall', 312, 'FCT Indigine'),
  ('ABUJA', 'FEDERAL GOVERNMENT', 'city-hall', 312, 'Abuja'),
  ('ABUJA', 'FEDERAL GOVERNMENT', 'city-hall', 313, 'FCT Resident'),
  ('ABUJA', 'FEDERAL GOVERNMENT', 'city-hall', 313, 'Abuja'),
  ('ABUJA', 'ASO ROCK', 'chief-of-staff', 314, 'FCT Commissioner'),
  ('ABUJA', 'ASO ROCK', 'chief-of-staff', 314, 'Abuja'),
  ('ABUJA', 'ASO ROCK', 'chief-of-staff', 315, 'Lagos Commissioner'),
  ('ABUJA', 'ASO ROCK', 'chief-of-staff', 315, 'Abuja'),
  ('ABUJA', 'ASO ROCK', 'chief-of-staff', 316, 'President'),
  ('ABUJA', 'ASO ROCK', 'chief-of-staff', 316, 'Abuja'),
  ('ABUJA', 'ASO ROCK', 'chief-of-staff', 317, 'Vice President'),
  ('ABUJA', 'ASO ROCK', 'chief-of-staff', 317, 'Abuja'),
  ('ABUJA', 'ASO ROCK', 'chief-of-staff', 318, 'FCT Minister'),
  ('ABUJA', 'ASO ROCK', 'chief-of-staff', 318, 'Abuja'),
  ('ABUJA', 'BANK PLC', 'customer-care', 319, 'Bank Staff'),
  ('ABUJA', 'BANK PLC', 'customer-care', 319, 'FCT Employee'),
  ('ABUJA', 'BANK PLC', 'customer-care', 319, 'Abuja'),
  ('ABUJA', 'BANK PLC', 'accountant', 320, 'Bank Staff'),
  ('ABUJA', 'BANK PLC', 'accountant', 320, 'FCT Employee'),
  ('ABUJA', 'BANK PLC', 'accountant', 320, 'Abuja'),
  ('ABUJA', 'BANK PLC', 'deposit', 321, 'Bank Staff'),
  ('ABUJA', 'BANK PLC', 'deposit', 321, 'FCT Employee'),
  ('ABUJA', 'BANK PLC', 'deposit', 321, 'Abuja'),
  ('ABUJA', 'BANK PLC', 'bank-manager', 322, 'Bank Staff'),
  ('ABUJA', 'BANK PLC', 'bank-manager', 322, 'FCT Employee'),
  ('ABUJA', 'BANK PLC', 'bank-manager', 322, 'Abuja'),
  ('ABUJA', 'BANK PLC', 'transaction-log', 323, 'Bank Manager'),
  ('ABUJA', 'BANK PLC', 'transaction-log', 323, 'FCT Employee'),
  ('ABUJA', 'BANK PLC', 'transaction-log', 323, 'Abuja'),
  ('ABUJA', 'BANK PLC', 'treasury', 324, 'Bank Manager'),
  ('ABUJA', 'BANK PLC', 'treasury', 324, 'FCT Employee'),
  ('ABUJA', 'BANK PLC', 'treasury', 324, 'Abuja'),
  ('ABUJA', 'POLICE DEPARTMENT', 'officers-office', 325, 'Police Officer'),
  ('ABUJA', 'POLICE DEPARTMENT', 'officers-office', 325, 'FCT Employee'),
  ('ABUJA', 'POLICE DEPARTMENT', 'officers-office', 325, 'Abuja'),
  ('ABUJA', 'POLICE DEPARTMENT', 'investigation-room', 326, 'Police Officer'),
  ('ABUJA', 'POLICE DEPARTMENT', 'investigation-room', 326, 'FCT Employee'),
  ('ABUJA', 'POLICE DEPARTMENT', 'investigation-room', 326, 'Abuja'),
  ('ABUJA', 'POLICE DEPARTMENT', 'investigation-room', 327, 'Suspect'),
  ('ABUJA', 'POLICE DEPARTMENT', 'investigation-room', 327, 'Abuja'),
  ('ABUJA', 'POLICE DEPARTMENT', 'investigation-room', 328, 'Arrested'),
  ('ABUJA', 'POLICE DEPARTMENT', 'investigation-room', 328, 'Abuja'),
  ('ABUJA', 'POLICE DEPARTMENT', 'holding-cell', 329, 'Police Officer'),
  ('ABUJA', 'POLICE DEPARTMENT', 'holding-cell', 329, 'FCT Employee'),
  ('ABUJA', 'POLICE DEPARTMENT', 'holding-cell', 329, 'Abuja'),
  ('ABUJA', 'POLICE DEPARTMENT', 'holding-cell', 330, 'Jailed'),
  ('ABUJA', 'POLICE DEPARTMENT', 'holding-cell', 330, 'Abuja'),
  ('ABUJA', 'POLICE DEPARTMENT', 'holding-cell', 331, 'Arrested'),
  ('ABUJA', 'POLICE DEPARTMENT', 'holding-cell', 331, 'Abuja'),
  ('ABUJA', 'POLICE DEPARTMENT', 'patrol', 332, 'Police Officer'),
  ('ABUJA', 'POLICE DEPARTMENT', 'patrol', 332, 'FCT Employee'),
  ('ABUJA', 'POLICE DEPARTMENT', 'patrol', 332, 'Abuja'),
  ('ABUJA', 'POLICE DEPARTMENT', 'evidence-room', 333, 'Police Officer'),
  ('ABUJA', 'POLICE DEPARTMENT', 'evidence-room', 333, 'FCT Employee'),
  ('ABUJA', 'POLICE DEPARTMENT', 'evidence-room', 333, 'Abuja'),
  ('ABUJA', 'POLICE DEPARTMENT', 'dcp-office', 334, 'Police Officer'),
  ('ABUJA', 'POLICE DEPARTMENT', 'dcp-office', 334, 'FCT Employee'),
  ('ABUJA', 'POLICE DEPARTMENT', 'dcp-office', 334, 'Abuja'),
  ('ABUJA', 'POLICE DEPARTMENT', 'dcp-office', 335, 'Police Station Visitor'),
  ('ABUJA', 'POLICE DEPARTMENT', 'dcp-office', 335, 'Abuja'),
  ('ABUJA', 'POLICE DEPARTMENT', 'cp-office', 336, 'FCT Deputy Chief of Police'),
  ('ABUJA', 'POLICE DEPARTMENT', 'cp-office', 336, 'Abuja'),
  ('ABUJA', 'POLICE DEPARTMENT', 'cp-office', 337, 'Police Station Visitor'),
  ('ABUJA', 'POLICE DEPARTMENT', 'cp-office', 337, 'Abuja'),
  ('ABUJA', 'POLICE DEPARTMENT', 'police-radio', 338, 'FCT Chief of Police'),
  ('ABUJA', 'POLICE DEPARTMENT', 'police-radio', 338, 'Abuja'),
  ('ABUJA', 'POLICE DEPARTMENT', 'police-radio', 339, 'FCT Deputy Chief of Police'),
  ('ABUJA', 'POLICE DEPARTMENT', 'police-radio', 339, 'Abuja'),
  ('ABUJA', 'GENERAL HOSPITAL', 'hospital-reception', 340, 'Hospitalized'),
  ('ABUJA', 'GENERAL HOSPITAL', 'hospital-reception', 340, 'Abuja'),
  ('ABUJA', 'GENERAL HOSPITAL', 'hospital-reception', 341, 'Medic Staff'),
  ('ABUJA', 'GENERAL HOSPITAL', 'hospital-reception', 341, 'Abuja'),
  ('ABUJA', 'GENERAL HOSPITAL', 'hospital-reception', 342, 'Hospital Visitor'),
  ('ABUJA', 'GENERAL HOSPITAL', 'hospital-reception', 342, 'Abuja'),
  ('ABUJA', 'GENERAL HOSPITAL', 'hospital-reception', 343, 'Out Patient'),
  ('ABUJA', 'GENERAL HOSPITAL', 'hospital-reception', 343, 'Abuja'),
  ('ABUJA', 'GENERAL HOSPITAL', 'nursing-station', 344, 'Hospitalized'),
  ('ABUJA', 'GENERAL HOSPITAL', 'nursing-station', 344, 'Abuja'),
  ('ABUJA', 'GENERAL HOSPITAL', 'nursing-station', 345, 'Medic Staff'),
  ('ABUJA', 'GENERAL HOSPITAL', 'nursing-station', 345, 'FCT Employee'),
  ('ABUJA', 'GENERAL HOSPITAL', 'nursing-station', 345, 'Abuja'),
  ('ABUJA', 'GENERAL HOSPITAL', 'nursing-station', 346, 'Hospital Visitor'),
  ('ABUJA', 'GENERAL HOSPITAL', 'nursing-station', 346, 'Abuja'),
  ('ABUJA', 'GENERAL HOSPITAL', 'nursing-station', 347, 'Out Patient'),
  ('ABUJA', 'GENERAL HOSPITAL', 'nursing-station', 347, 'Abuja'),
  ('ABUJA', 'GENERAL HOSPITAL', 'emergency', 348, 'Hospitalized'),
  ('ABUJA', 'GENERAL HOSPITAL', 'emergency', 348, 'Abuja'),
  ('ABUJA', 'GENERAL HOSPITAL', 'emergency', 349, 'Medic Staff'),
  ('ABUJA', 'GENERAL HOSPITAL', 'emergency', 349, 'FCT Employee'),
  ('ABUJA', 'GENERAL HOSPITAL', 'emergency', 349, 'Abuja'),
  ('ABUJA', 'GENERAL HOSPITAL', 'pharmacy-and-laboratory', 350, 'Medic Staff'),
  ('ABUJA', 'GENERAL HOSPITAL', 'pharmacy-and-laboratory', 350, 'FCT Employee'),
  ('ABUJA', 'GENERAL HOSPITAL', 'pharmacy-and-laboratory', 350, 'Abuja'),
  ('ABUJA', 'GENERAL HOSPITAL', 'consultation', 351, 'Hospitalized'),
  ('ABUJA', 'GENERAL HOSPITAL', 'consultation', 351, 'Abuja'),
  ('ABUJA', 'GENERAL HOSPITAL', 'consultation', 352, 'Medic Staff'),
  ('ABUJA', 'GENERAL HOSPITAL', 'consultation', 352, 'FCT Employee'),
  ('ABUJA', 'GENERAL HOSPITAL', 'consultation', 352, 'Abuja'),
  ('ABUJA', 'GENERAL HOSPITAL', 'dentistry', 353, 'Dental Patient'),
  ('ABUJA', 'GENERAL HOSPITAL', 'dentistry', 353, 'Abuja'),
  ('ABUJA', 'GENERAL HOSPITAL', 'dentistry', 354, 'Dentist'),
  ('ABUJA', 'GENERAL HOSPITAL', 'dentistry', 354, 'FCT Employee'),
  ('ABUJA', 'GENERAL HOSPITAL', 'dentistry', 354, 'Abuja'),
  ('ABUJA', 'GENERAL HOSPITAL', 'female-wards', 355, 'Hospitalized (Female)'),
  ('ABUJA', 'GENERAL HOSPITAL', 'female-wards', 355, 'Abuja'),
  ('ABUJA', 'GENERAL HOSPITAL', 'female-wards', 356, 'Medic Staff'),
  ('ABUJA', 'GENERAL HOSPITAL', 'female-wards', 356, 'FCT Employee'),
  ('ABUJA', 'GENERAL HOSPITAL', 'female-wards', 356, 'Abuja'),
  ('ABUJA', 'GENERAL HOSPITAL', 'male-wards', 357, 'Hospitalized (Male)'),
  ('ABUJA', 'GENERAL HOSPITAL', 'male-wards', 357, 'Abuja'),
  ('ABUJA', 'GENERAL HOSPITAL', 'male-wards', 358, 'Medic Staff'),
  ('ABUJA', 'GENERAL HOSPITAL', 'male-wards', 358, 'FCT Employee'),
  ('ABUJA', 'GENERAL HOSPITAL', 'male-wards', 358, 'Abuja'),
  ('ABUJA', 'GENERAL HOSPITAL', 'surgical-theatre', 359, 'Surgery Patient'),
  ('ABUJA', 'GENERAL HOSPITAL', 'surgical-theatre', 359, 'Abuja'),
  ('ABUJA', 'GENERAL HOSPITAL', 'surgical-theatre', 360, 'Medic Staff'),
  ('ABUJA', 'GENERAL HOSPITAL', 'surgical-theatre', 360, 'FCT Employee'),
  ('ABUJA', 'GENERAL HOSPITAL', 'surgical-theatre', 360, 'Abuja'),
  ('ABUJA', 'GENERAL HOSPITAL', 'dmd-office', 361, 'Medic Staff'),
  ('ABUJA', 'GENERAL HOSPITAL', 'dmd-office', 361, 'Abuja'),
  ('ABUJA', 'GENERAL HOSPITAL', 'dmd-office', 362, 'Deputy Medical Director'),
  ('ABUJA', 'GENERAL HOSPITAL', 'dmd-office', 362, 'FCT Employee'),
  ('ABUJA', 'GENERAL HOSPITAL', 'dmd-office', 362, 'Abuja'),
  ('ABUJA', 'GENERAL HOSPITAL', 'dmd-office', 363, 'Director Visitor'),
  ('ABUJA', 'GENERAL HOSPITAL', 'dmd-office', 363, 'Abuja'),
  ('ABUJA', 'GENERAL HOSPITAL', 'cmd-office', 364, 'Chief Medical Director'),
  ('ABUJA', 'GENERAL HOSPITAL', 'cmd-office', 364, 'Abuja'),
  ('ABUJA', 'GENERAL HOSPITAL', 'cmd-office', 365, 'Deputy Medical Director'),
  ('ABUJA', 'GENERAL HOSPITAL', 'cmd-office', 365, 'FCT Employee'),
  ('ABUJA', 'GENERAL HOSPITAL', 'cmd-office', 365, 'Abuja'),
  ('ABUJA', 'PROPERTY AND DEVELOPMENT DEPARTMENT', 'agents-office', 366, 'Housing Officer'),
  ('ABUJA', 'PROPERTY AND DEVELOPMENT DEPARTMENT', 'agents-office', 366, 'FCT Employee'),
  ('ABUJA', 'PROPERTY AND DEVELOPMENT DEPARTMENT', 'agents-office', 366, 'Abuja'),
  ('ABUJA', 'ELECTRICITY DISTRIBUTION COMPANY', 'fault-report', 367, 'Technician'),
  ('ABUJA', 'ELECTRICITY DISTRIBUTION COMPANY', 'fault-report', 367, 'FCT Employee'),
  ('ABUJA', 'ELECTRICITY DISTRIBUTION COMPANY', 'fault-report', 367, 'Abuja'),
  ('ABUJA', 'ELECTRICITY DISTRIBUTION COMPANY', 'fault-report', 368, 'FCT Commissioner of Power and Water'),
  ('ABUJA', 'ELECTRICITY DISTRIBUTION COMPANY', 'fault-report', 368, 'Abuja'),
  ('ABUJA', 'ELECTRICITY DISTRIBUTION COMPANY', 'technician-office', 369, 'Technician'),
  ('ABUJA', 'ELECTRICITY DISTRIBUTION COMPANY', 'technician-office', 369, 'FCT Employee'),
  ('ABUJA', 'ELECTRICITY DISTRIBUTION COMPANY', 'technician-office', 369, 'Abuja'),
  ('ABUJA', 'ELECTRICITY DISTRIBUTION COMPANY', 'technician-office', 370, 'FCT Commissioner of Power and Water'),
  ('ABUJA', 'ELECTRICITY DISTRIBUTION COMPANY', 'technician-office', 370, 'Abuja'),
  ('ABUJA', 'ELECTRICITY DISTRIBUTION COMPANY', 'operations', 371, 'FCT Commissioner of Power and Water'),
  ('ABUJA', 'ELECTRICITY DISTRIBUTION COMPANY', 'operations', 371, 'Abuja'),
  ('ABUJA', 'MID CLASS HOUSING', 'gwarinpa', 372, 'Gwarinpa Resident'),
  ('ABUJA', 'MID CLASS HOUSING', 'gwarinpa', 372, 'Abuja'),
  ('ABUJA', 'MID CLASS HOUSING', 'kubwa', 373, 'Kubwa Resident'),
  ('ABUJA', 'MID CLASS HOUSING', 'kubwa', 373, 'Abuja'),
  ('ABUJA', 'HIGH CLASS HOUSING', 'maitama', 374, 'Maitama Resident'),
  ('ABUJA', 'HIGH CLASS HOUSING', 'maitama', 374, 'Abuja'),
  ('ABUJA', 'HIGH CLASS HOUSING', 'asokoro', 375, 'Asokoro Resident'),
  ('ABUJA', 'HIGH CLASS HOUSING', 'asokoro', 375, 'Abuja'),
  ('ABUJA', 'CAREER HIGH SCHOOL', 'school-building', 376, 'Student'),
  ('ABUJA', 'CAREER HIGH SCHOOL', 'school-building', 376, 'Abuja'),
  ('ABUJA', 'CAREER HIGH SCHOOL', 'school-hostel', 377, 'Hostel Resident'),
  ('ABUJA', 'CAREER HIGH SCHOOL', 'school-hostel', 377, 'Abuja'),
  ('ABUJA', 'UNIVERSITY OF BANKING AND MEDICINE', 'campus-residence', 378, 'Campus Resident'),
  ('ABUJA', 'UNIVERSITY OF BANKING AND MEDICINE', 'campus-residence', 378, 'Abuja'),
  ('ABUJA', 'BUSINESS & COMMERCE', 'depot', 379, 'Business Owner'),
  ('ABUJA', 'BUSINESS & COMMERCE', 'depot', 379, 'Abuja'),
  ('ABUJA', 'BUSINESS & COMMERCE', 'depot', 380, 'Supplier'),
  ('ABUJA', 'BUSINESS & COMMERCE', 'depot', 380, 'Abuja'),
  ('ABUJA', 'BUSINESS & COMMERCE', 'industrial-goods', 381, 'FCT Commissioner of Commerce'),
  ('ABUJA', 'BUSINESS & COMMERCE', 'industrial-goods', 381, 'Abuja'),
  ('ABUJA', 'BUSINESS & COMMERCE', 'industrial-goods', 382, 'Supplier'),
  ('ABUJA', 'BUSINESS & COMMERCE', 'industrial-goods', 382, 'Abuja'),
  ('ABUJA', 'BUSINESS & COMMERCE', 'food-beverages-industry', 383, 'FCT Commissioner of Commerce'),
  ('ABUJA', 'BUSINESS & COMMERCE', 'food-beverages-industry', 383, 'Abuja'),
  ('ABUJA', 'BUSINESS & COMMERCE', 'food-beverages-industry', 384, 'Supplier'),
  ('ABUJA', 'BUSINESS & COMMERCE', 'food-beverages-industry', 384, 'Abuja'),
  ('ABUJA', 'BUSINESS & COMMERCE', 'refinery', 385, 'FCT Commissioner of Petroleum'),
  ('ABUJA', 'BUSINESS & COMMERCE', 'refinery', 385, 'Abuja'),
  ('ABUJA', 'BUSINESS & COMMERCE', 'refinery', 386, 'Gas Station Owner'),
  ('ABUJA', 'BUSINESS & COMMERCE', 'refinery', 386, 'Abuja'),
  ('ABUJA', 'BUSINESS & COMMERCE', 'refinery', 387, 'Chief of Staff'),
  ('ABUJA', 'BUSINESS & COMMERCE', 'refinery', 387, 'Abuja'),
  ('ABUJA', 'BUSINESS & COMMERCE', 'mining-ground', 388, 'Minister of Trade and Commerce'),
  ('ABUJA', 'BUSINESS & COMMERCE', 'mining-ground', 388, 'Abuja'),
  ('ABUJA', 'BUSINESS & COMMERCE', 'mining-ground', 389, 'FCT Commissioner of Commerce'),
  ('ABUJA', 'BUSINESS & COMMERCE', 'mining-ground', 389, 'Abuja'),
  ('ABUJA', 'FARMS', 'farmland', 390, 'Farmer'),
  ('ABUJA', 'FARMS', 'farmland', 390, 'Abuja'),
  ('ABUJA', 'FARMS', 'farmland', 391, 'Trader'),
  ('ABUJA', 'FARMS', 'farmland', 391, 'Abuja'),
  ('ABUJA', 'FARMS', 'farmland', 392, 'FCT Commissioner of Agriculture'),
  ('ABUJA', 'FARMS', 'farmland', 392, 'Abuja'),
  ('ABUJA', 'FARMS', 'ranch', 393, 'Rancher'),
  ('ABUJA', 'FARMS', 'ranch', 393, 'Abuja'),
  ('ABUJA', 'FARMS', 'ranch', 394, 'Butcher'),
  ('ABUJA', 'FARMS', 'ranch', 394, 'Abuja'),
  ('ABUJA', 'FARMS', 'ranch', 395, 'FCT Commissioner of Agriculture'),
  ('ABUJA', 'FARMS', 'ranch', 395, 'Abuja'),
  ('ABUJA', 'CENTRAL BANK OF NIGERIA', 'national-treasury', 396, 'CBN Governor'),
  ('ABUJA', 'CENTRAL BANK OF NIGERIA', 'national-treasury', 396, 'Abuja'),
  ('ABUJA', 'CENTRAL BANK OF NIGERIA', 'national-treasury', 397, 'Minister of Finance'),
  ('ABUJA', 'CENTRAL BANK OF NIGERIA', 'national-treasury', 397, 'Abuja'),
  ('DELTA', 'BORDER & ENTRY', 'airport', 398, 'Delta'),
  ('DELTA', 'BORDER & ENTRY', 'travel-agency', 399, 'Delta'),
  ('DELTA', 'BORDER & ENTRY', 'road-checkpoint', 403, 'Delta'),
  ('DELTA', 'HOTEL & SUITES', 'hotel-reception', 404, 'Delta'),
  ('DELTA', 'BROADCASTING STATION', 'broadcasting-station', 405, 'Delta'),
  ('DELTA', 'JUDICIARY', 'clerk-office', 406, 'Delta'),
  ('DELTA', 'JUDICIARY', 'court-room', 407, 'Delta'),
  ('DELTA', 'BANK PLC', 'banking-hall', 408, 'Delta'),
  ('DELTA', 'BANK PLC', 'atm', 409, 'Delta'),
  ('DELTA', 'POLICE DEPARTMENT', 'police-station', 410, 'Delta'),
  ('DELTA', 'GENERAL HOSPITAL', 'hospital-lobby', 411, 'Delta'),
  ('DELTA', 'PROPERTY AND DEVELOPMENT DEPARTMENT', 'rental-desk', 412, 'Delta'),
  ('DELTA', 'ELECTRICITY DISTRIBUTION COMPANY', 'help-desk', 413, 'Delta'),
  ('DELTA', 'LOW COST HOUSING', 'okpanam', 414, 'Delta'),
  ('DELTA', 'LOW COST HOUSING', 'ozoro', 415, 'Delta'),
  ('DELTA', 'CAREER HIGH SCHOOL', 'admin-block', 416, 'Delta'),
  ('DELTA', 'STATE UNIVERSITY', 'administrative-block', 417, 'Delta'),
  ('DELTA', 'BUSINESS & COMMERCE', 'market', 418, 'Delta'),
  ('DELTA', 'BUSINESS & COMMERCE', 'restaurant', 419, 'Delta'),
  ('DELTA', 'BUSINESS & COMMERCE', 'abattoir', 420, 'Delta'),
  ('DELTA', 'BUSINESS & COMMERCE', 'nnpc-fuel-station', 421, 'Delta'),
  ('DELTA', 'BUSINESS & COMMERCE', 'auto-repair', 422, 'Delta'),
  ('DELTA', 'BUSINESS & COMMERCE', 'dealership', 423, 'Delta'),
  ('DELTA', 'BUSINESS & COMMERCE', 'driving-school', 424, 'Delta'),
  ('DELTA', 'BUSINESS & COMMERCE', 'club-house', 425, 'Delta'),
  ('DELTA', 'BUSINESS & COMMERCE', 'bus-park', 426, 'Delta'),
  ('DELTA', 'BUSINESS & COMMERCE', 'taxi-company', 427, 'Delta'),
  ('LAGOS', 'BORDER & ENTRY', 'airport', 428, 'Lagos'),
  ('LAGOS', 'BORDER & ENTRY', 'travel-agency', 429, 'Lagos'),
  ('LAGOS', 'BORDER & ENTRY', 'road-checkpoint', 433, 'Lagos'),
  ('LAGOS', 'HOTEL & SUITES', 'hotel-reception', 434, 'Lagos'),
  ('LAGOS', 'BROADCASTING STATION', 'broadcasting-station', 435, 'Lagos'),
  ('LAGOS', 'JUDICIARY', 'clerk-office', 436, 'Lagos'),
  ('LAGOS', 'JUDICIARY', 'court-room', 437, 'Lagos'),
  ('LAGOS', 'BANK PLC', 'banking-hall', 438, 'Lagos'),
  ('LAGOS', 'BANK PLC', 'atm', 439, 'Lagos'),
  ('LAGOS', 'POLICE DEPARTMENT', 'police-station', 440, 'Lagos'),
  ('LAGOS', 'GENERAL HOSPITAL', 'hospital-lobby', 441, 'Lagos'),
  ('LAGOS', 'PROPERTY AND DEVELOPMENT DEPARTMENT', 'rental-desk', 442, 'Lagos'),
  ('LAGOS', 'ELECTRICITY DISTRIBUTION COMPANY', 'help-desk', 443, 'Lagos'),
  ('LAGOS', 'ELECTRICITY DISTRIBUTION COMPANY', 'billing', 444, 'Lagos'),
  ('LAGOS', 'GHETTO', 'ajegunle', 445, 'Lagos'),
  ('LAGOS', 'GHETTO', 'makoko', 446, 'Lagos'),
  ('LAGOS', 'CAREER HIGH SCHOOL', 'admin-block', 447, 'Lagos'),
  ('LAGOS', 'DEFENCE ACADEMY', 'administrative-block', 448, 'Lagos'),
  ('LAGOS', 'BUSINESS & COMMERCE', 'market', 449, 'Lagos'),
  ('LAGOS', 'BUSINESS & COMMERCE', 'restaurant', 450, 'Lagos'),
  ('LAGOS', 'BUSINESS & COMMERCE', 'abattoir', 451, 'Lagos'),
  ('LAGOS', 'BUSINESS & COMMERCE', 'nnpc-fuel-station', 452, 'Lagos'),
  ('LAGOS', 'BUSINESS & COMMERCE', 'auto-repair', 453, 'Lagos'),
  ('LAGOS', 'BUSINESS & COMMERCE', 'dealership', 454, 'Lagos'),
  ('LAGOS', 'BUSINESS & COMMERCE', 'driving-school', 455, 'Lagos'),
  ('LAGOS', 'BUSINESS & COMMERCE', 'club-house', 456, 'Lagos'),
  ('LAGOS', 'BUSINESS & COMMERCE', 'bus-park', 457, 'Lagos'),
  ('LAGOS', 'BUSINESS & COMMERCE', 'taxi-company', 458, 'Lagos'),
  ('ABUJA', 'BORDER & ENTRY', 'airport', 459, 'Abuja'),
  ('ABUJA', 'BORDER & ENTRY', 'travel-agency', 460, 'Abuja'),
  ('ABUJA', 'BORDER & ENTRY', 'road-checkpoint', 467, 'Abuja'),
  ('ABUJA', 'HOTEL & SUITES', 'hotel-reception', 468, 'Abuja'),
  ('ABUJA', 'TELEVISION AUTHORITY', 'broadcasting-station', 470, 'Abuja'),
  ('ABUJA', 'JUDICIARY', 'clerk-office', 471, 'Abuja'),
  ('ABUJA', 'JUDICIARY', 'court-room', 474, 'Abuja'),
  ('ABUJA', 'JUDICIARY', 'high-court', 475, 'Abuja'),
  ('ABUJA', 'BANK PLC', 'banking-hall', 483, 'Abuja'),
  ('ABUJA', 'BANK PLC', 'atm', 484, 'Abuja'),
  ('ABUJA', 'POLICE DEPARTMENT', 'police-station', 490, 'Abuja'),
  ('ABUJA', 'GENERAL HOSPITAL', 'hospital-lobby', 494, 'Abuja'),
  ('ABUJA', 'PROPERTY AND DEVELOPMENT DEPARTMENT', 'rental-desk', 495, 'Abuja'),
  ('ABUJA', 'ELECTRICITY DISTRIBUTION COMPANY', 'help-desk', 496, 'Abuja'),
  ('ABUJA', 'ELECTRICITY DISTRIBUTION COMPANY', 'billing', 497, 'Abuja'),
  ('ABUJA', 'LOW COST HOUSING', 'karu', 498, 'Abuja'),
  ('ABUJA', 'CAREER HIGH SCHOOL', 'admin-block', 499, 'Abuja'),
  ('ABUJA', 'UNIVERSITY OF BANKING AND MEDICINE', 'administrative-block', 500, 'Abuja'),
  ('ABUJA', 'BUSINESS & COMMERCE', 'market', 503, 'Abuja'),
  ('ABUJA', 'BUSINESS & COMMERCE', 'restaurant', 504, 'Abuja'),
  ('ABUJA', 'BUSINESS & COMMERCE', 'abattoir', 505, 'Abuja'),
  ('ABUJA', 'BUSINESS & COMMERCE', 'nnpc-fuel-station', 506, 'Abuja'),
  ('ABUJA', 'BUSINESS & COMMERCE', 'auto-repair', 507, 'Abuja'),
  ('ABUJA', 'BUSINESS & COMMERCE', 'dealership', 508, 'Abuja'),
  ('ABUJA', 'BUSINESS & COMMERCE', 'driving-school', 509, 'Abuja'),
  ('ABUJA', 'BUSINESS & COMMERCE', 'club-house', 510, 'Abuja'),
  ('ABUJA', 'BUSINESS & COMMERCE', 'bus-park', 511, 'Abuja'),
  ('ABUJA', 'BUSINESS & COMMERCE', 'taxi-company', 512, 'Abuja'),
  ('ABUJA', 'CENTRAL BANK OF NIGERIA', 'cbn-lobby', 513, 'Abuja'),
  ('ABUJA', 'CENTRAL BANK OF NIGERIA', 'vault', 514, 'CBN Governor'),
  ('ABUJA', 'CENTRAL BANK OF NIGERIA', 'vault', 514, 'Abuja'),
  ('ABUJA', 'CENTRAL BANK OF NIGERIA', 'vault', 515, 'CBN Deputy'),
  ('ABUJA', 'CENTRAL BANK OF NIGERIA', 'vault', 515, 'Abuja'),
  ('ABUJA', 'CENTRAL BANK OF NIGERIA', 'cbn-deputy', 516, 'CBN Governor'),
  ('ABUJA', 'CENTRAL BANK OF NIGERIA', 'cbn-deputy', 516, 'Abuja'),
  ('ABUJA', 'CENTRAL BANK OF NIGERIA', 'cbn-deputy', 517, 'CBN Deputy'),
  ('ABUJA', 'CENTRAL BANK OF NIGERIA', 'cbn-deputy', 517, 'Abuja'),
  ('ABUJA', 'CENTRAL BANK OF NIGERIA', 'cbn-log', 518, 'CBN Governor'),
  ('ABUJA', 'CENTRAL BANK OF NIGERIA', 'cbn-log', 518, 'Abuja'),
  ('ABUJA', 'CENTRAL BANK OF NIGERIA', 'cbn-log', 519, 'CBN Deputy'),
  ('ABUJA', 'CENTRAL BANK OF NIGERIA', 'cbn-log', 519, 'Abuja'),
  ('ABUJA', 'CENTRAL BANK OF NIGERIA', 'cbn-governor', 520, 'CBN Governor'),
  ('ABUJA', 'CENTRAL BANK OF NIGERIA', 'cbn-governor', 520, 'Abuja'),
  ('DELTA', 'BORDER & ENTRY', 'arrival-terminal', 521, 'Delta Arrival'),
  ('DELTA', 'BORDER & ENTRY', 'arrival-terminal', 522, 'Delta'),
  ('DELTA', 'BORDER & ENTRY', 'refugee-camp', 523, 'Delta Arrival'),
  ('DELTA', 'BORDER & ENTRY', 'immigration-office', 524, 'Delta Arrival'),
  ('LAGOS', 'BORDER & ENTRY', 'arrival-terminal', 525, 'Lagos Arrival'),
  ('LAGOS', 'BORDER & ENTRY', 'arrival-terminal', 526, 'Lagos'),
  ('LAGOS', 'BORDER & ENTRY', 'refugee-camp', 527, 'Lagos Arrival'),
  ('LAGOS', 'BORDER & ENTRY', 'immigration-office', 528, 'Lagos Arrival'),
  ('ABUJA', 'BORDER & ENTRY', 'arrival-terminal', 529, 'Abuja Arrival'),
  ('ABUJA', 'BORDER & ENTRY', 'arrival-terminal', 530, 'Abuja'),
  ('ABUJA', 'BORDER & ENTRY', 'refugee-camp', 531, 'Abuja Arrival'),
  ('ABUJA', 'BORDER & ENTRY', 'immigration-office', 532, 'Abuja Arrival'),
  ('ABUJA', 'BORDER & ENTRY', 'front-desk', 533, 'Immigration Officer'),
  ('ABUJA', 'BORDER & ENTRY', 'front-desk', 533, 'Abuja'),
  ('ABUJA', 'BORDER & ENTRY', 'parcel-pickup', 534, 'Immigration Officer'),
  ('ABUJA', 'BORDER & ENTRY', 'parcel-pickup', 534, 'Abuja'),
  ('ABUJA', 'BORDER & ENTRY', 'parcel-pickup', 535, 'Dispatch Rider'),
  ('ABUJA', 'BORDER & ENTRY', 'parcel-pickup', 535, 'Abuja'),
  ('ABUJA', 'BORDER & ENTRY', 'chief-marshal-office', 536, 'Chief Immigration Marshal'),
  ('ABUJA', 'BORDER & ENTRY', 'chief-marshal-office', 536, 'Abuja'),
  ('ABUJA', 'HOTEL & SUITES', 'hotel-lobby', 537, 'Hotel Guest'),
  ('ABUJA', 'HOTEL & SUITES', 'hotel-lobby', 537, 'Abuja'),
  ('ABUJA', 'JUDICIARY', 'lawyer-chambers', 538, 'Lawyers'),
  ('ABUJA', 'JUDICIARY', 'lawyer-chambers', 538, 'Abuja'),
  ('ABUJA', 'JUDICIARY', 'judge-chambers', 539, 'Supreme Judge'),
  ('ABUJA', 'JUDICIARY', 'judge-chambers', 539, 'Abuja'),
  ('ABUJA', 'JUDICIARY', 'judge-chambers', 540, 'High Court Judge'),
  ('ABUJA', 'JUDICIARY', 'judge-chambers', 540, 'Abuja'),
  ('ABUJA', 'FEDERAL GOVERNMENT', 'fct-minister', 541, 'FCT Minister'),
  ('ABUJA', 'FEDERAL GOVERNMENT', 'fct-minister', 541, 'Abuja'),
  ('ABUJA', 'FEDERAL GOVERNMENT', 'fct-minister', 542, 'Appointment with Minister'),
  ('ABUJA', 'FEDERAL GOVERNMENT', 'fct-minister', 542, 'Abuja'),
  ('ABUJA', 'ASO ROCK', 'president-office', 543, 'President'),
  ('ABUJA', 'ASO ROCK', 'president-office', 543, 'Abuja'),
  ('ABUJA', 'ASO ROCK', 'president-office', 544, 'Appointment with President'),
  ('ABUJA', 'ASO ROCK', 'president-office', 544, 'Abuja'),
  ('ABUJA', 'ASO ROCK', 'vice-president-office', 545, 'President'),
  ('ABUJA', 'ASO ROCK', 'vice-president-office', 545, 'Abuja'),
  ('ABUJA', 'ASO ROCK', 'vice-president-office', 546, 'Vice President'),
  ('ABUJA', 'ASO ROCK', 'vice-president-office', 546, 'Abuja'),
  ('ABUJA', 'ASO ROCK', 'vice-president-office', 547, 'Appointment with Vice'),
  ('ABUJA', 'ASO ROCK', 'vice-president-office', 547, 'Abuja'),
  ('ABUJA', 'ASO ROCK', 'presidential-villa', 548, 'Presidential Resident'),
  ('ABUJA', 'ASO ROCK', 'presidential-villa', 548, 'Abuja'),
  ('ABUJA', 'ASO ROCK', 'presidential-villa', 549, 'Presidential Visitor'),
  ('ABUJA', 'ASO ROCK', 'presidential-villa', 549, 'Abuja'),
  ('ABUJA', 'ASO ROCK', 'presidential-guesthouse', 550, 'Presidential Resident'),
  ('ABUJA', 'ASO ROCK', 'presidential-guesthouse', 550, 'Abuja'),
  ('ABUJA', 'ASO ROCK', 'presidential-guesthouse', 551, 'Presidential Guest'),
  ('ABUJA', 'ASO ROCK', 'presidential-guesthouse', 551, 'Abuja'),
  ('ABUJA', 'ASO ROCK', 'villa-staff-residence', 552, 'Villa Staff'),
  ('ABUJA', 'ASO ROCK', 'villa-staff-residence', 552, 'Abuja'),
  ('ABUJA', 'ASO ROCK', 'villa-staff-residence', 553, 'Presidential Resident'),
  ('ABUJA', 'ASO ROCK', 'villa-staff-residence', 553, 'Abuja'),
  ('ABUJA', 'ASO ROCK', 'presidential-banquet-hall', 554, 'Presidential Resident'),
  ('ABUJA', 'ASO ROCK', 'presidential-banquet-hall', 554, 'Abuja'),
  ('ABUJA', 'ASO ROCK', 'presidential-banquet-hall', 555, 'Presidential Visitor'),
  ('ABUJA', 'ASO ROCK', 'presidential-banquet-hall', 555, 'Abuja'),
  ('ABUJA', 'POLICE DEPARTMENT', 'armoury', 556, 'FCT Chief of Police'),
  ('ABUJA', 'POLICE DEPARTMENT', 'armoury', 556, 'Abuja'),
  ('ABUJA', 'POLICE DEPARTMENT', 'armoury', 557, 'FCT Deputy Chief of Police'),
  ('ABUJA', 'POLICE DEPARTMENT', 'armoury', 557, 'Abuja'),
  ('ABUJA', 'POLICE DEPARTMENT', 'igp-office', 558, 'Inspector General of Police'),
  ('ABUJA', 'POLICE DEPARTMENT', 'igp-office', 558, 'Abuja'),
  ('ABUJA', 'POLICE DEPARTMENT', 'igp-office', 559, 'Appointment with IGP'),
  ('ABUJA', 'POLICE DEPARTMENT', 'igp-office', 559, 'Abuja'),
  ('ABUJA', 'POLICE DEPARTMENT', 'maximum-prison', 560, 'Police Officer'),
  ('ABUJA', 'POLICE DEPARTMENT', 'maximum-prison', 560, 'Abuja'),
  ('ABUJA', 'POLICE DEPARTMENT', 'maximum-prison', 561, 'Imprisoned'),
  ('ABUJA', 'POLICE DEPARTMENT', 'maximum-prison', 561, 'Abuja'),
  ('ABUJA', 'UNIVERSITY OF BANKING AND MEDICINE', 'school-of-medicine-and-surgery', 562, 'Medicine Student'),
  ('ABUJA', 'UNIVERSITY OF BANKING AND MEDICINE', 'school-of-medicine-and-surgery', 562, 'Abuja'),
  ('ABUJA', 'UNIVERSITY OF BANKING AND MEDICINE', 'school-of-banking', 563, 'Banking Student'),
  ('ABUJA', 'UNIVERSITY OF BANKING AND MEDICINE', 'school-of-banking', 563, 'Abuja'),
  ('DELTA', 'STATE GOVERNMENT', 'city-hall', 564, 'Delta Resident'),
  ('DELTA', 'STATE GOVERNMENT', 'city-hall', 564, 'Delta'),
  ('LAGOS', 'STATE GOVERNMENT', 'city-hall', 565, 'Lagos')
) AS v(state, category, channel_name, group_id, role_name)
JOIN locations l ON l.state = v.state AND l.category = v.category AND l.channel_name = v.channel_name
JOIN roles r ON r.name = v.role_name
ON CONFLICT (location_id, group_id, role_id) DO NOTHING;
