-- Links each location to the role(s) that may access it. Run after
-- locations_seed.sql and roles_seed.sql.

INSERT INTO location_roles (location_id, role_id)
SELECT l.id, r.id
FROM (VALUES
  ('DELTA', 'BORDER & ENTRY', 'front-desk', 'Immigration Officer'),
  ('DELTA', 'BORDER & ENTRY', 'parcel-pickup', 'Dispatch Rider'),
  ('DELTA', 'BORDER & ENTRY', 'parcel-pickup', 'Immigration Officer'),
  ('DELTA', 'BORDER & ENTRY', 'chief-marshal-office', 'Chief Immigration Marshal'),
  ('DELTA', 'HOTEL & SUITES', 'hotel-lobby', 'Hotel Guest'),
  ('DELTA', 'BROADCASTING STATION', 'production-room', 'Media Staff (Delta Employee)'),
  ('DELTA', 'BROADCASTING STATION', 'production-room', 'Journalist (Delta Employee)'),
  ('DELTA', 'BROADCASTING STATION', 'production-room', 'Reporter (Delta Employee)'),
  ('DELTA', 'BROADCASTING STATION', 'media-manager', 'Media Manager (Delta Employee)'),
  ('DELTA', 'JUDICIARY', 'lawyer-chambers', 'Lawyers (Delta Employee)'),
  ('DELTA', 'JUDICIARY', 'judge-chambers', 'Supreme Judge (Delta Employee)'),
  ('DELTA', 'STATE GOVERNMENT', 'governor-office', 'Delta Governor'),
  ('DELTA', 'STATE GOVERNMENT', 'governor-office', 'Appointment with Governor'),
  ('DELTA', 'STATE GOVERNMENT', 'deputy-governor-office', 'Governor'),
  ('DELTA', 'STATE GOVERNMENT', 'deputy-governor-office', 'Deputy Governor'),
  ('DELTA', 'STATE GOVERNMENT', 'deputy-governor-office', 'Appointment with Deputy'),
  ('DELTA', 'STATE GOVERNMENT', 'chief-of-staff', 'Delta Commissioner'),
  ('DELTA', 'STATE GOVERNMENT', 'chief-of-staff', 'Lagos Commissioner'),
  ('DELTA', 'STATE GOVERNMENT', 'chief-of-staff', 'FCT Commissioner'),
  ('DELTA', 'STATE GOVERNMENT', 'chief-of-staff', 'President'),
  ('DELTA', 'STATE GOVERNMENT', 'chief-of-staff', 'Vice President'),
  ('DELTA', 'STATE GOVERNMENT', 'chief-of-staff', 'FCT Minister'),
  ('DELTA', 'STATE GOVERNMENT', 'state-secretariat', 'Delta Commissioner'),
  ('DELTA', 'STATE GOVERNMENT', 'state-secretariat', 'Lagos Commissioner'),
  ('DELTA', 'STATE GOVERNMENT', 'state-secretariat', 'FCT Commissioner'),
  ('DELTA', 'STATE GOVERNMENT', 'council', 'Delta Commissioner'),
  ('DELTA', 'STATE GOVERNMENT', 'ministry-of-finance', 'Delta Commissioner'),
  ('DELTA', 'STATE GOVERNMENT', 'ministry-of-finance', 'Bank Manager (Delta Employee)'),
  ('DELTA', 'STATE GOVERNMENT', 'ministry-of-finance', 'Minister of Finance'),
  ('DELTA', 'STATE GOVERNMENT', 'ministry-of-finance', 'Delta Commissioner of Finance'),
  ('DELTA', 'STATE GOVERNMENT', 'ministry-of-justice', 'Delta Commissioner'),
  ('DELTA', 'STATE GOVERNMENT', 'ministry-of-justice', 'High Court Judge'),
  ('DELTA', 'STATE GOVERNMENT', 'ministry-of-justice', 'Supreme Judge'),
  ('DELTA', 'STATE GOVERNMENT', 'ministry-of-agriculture', 'Delta Commissioner'),
  ('DELTA', 'STATE GOVERNMENT', 'ministry-of-agriculture', 'Minister of Agriculture'),
  ('DELTA', 'STATE GOVERNMENT', 'ministry-of-housing', 'Delta Commissioner'),
  ('DELTA', 'STATE GOVERNMENT', 'ministry-of-housing', 'Minister of Housing'),
  ('DELTA', 'STATE GOVERNMENT', 'ministry-of-education', 'Delta Commissioner'),
  ('DELTA', 'STATE GOVERNMENT', 'ministry-of-education', 'Minister of Education'),
  ('DELTA', 'STATE GOVERNMENT', 'ministry-of-commerce', 'Delta Commissioner'),
  ('DELTA', 'STATE GOVERNMENT', 'ministry-of-commerce', 'Minister of Trade and Commerce'),
  ('DELTA', 'STATE GOVERNMENT', 'ministry-of-commerce', 'Delta Commissioner of Commerce'),
  ('DELTA', 'STATE GOVERNMENT', 'ministry-of-power-and-water', 'Delta Commissioner'),
  ('DELTA', 'STATE GOVERNMENT', 'ministry-of-power-and-water', 'Minister of Power and Water'),
  ('DELTA', 'STATE GOVERNMENT', 'ministry-of-petroleum', 'Delta Commissioner'),
  ('DELTA', 'STATE GOVERNMENT', 'ministry-of-petroleum', 'Minister of Petroleum'),
  ('DELTA', 'STATE GOVERNMENT', 'city-hall', 'Delta Indigine'),
  ('DELTA', 'STATE GOVERNMENT', 'city-hall', 'Delta Resident'),
  ('DELTA', 'GOVERNOR''S HOUSE', 'governor-penthouse', 'Delta Governor'),
  ('DELTA', 'GOVERNOR''S HOUSE', 'governor-penthouse', 'Deputy Governor'),
  ('DELTA', 'GOVERNOR''S HOUSE', 'governor-penthouse', 'Governor Visitor'),
  ('DELTA', 'GOVERNOR''S HOUSE', 'deputy-governor-residence', 'Delta Governor'),
  ('DELTA', 'GOVERNOR''S HOUSE', 'deputy-governor-residence', 'Deputy Governor'),
  ('DELTA', 'GOVERNOR''S HOUSE', 'deputy-governor-residence', 'Governor Visitor'),
  ('DELTA', 'GOVERNOR''S HOUSE', 'governor-guesthouse', 'Delta Governor'),
  ('DELTA', 'GOVERNOR''S HOUSE', 'governor-guesthouse', 'Deputy Governor'),
  ('DELTA', 'GOVERNOR''S HOUSE', 'governor-guesthouse', 'Governor Guest'),
  ('DELTA', 'BANK PLC', 'customer-care', 'Bank Staff (Delta Employee)'),
  ('DELTA', 'BANK PLC', 'accountant', 'Bank Staff (Delta Employee)'),
  ('DELTA', 'BANK PLC', 'deposit', 'Bank Staff (Delta Employee)'),
  ('DELTA', 'BANK PLC', 'bank-manager', 'Bank Staff (Delta Employee)'),
  ('DELTA', 'BANK PLC', 'transaction-log', 'Bank Manager (Delta Employee)'),
  ('DELTA', 'BANK PLC', 'treasury', 'Bank Manager (Delta Employee)'),
  ('DELTA', 'POLICE DEPARTMENT', 'officers-office', 'Police Officer (Delta Employee)'),
  ('DELTA', 'POLICE DEPARTMENT', 'investigation-room', 'Police Officer (Delta Employee)'),
  ('DELTA', 'POLICE DEPARTMENT', 'investigation-room', 'Suspect'),
  ('DELTA', 'POLICE DEPARTMENT', 'investigation-room', 'Arrested'),
  ('DELTA', 'POLICE DEPARTMENT', 'holding-cell', 'Police Officer (Delta Employee)'),
  ('DELTA', 'POLICE DEPARTMENT', 'holding-cell', 'Jailed'),
  ('DELTA', 'POLICE DEPARTMENT', 'holding-cell', 'Arrested'),
  ('DELTA', 'POLICE DEPARTMENT', 'patrol', 'Police Officer (Delta Employee)'),
  ('DELTA', 'POLICE DEPARTMENT', 'evidence-room', 'Police Officer (Delta Employee)'),
  ('DELTA', 'POLICE DEPARTMENT', 'dcp-office', 'Police Officer (Delta Employee)'),
  ('DELTA', 'POLICE DEPARTMENT', 'dcp-office', 'Police Station Visitor'),
  ('DELTA', 'POLICE DEPARTMENT', 'cp-office', 'Delta Deputy Chief of Police'),
  ('DELTA', 'POLICE DEPARTMENT', 'cp-office', 'Police Station Visitor'),
  ('DELTA', 'POLICE DEPARTMENT', 'police-radio', 'Delta Chief of Police'),
  ('DELTA', 'POLICE DEPARTMENT', 'police-radio', 'Delta Deputy Chief of Police'),
  ('DELTA', 'GENERAL HOSPITAL', 'hospital-reception', 'Hospitalized'),
  ('DELTA', 'GENERAL HOSPITAL', 'hospital-reception', 'Medic Staff'),
  ('DELTA', 'GENERAL HOSPITAL', 'hospital-reception', 'Hospital Visitor'),
  ('DELTA', 'GENERAL HOSPITAL', 'hospital-reception', 'Out Patient'),
  ('DELTA', 'GENERAL HOSPITAL', 'nursing-station', 'Hospitalized'),
  ('DELTA', 'GENERAL HOSPITAL', 'nursing-station', 'Medic Staff (Delta Employee)'),
  ('DELTA', 'GENERAL HOSPITAL', 'nursing-station', 'Hospital Visitor'),
  ('DELTA', 'GENERAL HOSPITAL', 'nursing-station', 'Out Patient'),
  ('DELTA', 'GENERAL HOSPITAL', 'emergency', 'Hospitalized'),
  ('DELTA', 'GENERAL HOSPITAL', 'emergency', 'Medic Staff (Delta Employee)'),
  ('DELTA', 'GENERAL HOSPITAL', 'pharmacy-and-laboratory', 'Medic Staff (Delta Employee)'),
  ('DELTA', 'GENERAL HOSPITAL', 'consultation', 'Hospitalized'),
  ('DELTA', 'GENERAL HOSPITAL', 'consultation', 'Medic Staff (Delta Employee)'),
  ('DELTA', 'GENERAL HOSPITAL', 'dentistry', 'Dental Patient'),
  ('DELTA', 'GENERAL HOSPITAL', 'dentistry', 'Dentist (Delta Employee)'),
  ('DELTA', 'GENERAL HOSPITAL', 'female-wards', 'Hospitalized (Female)'),
  ('DELTA', 'GENERAL HOSPITAL', 'female-wards', 'Medic Staff (Delta Employee)'),
  ('DELTA', 'GENERAL HOSPITAL', 'male-wards', 'Hospitalized (Male)'),
  ('DELTA', 'GENERAL HOSPITAL', 'male-wards', 'Medic Staff (Delta Employee)'),
  ('DELTA', 'GENERAL HOSPITAL', 'surgical-theatre', 'Surgery Patient'),
  ('DELTA', 'GENERAL HOSPITAL', 'surgical-theatre', 'Medic Staff (Delta Employee)'),
  ('DELTA', 'GENERAL HOSPITAL', 'dmd-office', 'Medic Staff'),
  ('DELTA', 'GENERAL HOSPITAL', 'dmd-office', 'Deputy Medical Director (Delta Employee)'),
  ('DELTA', 'GENERAL HOSPITAL', 'dmd-office', 'Director Visitor'),
  ('DELTA', 'GENERAL HOSPITAL', 'cmd-office', 'Chief Medical Director'),
  ('DELTA', 'GENERAL HOSPITAL', 'cmd-office', 'Deputy Medical Director (Delta Employee)'),
  ('DELTA', 'PROPERTY AND DEVELOPMENT DEPARTMENT', 'agents-office', 'Housing Officer (Delta Employee)'),
  ('DELTA', 'ELECTRICITY DISTRIBUTION COMPANY', 'billing', 'Delta Resident'),
  ('DELTA', 'ELECTRICITY DISTRIBUTION COMPANY', 'billing', 'Technician (Delta Employee)'),
  ('DELTA', 'ELECTRICITY DISTRIBUTION COMPANY', 'fault-report', 'Technician (Delta Employee)'),
  ('DELTA', 'ELECTRICITY DISTRIBUTION COMPANY', 'fault-report', 'Commissioner of Power and Water (Delta Commissioner)'),
  ('DELTA', 'ELECTRICITY DISTRIBUTION COMPANY', 'technician-office', 'Technician (Delta Employee)'),
  ('DELTA', 'ELECTRICITY DISTRIBUTION COMPANY', 'technician-office', 'Delta Commissioner of Power and Water'),
  ('DELTA', 'ELECTRICITY DISTRIBUTION COMPANY', 'operations', 'Delta Commissioner of Power and Water'),
  ('DELTA', 'MID CLASS HOUSING', 'ughelli', 'Ughelli Resident'),
  ('DELTA', 'MID CLASS HOUSING', 'sapele', 'Sapele Resident'),
  ('DELTA', 'HIGH CLASS HOUSING', 'asaba', 'Asaba Resident'),
  ('DELTA', 'HIGH CLASS HOUSING', 'warri', 'Warri Resident'),
  ('DELTA', 'CAREER HIGH SCHOOL', 'school-building', 'Student'),
  ('DELTA', 'CAREER HIGH SCHOOL', 'school-hostel', 'Hostel Resident'),
  ('DELTA', 'STATE UNIVERSITY', 'school-of-nursing', 'Nursing Student'),
  ('DELTA', 'STATE UNIVERSITY', 'school-of-nursing', 'Doctor'),
  ('DELTA', 'STATE UNIVERSITY', 'school-of-administration', 'Admin Student'),
  ('DELTA', 'STATE UNIVERSITY', 'school-of-administration', 'Lecturer'),
  ('DELTA', 'STATE UNIVERSITY', 'campus-residence', 'Campus Resident'),
  ('DELTA', 'BUSINESS & COMMERCE', 'depot', 'Business Owner'),
  ('DELTA', 'BUSINESS & COMMERCE', 'depot', 'Supplier'),
  ('DELTA', 'BUSINESS & COMMERCE', 'industrial-goods', 'Delta Commissioner of Commerce'),
  ('DELTA', 'BUSINESS & COMMERCE', 'industrial-goods', 'Supplier'),
  ('DELTA', 'BUSINESS & COMMERCE', 'food-beverages-industry', 'Delta Commissioner of Commerce'),
  ('DELTA', 'BUSINESS & COMMERCE', 'food-beverages-industry', 'Supplier'),
  ('DELTA', 'BUSINESS & COMMERCE', 'refinery', 'Delta Commissioner of Petroleum'),
  ('DELTA', 'BUSINESS & COMMERCE', 'refinery', 'Gas Station Owner'),
  ('DELTA', 'BUSINESS & COMMERCE', 'refinery', 'Chief of Staff'),
  ('DELTA', 'BUSINESS & COMMERCE', 'oil-well', 'Delta Commissioner of Petroleum'),
  ('DELTA', 'BUSINESS & COMMERCE', 'oil-well', 'President'),
  ('DELTA', 'BUSINESS & COMMERCE', 'oil-well', 'Vice President'),
  ('DELTA', 'BUSINESS & COMMERCE', 'oil-well', 'Minister of Petroleum'),
  ('DELTA', 'FARMS', 'farmland', 'Farmer'),
  ('DELTA', 'FARMS', 'farmland', 'Trader'),
  ('DELTA', 'FARMS', 'farmland', 'Delta Commissioner of Agriculture'),
  ('DELTA', 'FARMS', 'Ranch', 'Rancher'),
  ('DELTA', 'FARMS', 'Ranch', 'Butcher'),
  ('DELTA', 'FARMS', 'Ranch', 'Delta Commissioner of Agriculture'),
  ('DELTA', 'FARMS', 'River', 'Fisherman'),
  ('DELTA', 'FARMS', 'River', 'Trader'),
  ('DELTA', 'FARMS', 'River', 'Delta Commissioner of Agriculture'),
  ('LAGOS', 'BORDER & ENTRY', 'front-desk', 'Immigration Officer'),
  ('LAGOS', 'BORDER & ENTRY', 'parcel-pickup', 'Dispatch Rider'),
  ('LAGOS', 'BORDER & ENTRY', 'parcel-pickup', 'Immigration Officer'),
  ('LAGOS', 'BORDER & ENTRY', 'chief-marshal-office', 'Chief Immigration Marshal'),
  ('LAGOS', 'HOTEL & SUITES', 'hotel-lobby', 'Hotel Guest'),
  ('LAGOS', 'BROADCASTING STATION', 'production-room', 'Media Staff (Lagos Employee)'),
  ('LAGOS', 'BROADCASTING STATION', 'production-room', 'Journalist (Lagos Employee)'),
  ('LAGOS', 'BROADCASTING STATION', 'production-room', 'Reporter (Lagos Employee)'),
  ('LAGOS', 'BROADCASTING STATION', 'media-manager', 'Media Manager (Lagos Employee)'),
  ('LAGOS', 'JUDICIARY', 'lawyer-chambers', 'Lawyers (Lagos Employee)'),
  ('LAGOS', 'JUDICIARY', 'judge-chambers', 'Supreme Judge (Lagos Employee)'),
  ('LAGOS', 'STATE GOVERNMENT', 'governor-office', 'Lagos Governor'),
  ('LAGOS', 'STATE GOVERNMENT', 'governor-office', 'Appointment with Governor'),
  ('LAGOS', 'STATE GOVERNMENT', 'deputy-governor-office', 'Governor'),
  ('LAGOS', 'STATE GOVERNMENT', 'deputy-governor-office', 'Deputy Governor'),
  ('LAGOS', 'STATE GOVERNMENT', 'deputy-governor-office', 'Appointment with Deputy'),
  ('LAGOS', 'STATE GOVERNMENT', 'chief-of-staff', 'Lagos Commissioner'),
  ('LAGOS', 'STATE GOVERNMENT', 'chief-of-staff', 'FCT Commissioner'),
  ('LAGOS', 'STATE GOVERNMENT', 'chief-of-staff', 'President'),
  ('LAGOS', 'STATE GOVERNMENT', 'chief-of-staff', 'Vice President'),
  ('LAGOS', 'STATE GOVERNMENT', 'chief-of-staff', 'FCT Minister'),
  ('LAGOS', 'STATE GOVERNMENT', 'state-secretariat', 'Lagos Commissioner'),
  ('LAGOS', 'STATE GOVERNMENT', 'state-secretariat', 'FCT Commissioner'),
  ('LAGOS', 'STATE GOVERNMENT', 'council', 'Lagos Commissioner'),
  ('LAGOS', 'STATE GOVERNMENT', 'ministry-of-finance', 'Lagos Commissioner'),
  ('LAGOS', 'STATE GOVERNMENT', 'ministry-of-finance', 'Bank Manager (Lagos Employee)'),
  ('LAGOS', 'STATE GOVERNMENT', 'ministry-of-finance', 'Minister of Finance'),
  ('LAGOS', 'STATE GOVERNMENT', 'ministry-of-finance', 'Lagos Commissioner of Finance'),
  ('LAGOS', 'STATE GOVERNMENT', 'ministry-of-justice', 'Lagos Commissioner'),
  ('LAGOS', 'STATE GOVERNMENT', 'ministry-of-justice', 'High Court Judge'),
  ('LAGOS', 'STATE GOVERNMENT', 'ministry-of-justice', 'Supreme Judge'),
  ('LAGOS', 'STATE GOVERNMENT', 'ministry-of-agriculture', 'Lagos Commissioner'),
  ('LAGOS', 'STATE GOVERNMENT', 'ministry-of-agriculture', 'Minister of Agriculture'),
  ('LAGOS', 'STATE GOVERNMENT', 'ministry-of-housing', 'Lagos Commissioner'),
  ('LAGOS', 'STATE GOVERNMENT', 'ministry-of-housing', 'Minister of Housing'),
  ('LAGOS', 'STATE GOVERNMENT', 'ministry-of-education', 'Lagos Commissioner'),
  ('LAGOS', 'STATE GOVERNMENT', 'ministry-of-education', 'Minister of Education'),
  ('LAGOS', 'STATE GOVERNMENT', 'ministry-of-commerce', 'Lagos Commissioner'),
  ('LAGOS', 'STATE GOVERNMENT', 'ministry-of-commerce', 'Minister of Trade and Commerce'),
  ('LAGOS', 'STATE GOVERNMENT', 'ministry-of-commerce', 'Lagos Commissioner of Commerce'),
  ('LAGOS', 'STATE GOVERNMENT', 'ministry-of-power-and-water', 'Lagos Commissioner'),
  ('LAGOS', 'STATE GOVERNMENT', 'ministry-of-power-and-water', 'Minister of Power and Water'),
  ('LAGOS', 'STATE GOVERNMENT', 'ministry-of-petroleum', 'Lagos Commissioner'),
  ('LAGOS', 'STATE GOVERNMENT', 'ministry-of-petroleum', 'Minister of Petroleum'),
  ('LAGOS', 'STATE GOVERNMENT', 'city-hall', 'Lagos Indigine'),
  ('LAGOS', 'STATE GOVERNMENT', 'city-hall', 'Lagos Resident'),
  ('LAGOS', 'GOVERNOR''S HOUSE', 'governor-penthouse', 'Lagos Governor'),
  ('LAGOS', 'GOVERNOR''S HOUSE', 'governor-penthouse', 'Deputy Governor'),
  ('LAGOS', 'GOVERNOR''S HOUSE', 'governor-penthouse', 'Governor Visitor'),
  ('LAGOS', 'GOVERNOR''S HOUSE', 'deputy-governor-residence', 'Lagos Governor'),
  ('LAGOS', 'GOVERNOR''S HOUSE', 'deputy-governor-residence', 'Deputy Governor'),
  ('LAGOS', 'GOVERNOR''S HOUSE', 'deputy-governor-residence', 'Governor Visitor'),
  ('LAGOS', 'GOVERNOR''S HOUSE', 'governor-guesthouse', 'Lagos Governor'),
  ('LAGOS', 'GOVERNOR''S HOUSE', 'governor-guesthouse', 'Deputy Governor'),
  ('LAGOS', 'GOVERNOR''S HOUSE', 'governor-guesthouse', 'Governor Guest'),
  ('LAGOS', 'BANK PLC', 'customer-care', 'Bank Staff (Lagos Employee)'),
  ('LAGOS', 'BANK PLC', 'accountant', 'Bank Staff (Lagos Employee)'),
  ('LAGOS', 'BANK PLC', 'deposit', 'Bank Staff (Lagos Employee)'),
  ('LAGOS', 'BANK PLC', 'bank-manager', 'Bank Staff (Lagos Employee)'),
  ('LAGOS', 'BANK PLC', 'transaction-log', 'Bank Manager (Lagos Employee)'),
  ('LAGOS', 'BANK PLC', 'treasury', 'Bank Manager (Lagos Employee)'),
  ('LAGOS', 'POLICE DEPARTMENT', 'officers-office', 'Police Officer (Lagos Employee)'),
  ('LAGOS', 'POLICE DEPARTMENT', 'investigation-room', 'Police Officer (Lagos Employee)'),
  ('LAGOS', 'POLICE DEPARTMENT', 'investigation-room', 'Suspect'),
  ('LAGOS', 'POLICE DEPARTMENT', 'investigation-room', 'Arrested'),
  ('LAGOS', 'POLICE DEPARTMENT', 'holding-cell', 'Police Officer (Lagos Employee)'),
  ('LAGOS', 'POLICE DEPARTMENT', 'holding-cell', 'Jailed'),
  ('LAGOS', 'POLICE DEPARTMENT', 'holding-cell', 'Arrested'),
  ('LAGOS', 'POLICE DEPARTMENT', 'patrol', 'Police Officer (Lagos Employee)'),
  ('LAGOS', 'POLICE DEPARTMENT', 'evidence-room', 'Police Officer (Lagos Employee)'),
  ('LAGOS', 'POLICE DEPARTMENT', 'dcp-office', 'Police Officer (Lagos Employee)'),
  ('LAGOS', 'POLICE DEPARTMENT', 'dcp-office', 'Police Station Visitor'),
  ('LAGOS', 'POLICE DEPARTMENT', 'cp-office', 'Lagos Deputy Chief of Police'),
  ('LAGOS', 'POLICE DEPARTMENT', 'cp-office', 'Police Station Visitor'),
  ('LAGOS', 'POLICE DEPARTMENT', 'police-radio', 'Lagos Chief of Police'),
  ('LAGOS', 'POLICE DEPARTMENT', 'police-radio', 'Lagos Deputy Chief of Police'),
  ('LAGOS', 'GENERAL HOSPITAL', 'hospital-reception', 'Hospitalized'),
  ('LAGOS', 'GENERAL HOSPITAL', 'hospital-reception', 'Medic Staff'),
  ('LAGOS', 'GENERAL HOSPITAL', 'hospital-reception', 'Hospital Visitor'),
  ('LAGOS', 'GENERAL HOSPITAL', 'hospital-reception', 'Out Patient'),
  ('LAGOS', 'GENERAL HOSPITAL', 'nursing-station', 'Hospitalized'),
  ('LAGOS', 'GENERAL HOSPITAL', 'nursing-station', 'Medic Staff (Lagos Employee)'),
  ('LAGOS', 'GENERAL HOSPITAL', 'nursing-station', 'Hospital Visitor'),
  ('LAGOS', 'GENERAL HOSPITAL', 'nursing-station', 'Out Patient'),
  ('LAGOS', 'GENERAL HOSPITAL', 'emergency', 'Hospitalized'),
  ('LAGOS', 'GENERAL HOSPITAL', 'emergency', 'Medic Staff (Lagos Employee)'),
  ('LAGOS', 'GENERAL HOSPITAL', 'pharmacy-and-laboratory', 'Medic Staff (Lagos Employee)'),
  ('LAGOS', 'GENERAL HOSPITAL', 'consultation', 'Hospitalized'),
  ('LAGOS', 'GENERAL HOSPITAL', 'consultation', 'Medic Staff (Lagos Employee)'),
  ('LAGOS', 'GENERAL HOSPITAL', 'dentistry', 'Dental Patient'),
  ('LAGOS', 'GENERAL HOSPITAL', 'dentistry', 'Dentist (Lagos Employee)'),
  ('LAGOS', 'GENERAL HOSPITAL', 'female-wards', 'Hospitalized (Female)'),
  ('LAGOS', 'GENERAL HOSPITAL', 'female-wards', 'Medic Staff (Lagos Employee)'),
  ('LAGOS', 'GENERAL HOSPITAL', 'male-wards', 'Hospitalized (Male)'),
  ('LAGOS', 'GENERAL HOSPITAL', 'male-wards', 'Medic Staff (Lagos Employee)'),
  ('LAGOS', 'GENERAL HOSPITAL', 'surgical-theatre', 'Surgery Patient'),
  ('LAGOS', 'GENERAL HOSPITAL', 'surgical-theatre', 'Medic Staff (Lagos Employee)'),
  ('LAGOS', 'GENERAL HOSPITAL', 'dmd-office', 'Medic Staff'),
  ('LAGOS', 'GENERAL HOSPITAL', 'dmd-office', 'Deputy Medical Director (Lagos Employee)'),
  ('LAGOS', 'GENERAL HOSPITAL', 'dmd-office', 'Director Visitor'),
  ('LAGOS', 'GENERAL HOSPITAL', 'cmd-office', 'Chief Medical Director'),
  ('LAGOS', 'GENERAL HOSPITAL', 'cmd-office', 'Deputy Medical Director (Lagos Employee)'),
  ('LAGOS', 'PROPERTY AND DEVELOPMENT DEPARTMENT', 'agents-office', 'Housing Officer (Lagos Employee)'),
  ('LAGOS', 'ELECTRICITY DISTRIBUTION COMPANY', 'fault-report', 'Technician (Lagos Employee)'),
  ('LAGOS', 'ELECTRICITY DISTRIBUTION COMPANY', 'fault-report', 'Commissioner of Power and Water (Lagos Commissioner)'),
  ('LAGOS', 'ELECTRICITY DISTRIBUTION COMPANY', 'technician-office', 'Technician (Lagos Employee)'),
  ('LAGOS', 'ELECTRICITY DISTRIBUTION COMPANY', 'technician-office', 'Lagos Commissioner of Power and Water'),
  ('LAGOS', 'ELECTRICITY DISTRIBUTION COMPANY', 'operations', 'Lagos Commissioner of Power and Water'),
  ('LAGOS', 'MAINLAND', 'ikeja', 'Ikeja Resident'),
  ('LAGOS', 'MAINLAND', 'gbagada', 'Gbagada Resident'),
  ('LAGOS', 'MAINLAND', 'yaba', 'Yaba Resident'),
  ('LAGOS', 'ISLAND', 'lekki-phase-1', 'Lekki Phase 1 Resident'),
  ('LAGOS', 'ISLAND', 'lekki-phase-2', 'Lekki Phase 2 Resident'),
  ('LAGOS', 'ISLAND', 'ikoyi', 'Ikoyi Resident'),
  ('LAGOS', 'CAREER HIGH SCHOOL', 'school-building', 'Student'),
  ('LAGOS', 'CAREER HIGH SCHOOL', 'school-hostel', 'Hostel Resident'),
  ('LAGOS', 'DEFENCE ACADEMY', 'training-ground', 'Rookie'),
  ('LAGOS', 'DEFENCE ACADEMY', 'training-ground', 'Detective'),
  ('LAGOS', 'DEFENCE ACADEMY', 'lecture-area', 'Rookie'),
  ('LAGOS', 'DEFENCE ACADEMY', 'lecture-area', 'Detective'),
  ('LAGOS', 'DEFENCE ACADEMY', 'campus-residence', 'Campus Resident'),
  ('LAGOS', 'BUSINESS & COMMERCE', 'depot', 'Business Owner'),
  ('LAGOS', 'BUSINESS & COMMERCE', 'depot', 'Supplier'),
  ('LAGOS', 'BUSINESS & COMMERCE', 'industrial-goods', 'Lagos Commissioner of Commerce'),
  ('LAGOS', 'BUSINESS & COMMERCE', 'industrial-goods', 'Supplier'),
  ('LAGOS', 'BUSINESS & COMMERCE', 'food-beverages-industry', 'Lagos Commissioner of Commerce'),
  ('LAGOS', 'BUSINESS & COMMERCE', 'food-beverages-industry', 'Supplier'),
  ('LAGOS', 'BUSINESS & COMMERCE', 'refinery', 'Lagos Commissioner of Petroleum'),
  ('LAGOS', 'BUSINESS & COMMERCE', 'refinery', 'Gas Station Owner'),
  ('LAGOS', 'BUSINESS & COMMERCE', 'refinery', 'Chief of Staff'),
  ('LAGOS', 'BUSINESS & COMMERCE', 'sea-port', 'Minister of Trade and Commerce'),
  ('LAGOS', 'BUSINESS & COMMERCE', 'sea-port', 'Lagos Commissioner of Commerce'),
  ('LAGOS', 'FARMS', 'river', 'Fisherman'),
  ('LAGOS', 'FARMS', 'river', 'Trader'),
  ('LAGOS', 'FARMS', 'river', 'Lagos Commissioner of Agriculture'),
  ('ABUJA', 'TELEVISION AUTHORITY', 'production-room', 'Media Staff (FCT Employee)'),
  ('ABUJA', 'TELEVISION AUTHORITY', 'production-room', 'Journalist (FCT Employee)'),
  ('ABUJA', 'TELEVISION AUTHORITY', 'production-room', 'Reporter (FCT Employee)'),
  ('ABUJA', 'TELEVISION AUTHORITY', 'media-manager', 'Media Manager (FCT Employee)'),
  ('ABUJA', 'FEDERAL GOVERNMENT', 'state-secretariat', 'FCT Commissioner'),
  ('ABUJA', 'FEDERAL GOVERNMENT', 'state-secretariat', 'Lagos Commissioner'),
  ('ABUJA', 'FEDERAL GOVERNMENT', 'council', 'FCT Commissioner'),
  ('ABUJA', 'FEDERAL GOVERNMENT', 'ministry-of-finance', 'FCT Commissioner'),
  ('ABUJA', 'FEDERAL GOVERNMENT', 'ministry-of-finance', 'Bank Manager (FCT Employee)'),
  ('ABUJA', 'FEDERAL GOVERNMENT', 'ministry-of-finance', 'Minister of Finance'),
  ('ABUJA', 'FEDERAL GOVERNMENT', 'ministry-of-finance', 'FCT Commissioner of Finance'),
  ('ABUJA', 'FEDERAL GOVERNMENT', 'ministry-of-justice', 'FCT Commissioner'),
  ('ABUJA', 'FEDERAL GOVERNMENT', 'ministry-of-justice', 'High Court Judge'),
  ('ABUJA', 'FEDERAL GOVERNMENT', 'ministry-of-justice', 'Supreme Judge'),
  ('ABUJA', 'FEDERAL GOVERNMENT', 'ministry-of-agriculture', 'FCT Commissioner'),
  ('ABUJA', 'FEDERAL GOVERNMENT', 'ministry-of-agriculture', 'Minister of Agriculture'),
  ('ABUJA', 'FEDERAL GOVERNMENT', 'ministry-of-housing', 'FCT Commissioner'),
  ('ABUJA', 'FEDERAL GOVERNMENT', 'ministry-of-housing', 'Minister of Housing'),
  ('ABUJA', 'FEDERAL GOVERNMENT', 'ministry-of-education', 'FCT Commissioner'),
  ('ABUJA', 'FEDERAL GOVERNMENT', 'ministry-of-education', 'Minister of Education'),
  ('ABUJA', 'FEDERAL GOVERNMENT', 'ministry-of-commerce', 'FCT Commissioner'),
  ('ABUJA', 'FEDERAL GOVERNMENT', 'ministry-of-commerce', 'Minister of Trade and Commerce'),
  ('ABUJA', 'FEDERAL GOVERNMENT', 'ministry-of-commerce', 'FCT Commissioner of Commerce'),
  ('ABUJA', 'FEDERAL GOVERNMENT', 'ministry-of-power-and-water', 'FCT Commissioner'),
  ('ABUJA', 'FEDERAL GOVERNMENT', 'ministry-of-power-and-water', 'Minister of Power and Water'),
  ('ABUJA', 'FEDERAL GOVERNMENT', 'ministry-of-petroleum', 'FCT Commissioner'),
  ('ABUJA', 'FEDERAL GOVERNMENT', 'ministry-of-petroleum', 'Minister of Petroleum'),
  ('ABUJA', 'FEDERAL GOVERNMENT', 'ministry-of-information-and-culture', 'FCT Commissioner'),
  ('ABUJA', 'FEDERAL GOVERNMENT', 'ministry-of-information-and-culture', 'Minister of Information and Culture'),
  ('ABUJA', 'FEDERAL GOVERNMENT', 'ministry-of-health', 'FCT Commissioner'),
  ('ABUJA', 'FEDERAL GOVERNMENT', 'ministry-of-health', 'Minister of Health'),
  ('ABUJA', 'FEDERAL GOVERNMENT', 'city-hall', 'FCT Indigine'),
  ('ABUJA', 'FEDERAL GOVERNMENT', 'city-hall', 'FCT Resident'),
  ('ABUJA', 'ASO ROCK', 'chief-of-staff', 'FCT Commissioner'),
  ('ABUJA', 'ASO ROCK', 'chief-of-staff', 'Lagos Commissioner'),
  ('ABUJA', 'ASO ROCK', 'chief-of-staff', 'President'),
  ('ABUJA', 'ASO ROCK', 'chief-of-staff', 'Vice President'),
  ('ABUJA', 'ASO ROCK', 'chief-of-staff', 'FCT Minister'),
  ('ABUJA', 'BANK PLC', 'customer-care', 'Bank Staff (FCT Employee)'),
  ('ABUJA', 'BANK PLC', 'accountant', 'Bank Staff (FCT Employee)'),
  ('ABUJA', 'BANK PLC', 'deposit', 'Bank Staff (FCT Employee)'),
  ('ABUJA', 'BANK PLC', 'bank-manager', 'Bank Staff (FCT Employee)'),
  ('ABUJA', 'BANK PLC', 'transaction-log', 'Bank Manager (FCT Employee)'),
  ('ABUJA', 'BANK PLC', 'treasury', 'Bank Manager (FCT Employee)'),
  ('ABUJA', 'POLICE DEPARTMENT', 'officers-office', 'Police Officer (FCT Employee)'),
  ('ABUJA', 'POLICE DEPARTMENT', 'investigation-room', 'Police Officer (FCT Employee)'),
  ('ABUJA', 'POLICE DEPARTMENT', 'investigation-room', 'Suspect'),
  ('ABUJA', 'POLICE DEPARTMENT', 'investigation-room', 'Arrested'),
  ('ABUJA', 'POLICE DEPARTMENT', 'holding-cell', 'Police Officer (FCT Employee)'),
  ('ABUJA', 'POLICE DEPARTMENT', 'holding-cell', 'Jailed'),
  ('ABUJA', 'POLICE DEPARTMENT', 'holding-cell', 'Arrested'),
  ('ABUJA', 'POLICE DEPARTMENT', 'patrol', 'Police Officer (FCT Employee)'),
  ('ABUJA', 'POLICE DEPARTMENT', 'evidence-room', 'Police Officer (FCT Employee)'),
  ('ABUJA', 'POLICE DEPARTMENT', 'dcp-office', 'Police Officer (FCT Employee)'),
  ('ABUJA', 'POLICE DEPARTMENT', 'dcp-office', 'Police Station Visitor'),
  ('ABUJA', 'POLICE DEPARTMENT', 'cp-office', 'FCT Deputy Chief of Police'),
  ('ABUJA', 'POLICE DEPARTMENT', 'cp-office', 'Police Station Visitor'),
  ('ABUJA', 'POLICE DEPARTMENT', 'police-radio', 'FCT Chief of Police'),
  ('ABUJA', 'POLICE DEPARTMENT', 'police-radio', 'FCT Deputy Chief of Police'),
  ('ABUJA', 'GENERAL HOSPITAL', 'hospital-reception', 'Hospitalized'),
  ('ABUJA', 'GENERAL HOSPITAL', 'hospital-reception', 'Medic Staff'),
  ('ABUJA', 'GENERAL HOSPITAL', 'hospital-reception', 'Hospital Visitor'),
  ('ABUJA', 'GENERAL HOSPITAL', 'hospital-reception', 'Out Patient'),
  ('ABUJA', 'GENERAL HOSPITAL', 'nursing-station', 'Hospitalized'),
  ('ABUJA', 'GENERAL HOSPITAL', 'nursing-station', 'Medic Staff (FCT Employee)'),
  ('ABUJA', 'GENERAL HOSPITAL', 'nursing-station', 'Hospital Visitor'),
  ('ABUJA', 'GENERAL HOSPITAL', 'nursing-station', 'Out Patient'),
  ('ABUJA', 'GENERAL HOSPITAL', 'emergency', 'Hospitalized'),
  ('ABUJA', 'GENERAL HOSPITAL', 'emergency', 'Medic Staff (FCT Employee)'),
  ('ABUJA', 'GENERAL HOSPITAL', 'pharmacy-and-laboratory', 'Medic Staff (FCT Employee)'),
  ('ABUJA', 'GENERAL HOSPITAL', 'consultation', 'Hospitalized'),
  ('ABUJA', 'GENERAL HOSPITAL', 'consultation', 'Medic Staff (FCT Employee)'),
  ('ABUJA', 'GENERAL HOSPITAL', 'dentistry', 'Dental Patient'),
  ('ABUJA', 'GENERAL HOSPITAL', 'dentistry', 'Dentist (FCT Employee)'),
  ('ABUJA', 'GENERAL HOSPITAL', 'female-wards', 'Hospitalized (Female)'),
  ('ABUJA', 'GENERAL HOSPITAL', 'female-wards', 'Medic Staff (FCT Employee)'),
  ('ABUJA', 'GENERAL HOSPITAL', 'male-wards', 'Hospitalized (Male)'),
  ('ABUJA', 'GENERAL HOSPITAL', 'male-wards', 'Medic Staff (FCT Employee)'),
  ('ABUJA', 'GENERAL HOSPITAL', 'surgical-theatre', 'Surgery Patient'),
  ('ABUJA', 'GENERAL HOSPITAL', 'surgical-theatre', 'Medic Staff (FCT Employee)'),
  ('ABUJA', 'GENERAL HOSPITAL', 'dmd-office', 'Medic Staff'),
  ('ABUJA', 'GENERAL HOSPITAL', 'dmd-office', 'Deputy Medical Director (FCT Employee)'),
  ('ABUJA', 'GENERAL HOSPITAL', 'dmd-office', 'Director Visitor'),
  ('ABUJA', 'GENERAL HOSPITAL', 'cmd-office', 'Chief Medical Director'),
  ('ABUJA', 'GENERAL HOSPITAL', 'cmd-office', 'Deputy Medical Director (FCT Employee)'),
  ('ABUJA', 'PROPERTY AND DEVELOPMENT DEPARTMENT', 'agents-office', 'Housing Officer (FCT Employee)'),
  ('ABUJA', 'ELECTRICITY DISTRIBUTION COMPANY', 'fault-report', 'Technician (FCT Employee)'),
  ('ABUJA', 'ELECTRICITY DISTRIBUTION COMPANY', 'fault-report', 'Commissioner of Power and Water (FCT Commissioner)'),
  ('ABUJA', 'ELECTRICITY DISTRIBUTION COMPANY', 'technician-office', 'Technician (FCT Employee)'),
  ('ABUJA', 'ELECTRICITY DISTRIBUTION COMPANY', 'technician-office', 'FCT Commissioner of Power and Water'),
  ('ABUJA', 'ELECTRICITY DISTRIBUTION COMPANY', 'operations', 'FCT Commissioner of Power and Water'),
  ('ABUJA', 'MID CLASS HOUSING', 'gwarinpa', 'Gwarinpa Resident'),
  ('ABUJA', 'MID CLASS HOUSING', 'kubwa', 'Kubwa Resident'),
  ('ABUJA', 'HIGH CLASS HOUSING', 'maitama', 'Maitama Resident'),
  ('ABUJA', 'HIGH CLASS HOUSING', 'asokoro', 'Asokoro Resident'),
  ('ABUJA', 'CAREER HIGH SCHOOL', 'school-building', 'Student'),
  ('ABUJA', 'CAREER HIGH SCHOOL', 'school-hostel', 'Hostel Resident'),
  ('ABUJA', 'UNIVERSITY OF BANKING AND MEDICINE', 'campus-residence', 'Campus Resident'),
  ('ABUJA', 'BUSINESS & COMMERCE', 'depot', 'Business Owner'),
  ('ABUJA', 'BUSINESS & COMMERCE', 'depot', 'Supplier'),
  ('ABUJA', 'BUSINESS & COMMERCE', 'industrial-goods', 'FCT Commissioner of Commerce'),
  ('ABUJA', 'BUSINESS & COMMERCE', 'industrial-goods', 'Supplier'),
  ('ABUJA', 'BUSINESS & COMMERCE', 'food-beverages-industry', 'FCT Commissioner of Commerce'),
  ('ABUJA', 'BUSINESS & COMMERCE', 'food-beverages-industry', 'Supplier'),
  ('ABUJA', 'BUSINESS & COMMERCE', 'refinery', 'FCT Commissioner of Petroleum'),
  ('ABUJA', 'BUSINESS & COMMERCE', 'refinery', 'Gas Station Owner'),
  ('ABUJA', 'BUSINESS & COMMERCE', 'refinery', 'Chief of Staff'),
  ('ABUJA', 'BUSINESS & COMMERCE', 'mining-ground', 'Minister of Trade and Commerce'),
  ('ABUJA', 'BUSINESS & COMMERCE', 'mining-ground', 'FCT Commissioner of Commerce'),
  ('ABUJA', 'FARMS', 'farmland', 'Farmer'),
  ('ABUJA', 'FARMS', 'farmland', 'Trader'),
  ('ABUJA', 'FARMS', 'farmland', 'FCT Commissioner of Agriculture'),
  ('ABUJA', 'FARMS', 'ranch', 'Rancher'),
  ('ABUJA', 'FARMS', 'ranch', 'Butcher'),
  ('ABUJA', 'FARMS', 'ranch', 'FCT Commissioner of Agriculture'),
  ('ABUJA', 'CENTRAL BANK OF NIGERIA', 'national-treasury', 'CBN Governor'),
  ('ABUJA', 'CENTRAL BANK OF NIGERIA', 'national-treasury', 'Minister of Finance')
) AS v(state, category, channel_name, role_name)
JOIN locations l ON l.state = v.state AND l.category = v.category AND l.channel_name = v.channel_name
JOIN roles r ON r.name = v.role_name
ON CONFLICT (location_id, role_id) DO NOTHING;
