-- Every role named in the DELTA / LAGOS / ABUJA design docs. role_id is left
-- NULL -- fill it in once each role exists as an actual Discord role, same as
-- the TODOs in config.py.
--
-- Roles that used to be single combined strings like "Medic Staff (Delta
-- Employee)" are now two separate roles: a job role ("Medic Staff") plus a
-- shared state-employee role ("Delta Employee" / "Lagos Employee" /
-- "FCT Employee"). A member needs BOTH to count as e.g. a Delta medic --
-- see location_roles_seed.sql for how they're paired per location, and
-- schema.sql for the group_id that expresses that AND requirement.
--
-- "Delta" / "Lagos" / "Abuja" (below) are separate from "Delta Indigine" /
-- "Delta Resident" etc. -- those Indigine/Resident roles serve a different
-- purpose and are untouched here. The plain state-name role is the general
-- "currently settled in this state" gate: everyone who's completed
-- immigration into a state holds that state's role (Indigine or Resident,
-- doesn't matter), and it's what should gate that state's general/open
-- channels so e.g. a Lagos resident doesn't see Delta's or Abuja's areas.
-- This lines up with config.py's per-state "indigene_role_id" -- despite
-- the similar name, that config field should point at this role, not at
-- the "Indigine" role above.

INSERT INTO roles (name) VALUES
('Abuja'),
('Abuja Arrival'),
('Admin Student'),
('Appointment with Deputy'),
('Appointment with Governor'),
('Appointment with IGP'),
('Appointment with Minister'),
('Appointment with President'),
('Appointment with Vice'),
('Arrested'),
('Asaba Resident'),
('Asokoro Resident'),
('Bank Manager'),
('Bank Staff'),
('Banking Student'),
('Business Owner'),
('Butcher'),
('CBN Deputy'),
('CBN Governor'),
('Campus Resident'),
('Chief Immigration Marshal'),
('Chief Medical Director'),
('Chief of Staff'),
('Delta'),
('Delta Arrival'),
('Delta Chief of Police'),
('Delta Commissioner'),
('Delta Commissioner of Agriculture'),
('Delta Commissioner of Commerce'),
('Delta Commissioner of Finance'),
('Delta Commissioner of Petroleum'),
('Delta Commissioner of Power and Water'),
('Delta Deputy Chief of Police'),
('Delta Employee'),
('Delta Governor'),
('Delta Indigine'),
('Delta Resident'),
('Dental Patient'),
('Dentist'),
('Deputy Governor'),
('Deputy Medical Director'),
('Detective'),
('Director Visitor'),
('Dispatch Rider'),
('Doctor'),
('FCT Chief of Police'),
('FCT Commissioner'),
('FCT Commissioner of Agriculture'),
('FCT Commissioner of Commerce'),
('FCT Commissioner of Finance'),
('FCT Commissioner of Petroleum'),
('FCT Commissioner of Power and Water'),
('FCT Deputy Chief of Police'),
('FCT Employee'),
('FCT Indigine'),
('FCT Minister'),
('FCT Resident'),
('Farmer'),
('Fisherman'),
('Gas Station Owner'),
('Gbagada Resident'),
('Governor'),
('Governor Guest'),
('Governor Visitor'),
('Gwarinpa Resident'),
('High Court Judge'),
('Hospital Visitor'),
('Hospitalized'),
('Hospitalized (Female)'),
('Hospitalized (Male)'),
('Hostel Resident'),
('Hotel Guest'),
('Housing Officer'),
('Ikeja Resident'),
('Ikoyi Resident'),
('Immigration Officer'),
('Imprisoned'),
('Inspector General of Police'),
('Jailed'),
('Journalist'),
('Kubwa Resident'),
('Lagos'),
('Lagos Arrival'),
('Lagos Chief of Police'),
('Lagos Commissioner'),
('Lagos Commissioner of Agriculture'),
('Lagos Commissioner of Commerce'),
('Lagos Commissioner of Finance'),
('Lagos Commissioner of Petroleum'),
('Lagos Commissioner of Power and Water'),
('Lagos Deputy Chief of Police'),
('Lagos Employee'),
('Lagos Governor'),
('Lagos Indigine'),
('Lagos Resident'),
('Lawyers'),
('Lecturer'),
('Lekki Phase 1 Resident'),
('Lekki Phase 2 Resident'),
('Maitama Resident'),
('Media Manager'),
('Media Staff'),
('Medic Staff'),
('Medicine Student'),
('Minister of Agriculture'),
('Minister of Education'),
('Minister of Finance'),
('Minister of Health'),
('Minister of Housing'),
('Minister of Information and Culture'),
('Minister of Petroleum'),
('Minister of Power and Water'),
('Minister of Trade and Commerce'),
('Nursing Student'),
('Out Patient'),
('Police Officer'),
('Police Station Visitor'),
('President'),
('Presidential Guest'),
('Presidential Resident'),
('Presidential Visitor'),
('Rancher'),
('Reporter'),
('Rookie'),
('Sapele Resident'),
('Student'),
('Supplier'),
('Supreme Judge'),
('Surgery Patient'),
('Suspect'),
('Technician'),
('Trader'),
('Ughelli Resident'),
('Vice President'),
('Villa Staff'),
('Warri Resident'),
('Yaba Resident')
ON CONFLICT (name) DO NOTHING;
