-- Every role named in the DELTA / LAGOS / ABUJA design docs. role_id is left
-- NULL -- fill it in once each role exists as an actual Discord role, same as
-- the TODOs in config.py.

INSERT INTO roles (name) VALUES
('Admin Student'),
('Appointment with Deputy'),
('Appointment with Governor'),
('Arrested'),
('Asaba Resident'),
('Asokoro Resident'),
('Bank Manager (Delta Employee)'),
('Bank Manager (FCT Employee)'),
('Bank Manager (Lagos Employee)'),
('Bank Staff (Delta Employee)'),
('Bank Staff (FCT Employee)'),
('Bank Staff (Lagos Employee)'),
('Business Owner'),
('Butcher'),
('Campus Resident'),
('Chief Immigration Marshal'),
('Chief Medical Director'),
('Chief of Staff'),
('Commissioner of Power and Water (Delta Commissioner)'),
('Commissioner of Power and Water (FCT Commissioner)'),
('Commissioner of Power and Water (Lagos Commissioner)'),
('Delta Chief of Police'),
('Delta Commissioner'),
('Delta Commissioner of Agriculture'),
('Delta Commissioner of Commerce'),
('Delta Commissioner of Finance'),
('Delta Commissioner of Petroleum'),
('Delta Commissioner of Power and Water'),
('Delta Deputy Chief of Police'),
('Delta Governor'),
('Delta Indigine'),
('Delta Resident'),
('Dental Patient'),
('Dentist (Delta Employee)'),
('Dentist (FCT Employee)'),
('Dentist (Lagos Employee)'),
('Deputy Governor'),
('Deputy Medical Director (Delta Employee)'),
('Deputy Medical Director (FCT Employee)'),
('Deputy Medical Director (Lagos Employee)'),
('Detective'),
('Director Visitor'),
('Dispatch Rider'),
('Doctor'),
('FCT Chief of Police'),
('FCT Commissioner'),
('FCT Commissioner of Agriculture'),
('FCT Commissioner of Commerce'),
('FCT Commissioner of Finance'),
('FCT Commissioner of Petroleum'),
('FCT Commissioner of Power and Water'),
('FCT Deputy Chief of Police'),
('FCT Indigine'),
('FCT Minister'),
('FCT Resident'),
('Farmer'),
('Fisherman'),
('Gas Station Owner'),
('Gbagada Resident'),
('Governor'),
('Governor Guest'),
('Governor Visitor'),
('Gwarinpa Resident'),
('High Court Judge'),
('Hospital Visitor'),
('Hospitalized'),
('Hospitalized (Female)'),
('Hospitalized (Male)'),
('Hostel Resident'),
('Hotel Guest'),
('Housing Officer (Delta Employee)'),
('Housing Officer (FCT Employee)'),
('Housing Officer (Lagos Employee)'),
('Ikeja Resident'),
('Ikoyi Resident'),
('Immigration Officer'),
('Jailed'),
('Journalist (Delta Employee)'),
('Journalist (FCT Employee)'),
('Journalist (Lagos Employee)'),
('Kubwa Resident'),
('Lagos Chief of Police'),
('Lagos Commissioner'),
('Lagos Commissioner of Agriculture'),
('Lagos Commissioner of Commerce'),
('Lagos Commissioner of Finance'),
('Lagos Commissioner of Petroleum'),
('Lagos Commissioner of Power and Water'),
('Lagos Deputy Chief of Police'),
('Lagos Governor'),
('Lagos Indigine'),
('Lagos Resident'),
('Lawyers (Delta Employee)'),
('Lawyers (Lagos Employee)'),
('Lecturer'),
('Lekki Phase 1 Resident'),
('Lekki Phase 2 Resident'),
('Maitama Resident'),
('Media Manager (Delta Employee)'),
('Media Manager (FCT Employee)'),
('Media Manager (Lagos Employee)'),
('Media Staff (Delta Employee)'),
('Media Staff (FCT Employee)'),
('Media Staff (Lagos Employee)'),
('Medic Staff'),
('Medic Staff (Delta Employee)'),
('Medic Staff (FCT Employee)'),
('Medic Staff (Lagos Employee)'),
('Minister of Agriculture'),
('Minister of Education'),
('Minister of Finance'),
('Minister of Health'),
('Minister of Housing'),
('Minister of Information and Culture'),
('Minister of Petroleum'),
('Minister of Power and Water'),
('Minister of Trade and Commerce'),
('Nursing Student'),
('Out Patient'),
('Police Officer (Delta Employee)'),
('Police Officer (FCT Employee)'),
('Police Officer (Lagos Employee)'),
('Police Station Visitor'),
('President'),
('Rancher'),
('Reporter (Delta Employee)'),
('Reporter (FCT Employee)'),
('Reporter (Lagos Employee)'),
('Rookie'),
('Sapele Resident'),
('Student'),
('Supplier'),
('Supreme Judge'),
('Supreme Judge (Delta Employee)'),
('Supreme Judge (Lagos Employee)'),
('Surgery Patient'),
('Suspect'),
('Technician (Delta Employee)'),
('Technician (FCT Employee)'),
('Technician (Lagos Employee)'),
('Trader'),
('Ughelli Resident'),
('Vice President'),
('Warri Resident'),
('Yaba Resident')
ON CONFLICT (name) DO NOTHING;
